### ISSUE TITLE
SQLite storage in Cordova, instead of IndexedDB

### ISSUE THREAD

**Issue by londonshliach** [shaka-project/shaka-player#1005]
I am using Shaka player in a Cordova app for Android and I want to download videos for when the user is offline.

Shaka player uses IndexedDB for storage, and WebViews on Android only have about 10MB available for IndexedDB.

Cordova has several storage plugins, including a SQLite plugin which has no size limitations.

I was wondering if there's any way to configure Shaka player to use the SQLite plugin (or any other storage option,) to save videos for offline use.

Thanks for the help.

**Comment by joeyparrish** [comment]
Yes!  There is a well-defined interface for you to add SQLite support.

We have an abstract interface for a storage engine: `shaka.offline.IStorageEngine`, defined in lib/offline/i_storage_engine.js.  There is currently one implementation of that interface, called `shaka.offline.DBEngine`, defined in lib/offline/db_engine.js, which uses IndexedDB.  The choice of an implementation is made in `shaka.offline.OfflineUtils.createStorageEngine`.

I suggest the following:

1. Since "DB" would be ambiguous, rename `DBEngine` to `IndexedDBEngine` (and db_engine.js to indexed_db_engine.js) in both lib/offline/ and tests/offline/
2. Create `SQLiteEngine` (in lib/offline/sqlite_engine.js) to implement IStorageEngine for Cordova
3. Modify `shaka.offline.OfflineUtils.createStorageEngine` to prefer Cordova's version, if supported, and fall back to IndexedDB otherwise
4. Modify `shaka.offline.OfflineUtils.isStorageEngineSupported` to check for both versions.
5. Send us a PR!

**Comment by patbenatar** [comment]
@joeyparrish thanks for this detailed write-up! Follow-up question: is there a way to use app-specific implementations of `shaka.offline.IStorageEngine` in case I wanted to make a very specific version that wouldn't make sense to be shipped inside of Shaka player itself?

**Comment by joeyparrish** [comment]
Not at the moment, but we could build this out into a proper plugin interface.

**Comment by avelad** [comment]
Anyone interested in this? If no one responds to the thread in 7 days, it will be closed automatically. Thank you!
