### ISSUE TITLE
Make SimpleAbrManager more extensible

### ISSUE THREAD

**Issue by ondrejpar** [shaka-project/shaka-player#1100]
The filterAndSortVariants_ method is always called on shaka.abr.SimpleAbrManager. I'd like do do my own variant filtering (and nothing else), it would be great if I could just inherit SimpleAbrManager and override this single method.

**Comment by TheModMaker** [comment]
That is an interesting idea, but unfortunately it won't work.  We use the closure compiler to compile the library.  Since that method is private and not exported, the compiler will rename it to reduce space.  I don't think we should export it since it won't be used by 99% of people.

But we will think about ways to enhance the default ABR manager to make it easier to extend only pieces of it.

**Comment by avelad** [comment]
Is anyone interested in this? If not, the issue will be closed in 7 days.
