### ISSUE TITLE
Method to update manifest URI

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1201]
A partner recently asked if there was a way to update the manifest URI for a piece of content at the application level without reloading the content.

There are a couple of workarounds possible with Shaka Player today, but none of them is very natural.  It should not be very difficult to add an explicit API for this on `Player` and pass the information to the manifest parser through the `ManifestParser` plugin API.

In the mean time, this could be worked around client-side using a request filter:

```js
// Using a request filter:
player.getNetworkingEngine().registerRequestFilter(function(type, request) {
  if (type != shaka.net.NetworkingEngine.RequestType.MANIFEST) return;
  // Replace the manifest URI with an updated URI on every request before it goes out.
  request.uris = [ latestManifestUri ];
});
```

For DASH, this could also be managed server-side using a `<Location>` element in the manifest to point to a new manifest URI.

**Comment by chrisfillmore** [comment]
We are trying to do this and are having some problems. Is there a requirement that the manifest to which we redirect be identical to previous ones? What if the new manifest points to the same content, but presented differently in the manifest?

By "presented differently" I mean:
- `availabilityStartTime` is different
- `timeShiftBufferDepth` is different
- `Period@start` is different
- Segment times `S@t` are different, and there may be different amounts of segments per manifest
- `presentationTimeOffset` is different

Both use `SegmentTemplate` + `SegmentTimeline`.

I haven't dug deeply into the player's behaviour yet, but on observation I see that playback stalls when I try to switch the manifest, and doesn't recover.

Either manifest on its own plays fine in Shaka, it's just the switching that doesn't work. This may be a loaded question, but would you expect this to work?

I will see if I can put together a demo. Thanks.

**Comment by joeyparrish** [comment]
If you change everything about it, then I would expect you to have issues.  :-)

What happens when we update the manifest is that we merge the old information and the new.  If I recall correctly, as of v2.5, this happens first at the period level.  So if there's no relation between the periods of the original and the updated manifest, I would expect playback to fail in one way or another.

In v2.6, we plan to flatten periods into a list of segments in the DASH parser, so this would be less of an issue post v2.6.

As for the rest, availabilityStartTime is ignored by default for SegmentTimeline, and timeShiftBufferDepth can change at any time without causing any trouble.  Segment times are combined with presentationTimeOffset and period start, so I think those might be fine to change to some degree if the periods align.

**Comment by chrisfillmore** [comment]
Just to clarify, we are still using 2.4.0. Is `availabilityStartTime` ignored for that version?

**Comment by joeyparrish** [comment]
No, that's starting in one of the v2.5 betas.  So changing AST would also be an issue for you, as that will affect our view of the availability window.

**Comment by chrisfillmore** [comment]
Theoretically, could the player construct a new PresentationTimeline on manifest change? Do you think playback could recover?

This is of some interest to us, because we have a variety of failover scenarios to support, and it would be nice to recover within the same playback session. We could potentially work on a PR if you thought it was possible.

The manifests we fail over to are the "same content", i.e. the same live stream, but different: ads versus no ads, longer timeShiftBufferDepth versus shorter. Some of the manifests are processed by an external vendor before being passed to the player. So, we aren't always certain that the timeline described in the manifest will be exactly the same.

There is another reason we want this -- we experience persistent playback problems on Tizen when a stream starts in clear content and switches to encrypted. Being able to start with a stream we knew was completely encrypted, then switch to a blended one, would be nice.

**Comment by avelad** [comment]
Is anyone interested in seeing this supported?
