### ISSUE TITLE
Tests for multiple concurrent playbacks

### ISSUE THREAD

**Issue by chrisfillmore** [shaka-project/shaka-player#1205]
I'm curious to what extent Shaka is tested in scenarios with multiple Players. I have the same requirement as #1166, to deliver up to 4 concurrent playbacks.

I took a quick look at player_unit and player_integration and only see one video element in use in each. The demo app is also limited to one video element. This seems like a gap. Would Shaka team consider adding either or both of the following?
- Test coverage for multiple concurrent Players
- Support for multiple video elements / Players in the sample app (this would be useful for assessing performance qualitatively)

I realize this could be a bunch of work, but it looks like multi-Player playback isn't treated as a use case at all, even though it's possible to do.

**Comment by joeyparrish** [comment]
Multiple concurrent players and video elements is supported by the library, but may not be supported by every platform.  Many embedded devices exist which cannot support multiple video elements.

We've avoided singletons to make sure it is possible to have multiple players, and we explicitly support this in the library.

We could add tests to cover multiple concurrent playbacks.  I'm fairly sure the desktop browsers would support multiple playbacks, but those tests might fail on Chromecast or Tizen TVs, which would require us to disable those tests on specific platforms.

If you want to put together a set of multi-player playback tests, I'd be happy to review a PR for it.  I suggest you add another file, maybe `test/multi_player_integration.js`, since these tests will have a different setup from the other player tests and may need to be skipped on certain platforms.

**Comment by chrisfillmore** [comment]
Tizen definitely does not support it. I also read somewhere (maybe here) that Chromecast team recommends against multiple video elements, but I'm not sure what that means. I'm happy to contribute for this but it probably won't happen soon.

**Comment by avelad** [comment]
Is anyone interested in seeing this in the future? Otherwise the issue will be closed in 7 days.
