### ISSUE TITLE
Consider removing IE EME polyfill from the default build

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1261]
With the fix for #1260, we are not shipping absolutely everything needed for IE11 support.  We should consider splitting off the EME polyfill we use on IE11 as well.  Then, apps could save even more space if they choose not to support IE11.  The IE EME polyfill (shaka.polyfill.PatchedMediaKeysMs) costs about 8.5kB in the compiled bundle (about 4%).

**Comment by chrisfillmore** [comment]
I'm making a push for our next major version update to drop support for IE11, so this sounds good to me.

**Comment by boredom2** [comment]
Can someone please help me finding out, how exactly the Situation for IE11 is currently?
As far as I can see, it is not supported on IE11 on Windows 7 or lower.
On Windows 10 (which I run), it works fine with 2.3.3.
The Homepage on Git here mentions a seperate PolyFill, that is needed - but is it needed already? And for what? Due to the Fact, that it runs fine currently, I dont see the need for a PolyFill?

Thanks for the Clarifications,
Christoph

**Comment by TheModMaker** [comment]
@boredom2 We support IE11 on Windows 8 and 10.  Windows 7 and below isn't supported because (I think) it doesn't expose `MediaSource`, which we need to play media.  We require the use of any `Promise` polyfill to be able to run.  The demo app does this by loading [es6-promise-polyfill](https://github.com/lahmatiy/es6-promise-polyfill).  But in a custom app, you'll need to manually load any `Promise` polyfill on IE11.

We need a polyfill since IE11 doesn't implement the `Promise` type, which we use extensively in the library.  We used to have our own, but we decided to remove it in favor of an external one, which the app can load if they want IE11 support.  This isn't needed on any other browser since they all implement Promises.

This issue is about our [EME polyfill](https://github.com/google/shaka-player/blob/master/lib/polyfill/patchedmediakeys_ms.js), which is required to be able to play encrypted content on IE11.

---

Also note to everyone: you can remove the EME polyfill using a custom build configuration:

```bash
# Remove just the IE11 polyfill:
./build/build.py +@complete -lib/polyfill/patchedmediakeys_ms.js
# Or removing all polyfills:
./build/build.py +@complete -@polyfill
```

See `./build/build.py --help` and the [customizing the build](https://shaka-player-demo.appspot.com/docs/api/tutorial-plugins.html) tutorial for more info.

**Comment by TheModMaker** [comment]
Actually you can't remove just the IE11 polyfill, the only option is to remove all the EME polyfills.  We should rewrite them so you can just remove one kind of EME polyfill.

**Comment by boredom2** [comment]
Thanks for Explanation.
I also understand now, why 2.3.3 works in our Player in IE11 without including this Polyfill.
Obviously, we include a Promise PolyFill ourselves also :)

Thanks a lot!

**Comment by avelad** [comment]
Already done in v4.0.0
