### ISSUE TITLE
Support for DASH Metrics

### ISSUE THREAD

**Issue by calvinschmidt** [shaka-project/shaka-player#1442]
Hi there,
this is not a bug, more likely a feature request or just looking for some help.

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.3.7

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: custom app

**If custom app, can you reproduce the issue using our demo app?**: yes

**What browser and OS are you using?**: Chrome 66.0.3359.181 on macOS High Sierra 10.13.2

I'd like to use shaka player to allocate the metrics HttpList, RepSwitchList, BufferLevel and PlayList specified in the ISO/IEC 23009-1 DASH standard.

The dash reference player provides an event "METRIC_ADDED" for all the specified metrics to which you can listen to: https://cdn.dashjs.org/v2.6.0/jsdoc/MediaPlayerEvents.html#event:METRIC_ADDED__anchor

For shaka player though I wasn't able to identify such an event. Hence, I am trying to calculate the metrics by myself from the stats I receive calling shaka.Player().getStats(). However they aren't sufficient enough to calculate all the metrics. Does shaka player already support these metrics or are there other methods which would help calculating them?

Thanks in advance and kind regards,
Calvin

**Comment by theodab** [comment]
Shaka Player currently ignores the Metrics element.
Adding some kind of event along the lines of METRIC_ADDED when it detects a Metrics element would be a fairly simple change.
Actually tracking the requested metrics would be significantly more complex. I'll hesitantly put this in the backlog for now. Maybe we'll decide to put it in 2.5, maybe not.

In the meantime...

You could track http transactions with a custom network scheme plugin. Just make one that acts as a wrapper over the default xhr or Fetch plugin. You can register network plugins with [shaka.net.NetworkingEngine.registerScheme](https://shaka-player-demo.appspot.com/docs/api/shaka.net.NetworkingEngine.html#.registerScheme).

You might be able to track RepSwitchList the same way, if you could figure out what representation an http request corresponds to from the URL. I'm not sure if that's possible or not off the top of my head.

BufferLevel... honestly, I can't tell what this metric is measuring, from the description in the ISO/IEC 23009-1 DASH standard. There doesn't seem to be a definition for "buffer occupancy level". 

PlayList, you could measure yourself with enough event listeners.  combination of a lot of event listeners on the  ('play' event, 'pause' event, etc on the media element) to detect user input, an `ended` event listener to determine end of playback, and an `error` event listener

PlayList, you could measure yourself with enough event listeners. On the video element, you could put a `play` listener, a `pause` listener, etc to detect user input, and an `ended` listener to detect end of playback. On the Shaka Player, you could put an `error` event listener to detect failure that stops playback. Note that the `error` event on Shaka Player contains a [shaka.util.Error](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#.Severity) object; you'll probably want to examine that error object's `severity` field, so that you can ignore recoverable errors.

**Comment by avelad** [comment]
Is anyone interested in seeing this supported?
