### ISSUE TITLE
Allow playback without audio when codec is not supported

### ISSUE THREAD

**Issue by lifecoderua** [shaka-project/shaka-player#1791]
I have a manifest where AC3 audio is not supported. This results in playback refuses to play anything at all.
Is it possible to run the video only, with audio disabled for such case?

**Comment by TheModMaker** [comment]
I assume this is DASH content?  If this is HLS you can just create a video-only variant and we'll play that if we can't play any video+audio variants.  The problem with DASH is you specify a list of video streams to play and a list of audio streams and we combine them.  There isn't a way to specify that you want to allow or forbid playing video-only or audio-only.

We could add a feature to allow playing with just video content (which would be consistent with many HLS manifests).  But this has the problem of not throwing an error if the user doesn't expect it.  Usually it should be an error if we can't play any audio or video streams.

So this will probably be behind a configuration option to ensure that this only happens if you explicitly allow it.  Probably `manifest.dash.allowAudioOnly` and `manifest.dash.allowVideoOnly`.

**Comment by lifecoderua** [comment]
Yes, it's a DASH container.

Option sounds logical, maybe even opt out for UI prompt ("This video may be played only without audio track. Do you want to proceed?").

Talking about exception, it would be nice to handle it in a more readable way. While Firefox is so nice to provide an exception text for human beings, Chrome is not - it's message is quite cryptic.

**Comment by avelad** [comment]
This is already supported with `manifest.disableAudio` or `manifest.disableVideo` configs

**Comment by joeyparrish** [comment]
Agreed.
