### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by liambresnahan** [shaka-project/shaka-player#2032]
I took a look through the roadmap and other questions but couldn't find out if Android TV as a platform has been requested before and / or is supported, could someone comment?

I'd really like to have a single player implementation over multiple platforms and Shaka looks like a good option for that if possible.

**Comment by theodab** [comment]
Shaka Player is based on a number of browser APIs. So it needs a browser environment to run. We don't currently test on Android TV, so I can't say for sure if Shaka Player will work on Android TV browsers.

We do have a related project, [Shaka Player Embedded](https://github.com/google/shaka-player-embedded), which is for embedding into apps (that is, it does not require a browser environment). However, at the moment, Shaka Player Embedded is only for iOS; we could theoretically add Android support, yes, but at the moment we don't think it's worth the development time, since Google already has [ExoPlayer](https://github.com/google/ExoPlayer).

**Comment by joeyparrish** [comment]
I'll ask around if anyone at the office has an Android TV we could poke at to determine its capabilities.  But the main thing is that, as @theodab points out, Shaka Player runs in a browser environment.  It should be possible to run Shaka Player in a browser on ATV, and it may be possible to run Shaka Player in a web app packaged as an APK, either using "[Trusted Web Activities](https://developers.google.com/web/updates/2019/02/using-twa)" or WebView.

For Shaka Player to call anything an "officially supported" platform, we have to have one in our lab and run tests on it nightly.  These are listed in our [README](https://github.com/google/shaka-player/blob/master/README.md#platform-and-browser-support-matrix).  But many unofficial, community-supported platforms can run Shaka Player anyway, such as XBox One, Tizen 4, etc.  We are always accepting pull requests to add support for these additional platforms.

**Comment by liambresnahan** [comment]
thanks for the info all. This helps a lot. I had seen Shaka Player Embedded but noticed that didn't support Android TV. It seems like this might be a good platform to target as having a single player over many places would be very nice. However totally understand this needs work / prioritization
