### ISSUE TITLE
Provide the close button (like in the demo) as part of the UI library.

### ISSUE THREAD

**Issue by ivansteff** [shaka-project/shaka-player#2316]
How to add a cross to close the player, as is done on [shaka demo](https://shaka-player-demo.appspot.com/demo/#audiolang=ru-RU;textlang=ru-RU;uilang=ru-RU;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;panel=HOME;build=compiled) ?
![image](https://user-images.githubusercontent.com/31563237/71356283-c479f000-2592-11ea-80aa-c0ff6992c001.png)

Is it possible to do this? Or i need to separately create a block, set position it and hang up the player’s closing event

**Comment by ismena** [comment]
It's a custom button we created for the demo: https://github.com/google/shaka-player/blob/master/demo/close_button.js

I think, we could offer it as part of the library if there's interest - let me convert the issue to an enhancement to do that.
In the meantime, feel free to just copy our code for the button to your project, if you need the button sooner rather than later. The css for it it is [here](https://github.com/google/shaka-player/blob/master/demo/demo.less#L49).

**Comment by ivansteff** [comment]
@ismena  Got it, thanks =)

**Comment by akashgp09** [comment]
hey there, i am intrested to work on this issue. I have a simple query. If i made changes to the code, how can i test it locally ?

**Comment by joeyparrish** [comment]
You can lint, compile, and run automated tests with:

```sh
python build/all.py
python build/test.py
```

There are some tests covering the UI, but existing tests won't cover the new button.  (Still run them, though, to make sure you didn't break any existing features.)  You can add new automated tests in the test/ui/ folder.  Let us know if you have any questions about the tests, which are written with Jasmine (https://jasmine.github.io/). 

You can also test the new button manually by loading the demo page from your working directory.  Just point any local web server at your shaka-player folder, then in your browser load http://localhost/demo/ .  If you are already familiar with local web server setup, feel free to set this up in a subfolder, rather than the server's document root.  The Shaka Player demo works on relative paths only, and can be hosted at any location in your local web server.

Shaka Player **cannot** work with file:/// URLs, though, so a local webserver is required for manual testing in your browser.

Some of us use Apache locally (https://httpd.apache.org/), while others prefer something ad-hoc like `python3 -m http.server` or `python2 -m SimpleHTTPServer` running in the shaka-player folder.  If you take the python route for this, take note of the port number and use that in your localhost URL.

Does this help?

**Comment by subodhk01** [comment]
Working on a PR(#3200) related to this issue

**Comment by MayankVir** [comment]
Hi, @ismena @joeyparrish Is this issue available for work?

**Comment by michellezhuogg** [comment]
Hello @MayankVir, we have an ongoing PR with part of the work done. You're welcome to look into other issues to make the most of your time.

**Comment by MayankVir** [comment]
Okay sure!

**Comment by aaazacky** [comment]
@michellezhuogg @joeyparrish I am GSoC aspirant I just wanted to ask since @subodhk01 is working on this issue can I still apply for GSoC project 'Add Close Button to the UI Library'?

**Comment by avelad** [comment]
Any one is interested on it? If not, the issue will be closed automatically in 7 days.
