### ISSUE TITLE
Add overflowMenuButtons to the UI bar

### ISSUE THREAD

**Issue by ThomasLohmann** [shaka-project/shaka-player#2676]
Hi everyone, is it possible to add buttons from the overflowMenu to the UI bar e.g. the quality button? I was not able to find a solution. If it's not possible, it would be great to make it more flexible in one of the next releases. Please, see the following link: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html

Kind regards,
Thomas

**Comment by ismena** [comment]
Let me make sure I understand correctly, you'd like some of the overflow buttons to go to the main UI button panel like the mute button etc, is that correct?

We currently don't have an out-of-the-box solution for that, but it's feasible and I'm open to scheduling it for a future release.
If you need this feature sooner,  let me know - I can coach you through creating a custom button like that.

**Comment by ismena** [comment]
We are also happy to accept a pull request for this, if anyone in the community is willing to contribute.

**Comment by ThomasLohmann** [comment]
Hi @ismena, first of all sry for my delayed answer.

Yes, that's correct. So we should be able to put e.g. the quality button to the main UI bar where the fullscreen button is placed etc. Maybe we can make it even more flexible and put the buttons from the UI bar to the overflowMenu and the other way around.

If you already have a custom solution in mind how I can place the quality button on the left to the fullscreen button it would be great!

**Comment by ismena** [comment]
The overflow buttons and the panel buttons have a bit different structure code-wise. Essentially, there'll need to be 2 versions of each button to support placing them wherever people want.
Let me try and sketch something for you that you can follow to create a button. I'm putting a note on my calendar to look at this tomorrow! :)

**Comment by ThomasLohmann** [comment]
Thanks a lot for your help!

**Comment by ismena** [comment]
Alright, here's a rough sketch that I put together, it's a combination of our resolution menu from the overflow and a random button panel button :)


```
ResolutionButton = class extends shaka.ui.Element {
  /**
   * @param {!HTMLElement} parent
   * @param {!shaka.ui.Controls} controls
   */
  constructor(parent, controls) {
    super(parent, controls);

    /** @private {!HTMLElement} */
    this.button_ = shaka.util.Dom.createHTMLElement('button');
    // Your class name to style with css
    this.button_.classList.add('yourClassName');
    this.button_.classList.add('material-icons');
    this.button_.textContent = shaka.ui.Enums.MaterialDesignIcons.RESOLUTION;
    this.parent.appendChild(this.button_);
    this.addMenu_();

    this.eventManager.listen(this.button_, 'click', () => {
      this.onButtonClick_();
    });

    this.eventManager.listen(this.player, 'variantchanged', () => {
      this.updateResolutionSelection_();
    });

    this.eventManager.listen(this.player, 'trackschanged', () => {
      this.updateResolutionSelection_();
    });

    this.eventManager.listen(this.player, 'abrstatuschanged', () => {
      this.updateResolutionSelection_();
    });

    this.updateResolutionSelection_();

    // Set up all the strings in the user's preferred language.
    this.updateLocalizedStrings_();
  }

  /** @private */
  addMenu_() {
    /** @protected {!HTMLElement}*/
    this.menu = shaka.util.Dom.createHTMLElement('div');
    this.menu.classList.add('shaka-no-propagation');
    // Your class to style the menu with css
    this.menu.classList.add('yourMenuClass');
    this.menu.classList.add('shaka-show-controls-on-mouse-over');
    this.menu.classList.add('shaka-hidden');

    const controlsContainer = this.controls.getControlsContainer();
    controlsContainer.appendChild(this.menu);
  }

  /** @private */
  onButtonClick_() {
    shaka.ui.Utils.setDisplay(this.menu, true);
    shaka.ui.Utils.focusOnTheChosenItem(this.menu);
  }

  /** @private */
  updateResolutionSelection_() {
    /** @type {!Array.<shaka.extern.Track>} */
    let tracks = this.player.getVariantTracks();

    // Hide resolution menu and button for audio-only content and src= content
    // without resolution information.
    // TODO: for audio-only content, this should be a bitrate selection menu
    // instead.
    if (tracks.length && !tracks[0].height) {
      shaka.ui.Utils.setDisplay(this.menu, false);
      shaka.ui.Utils.setDisplay(this.button_, false);
      return;
    }
    // Otherwise, restore it.
    shaka.ui.Utils.setDisplay(this.button_, true);

    tracks.sort((t1, t2) => {
      goog.asserts.assert(t1.height != null, 'Null height');
      goog.asserts.assert(t2.height != null, 'Null height');
      return t2.height - t1.height;
    });

    // If there is a selected variant track, then we filter out any tracks in
    // a different language.  Then we use those remaining tracks to display the
    // available resolutions.
    const selectedTrack = tracks.find((track) => track.active);
    if (selectedTrack) {
      // Filter by current audio language and channel count.
      tracks = tracks.filter(
          (track) => track.language == selectedTrack.language &&
              track.channelsCount == selectedTrack.channelsCount);
    }

    // Remove duplicate entries with the same height.  This can happen if
    // we have multiple resolutions of audio.  Pick an arbitrary one.
    tracks = tracks.filter((track, idx) => {
      // Keep the first one with the same height.
      const otherIdx = tracks.findIndex((t) => t.height == track.height);
      return otherIdx == idx;
    });

    shaka.util.Dom.removeAllChildren(this.menu);

    const abrEnabled = this.player.getConfiguration().abr.enabled;

    // Add new ones
    for (const track of tracks) {
      const button = shaka.util.Dom.createHTMLElement('button');
      this.eventManager.listen(button, 'click',
          () => this.onTrackSelected_(track));

      const span = shaka.util.Dom.createHTMLElement('span');
      span.textContent = track.height + 'p';
      button.appendChild(span);

      if (!abrEnabled && track == selectedTrack) {
        // If abr is disabled, mark the selected track's resolution.
        button.setAttribute('aria-selected', 'true');
        button.appendChild(shaka.ui.Utils.checkmarkIcon());
        span.classList.add('shaka-chosen-item');
      }
      this.menu.appendChild(button);
    }

    // Add the Auto button
    const autoButton = shaka.util.Dom.createHTMLElement('button');
    autoButton.classList.add('shaka-enable-abr-button');
    this.eventManager.listen(autoButton, 'click', () => {
      const config = {abr: {enabled: true}};
      this.player.configure(config);
      this.updateResolutionSelection_();
    });

    /** @private {!HTMLElement}*/
    this.abrOnSpan_ = shaka.util.Dom.createHTMLElement('span');
    this.abrOnSpan_.classList.add('shaka-auto-span');
    this.abrOnSpan_.textContent =
        this.localization.resolve(shaka.ui.Locales.Ids.AUTO_QUALITY);
    autoButton.appendChild(this.abrOnSpan_);

    // If abr is enabled reflect it by marking 'Auto' as selected.
    if (abrEnabled) {
      autoButton.setAttribute('aria-selected', 'true');
      autoButton.appendChild(shaka.ui.Utils.checkmarkIcon());

      this.abrOnSpan_.classList.add('shaka-chosen-item');
    }

    this.menu.appendChild(autoButton);
    shaka.ui.Utils.focusOnTheChosenItem(this.menu);
    this.controls.dispatchEvent(
        new shaka.util.FakeEvent('resolutionselectionupdated'));
  }

  /**
   * @param {!shaka.extern.Track} track
   * @private
   */
  onTrackSelected_(track) {
    // Disable abr manager before changing tracks.
    const config = {abr: {enabled: false}};
    this.player.configure(config);
    const clearBuffer = this.controls.getConfig().clearBufferOnQualityChange;
    this.player.selectVariantTrack(track, clearBuffer);
  }


  /**
   * @private
   */
  updateLocalizedStrings_() {
    const LocIds = shaka.ui.Locales.Ids;

    this.button_.setAttribute(shaka.ui.Constants.ARIA_LABEL,
        this.localization.resolve(LocIds.RESOLUTION));
    this.abrOnSpan_.textContent =
        this.localization.resolve(LocIds.AUTO_QUALITY);
  }
};


/**
 * @implements {shaka.extern.IUIElement.Factory}
 * @final
 */
ResolutionButton.Factory = class {
  /** @override */
  create(rootElement, controls) {
    return new ResolutionButton(rootElement, controls);
  }
};
```

You will still need to style the menu with CSS to make it look good and put it where you want it to go, and register the new button with the controls:
```
shaka.ui.Controls.registerElement('resolution', new ResolutionButton.Factory());
```

After this, you should be able to put it into the list of the buttons you want like the customization tutorial shows.

You might have to tweak other things (some of the utils I'm using might not be available outside the lib and so on), but I hope this gets you to a healthy start :)

**Comment by DDeis** [comment]
Hi @ismena, I was trying to create similar custom controls when I came accross this issue.

What do you have in mind by "tweak other things" ? In this case we can easily replace `shaka.util.Dom.createHTMLElement`, `shaka.ui.Enums.MaterialDesignIcons.RESOLUTION` or `shaka.ui.Constants.ARIA_LABEL` for instance, and replace `shaka.ui.Utils.setDisplay` by either `element.classList.ad('shaka-hidden')` or `element.classList.remove('shaka-hidden')`, but what about "more complicated" functions like `shaka.ui.Utils.focusOnTheChosenItem` ?

Wouldn't it be useful for developers to be able to use Utils/Constant/Enums/Locales and for instance be able to extend RangeElement for creating custom seek bar ? Otherwise what would be the "shaka" way for this ?

**Comment by ThomasLohmann** [comment]
@ismena thanks for your crazy long solution! My plan was just to change the position of a button and not flying to the moon in a automatic fashion :). If you have any simpler solution in mind, please just let me know ;).

**Comment by ismena** [comment]
@ThomasLohmann 
Sigh. I know. That's why I originally mentioned that we should schedule this as a feature and provide it out of the box, so all the automatic flying is done by us and none of the automatic flying is done by the users.
I'll put it on the UI roadmap to provide this, on add some boiler plate code to at least make it much easier to do so.

@DDeis Sorry, I'm not 100% clear what you mean. Would you like the stuff like Constants and internal functions to be exposed outside of the library so the apps could use them?

**Comment by ThomasLohmann** [comment]
@shaka-bot yes, you can close this issue. 

Thanks for all your answers and solutiond!

**Comment by joeyparrish** [comment]
I'm removing the "question" tag and reopening this as a UI enhancement.  The main idea as I understand it is to make the overflow menu items more flexible.

I imagine we could create a hybrid class that represents UI elements that could be configured either on the main panel *or* the overflow menu.  The class could expose a DOM element for each case, and applications could put that element's name in either the main panel or overflow menu purely by configuration.  Overflow menu items which have sub-menus could still pop up those sub-menus when the main panel version of the button is clicked.

**Comment by joeyparrish** [comment]
I've found in my own personal projects that it would be really nice to have a "cast" button that I could put into the main buttons panel.  It was only 89 lines of code to do it as a plugin at the app level, but it was basically all duplicated code from the existing overflow menu button.

A base class that could allow the button to be placed into either location without duplicating the functionality would be really nice.

**Comment by michellezhuogg** [comment]
<img width="818" alt="Screen Shot 2021-02-25 at 10 54 48 PM" src="https://user-images.githubusercontent.com/28269801/109266388-dec5e400-77bc-11eb-9ac8-dda3dac53bf4.png">

**Comment by nbcl** [comment]
**Dear @michellezhuogg,**

I encountered this issue in the ideas list and was really interested by it, specially because I have seen that multiple video players tend to have as many buttons as possible on what would be the "control panel" section, in the interest of facilitating accessibility to them! 

I started sketching an initial proposal in my head but I was encountered with a design doubt, considering that the project website suggested, as a possible solution, having two versions of each button.

Personally, I think that @joeyparrish's suggested design (having a hybrid base class) would be a great approach as it would avoid having duplicate code sources for each button.

On the other hand, I also think that having an "overflow menu" and a "control panel" version of each button could simplify the development roadmap and would initially make the project's scope smaller, without denying the possibility of merging them by creating a hybrid version in the long run.

This could be beneficial considering that the student's guide indicates us that we should lean proposals onto being more often under than over-scoped to assure the completion of deliverables.

Having those approaches under consideration, and in the interest of writing a (great!) initial proposal, I would appreciate having your directions, regarding which approach should the ideal design be focusing into!

Finally, I would appreciate if you let me know if this (GitHub) is not the ideal way of reaching to you with this type of inquiries and if I should continue this conversation in the mailing list or directly to your email! 

(I decided to write in the issue as this conversation could also be beneficial to the whole community and not only to my personal proposal.)

**Thank you very much!**

**Comment by nbcl** [comment]
**3/14/2021 Update!**

I had a really interesting weekend diving down and studying the codebase on which I managed to develop a "control panel" version of the "picture in picture" button by following the "two versions" code design that I mentioned in my previous comment.

> Having an "overflow menu" and a "control panel" version of each button

The implementation mainly reuses code from `ui/pip_button.js` to create a new `ui/loop_button_control.js` that can be added to the UI as follows.

```js
const config = {
    ...
    'controlPanelElements': [... 'picture_in_picture', ...],
    ...
};
```

This achieves the following functionality:

<p align=center>
<img src="https://nbcl.github.io/images/nopip.png" width=500>
<img src="https://nbcl.github.io/images/pip.png" width=500>
</p>

I have uploaded the changes to my personal fork [@nbcl/shaka-player](https://github.com/nbcl/shaka-player) just as a proof of concept as I'm looking forward into receiving the team's directions regarding which approach should the ideal design be focused into!

If this design works, I would be happy to follow the issue with a pull request after adding the corresponding documentation, and would look forward onto having the opportunity of expanding this feature to the other "overflow menu" buttons.

**Thank you very much!**

**Comment by michellezhuogg** [comment]
Hello Nico, thank you so much for your careful analysis and your proof of concept! 
I agree with you that having a hybrid base class would be a great approach as it would avoid having duplicate code sources for each button. Let's see that's possible to implement, and if not, we can fallback the "two versions of the buttons" solution. Let us know what you think!

**Comment by nbcl** [comment]
Understood, I am on it!

I will follow back with an updated proof of concept as soon as I am able to reach the expected outcome under the hybrid base class design. 

Thank you very much for your guidance!

**Comment by nbcl** [comment]
The new design is up and running!

The hybrid-class implementation works by adding the "overflows" `@param` to `shaka.ui.PipButton` which is checked via `this.overflows_` while building the class, performing a conditioned addition of the "overflow menu"-exclusive features that can then be ignored when communicating with the "control panel" version of the button.

This achieves exactly the same behavior as the proof of concept of the "two-version" approach in my previous comment, and overall, due to the design avoiding having duplicate code sources, it only adds 30 lines of code to `ui/pip_button.js`, making a considerable improvement in comparison to the previous implementation, which added 173!

I uploaded the resulting updates to a new branch in my personal fork, [@nbcl/shaka-player:feat-2676-hybrid](https://github.com/nbcl/shaka-player/tree/feat-2676-hybrid).

I would really appreciate knowing if this new implementation achieves the ideal code design for this scenario, so that I can continue studying similar solutions for the remaining "overflow menu" buttons!

Finally, I would like to thank you once again for your previous comment, as it pushed me forward to challenge myself with this new design. 

@michellezhuogg

**Comment by joeyparrish** [comment]
My only criticism for what you have in your branch now is the name `this.overflows_`.  As a boolean, it sounds like "yes, this thing overflows", which doesn't make sense to me.  I would suggest `this.inOverflowMenu_` or something similar.

I wonder: is there some way to generalize this?  We could add the same booleans to various overflow menu items and repeat the same process of excluding their other components, but I wonder if we can come up with something better.

The basic premise here seems to be "when this is not an overflow menu item, exclude these certain elements".  What if we instead added a classname to all those "excluded" elements, and used CSS to remove them (`display: none`) when they are outside of the overflow menu?  That way, each element that can live in either context simply needs to tag the elements that only show in overflow context.  You wouldn't even need the boolean.

It's probably just getting late here, and I'm tired, but I can't decide if the CSS approach is better.  I tend to think yes, because it's declarative, and you don't have to worry about wrapping if() around every access to those components.  Once you've tagged them with the classname during the initial setup, you can forget all about the differences everywhere else.

@nbcl, @michellezhuogg, @ismena, what do y'all think about these two approaches?

Looking through our overflow menu items, I see some are simple, like PIP, but some have submenus, like language or resolution.  If these submenus are going to be possible outside of overflow menu context, I think that would take some more thought and careful design.  Perhaps this can be a second phase of work after the easy ones are done.

**Comment by nbcl** [comment]
@joeyparrish, I completely agree with the CSS approach. 

I implemented it [@nbcl/shaka-player:feat-2676-hybrid](https://github.com/nbcl/shaka-player/tree/feat-2676-hybrid) achieving the intended functionality in a declarative way with no conditionals needed and only virtually adding 1 line of code, apart from the class and registration, of course. 

If I am not mistaken, this can be expanded to achieve the same final product for at least the Loop and AirPlay buttons with minimal extra code needed, which is great.

On the other hand, regarding the remaining buttons, 

> I think that would take some more thought and careful design. Perhaps this can be a second phase of work after the easy ones are done.

I also agree. 

I am trying to approach this challenge in careful and iterative manner with the interest of achieving the ideal design, so I started by investigating the simpler buttons to build a strong foundation for my understanding of the codebase. 

Now, the remaining buttons, should also solve the "exclude these certain elements" problem when placed in the control panel but, apart from that, as you mentioned, will also need to be able to display their submenus when placed outside the context of the original overflow menu.

I think is time for me to investigate a solution that will lead us to solve that second phase of this problem.

I will follow back with an updated design and proof of concept as soon as I am able to reach the expected outcome.

Thank you very much for your guidance.

**Comment by joeyparrish** [comment]
Hey, happy to help.  Thanks for taking some time to work on this.

With regards to the submenus, I had an image in my head that is similar to YouTube's menus:

![image](https://user-images.githubusercontent.com/6843156/111690312-44205a00-87ea-11eb-87c8-b46bd2dfb909.png)

But now that I'm thinking it through, it occurs to me that there's really no reason the menus have to be any different than they are now.  The only difference between what I had in my head and what we already have is just styling.  So perhaps there isn't much more to do for the menu items.  You could click a "resolution" button and get a menu that shows you all the resolutions.

I haven't investigated the new branch, but feel free to submit a PR with the non-submenu buttons you've already done.  Smaller PRs are easier to review, and with the non-submenu buttons, it sounds like it's all working already.

Thanks!

**Comment by nbcl** [comment]
Sub-menu buttons have arrived!

This was achieved by continuing to follow the hybrid-class design arriving to a proof of concept (currently at [@nbcl/shaka-player:feat-2676-overflow](https://github.com/nbcl/shaka-player/tree/feat-2676-overflow)) that looks as follows.

<p align=center>
<img src="https://nbcl.github.io/images/overflow.png" width=500>
</p>

My only concern with the current approach is that on the live branch, overflow menus and overflow submenus are hidden when clicking outside of them. Achieving this also includes hiding them even when clicking the control panel via a listener.

https://github.com/google/shaka-player/blob/4547c7ffc566f3b76c211809612cb41f538f320a/ui/controls.js#L776-L782

That behavior conflicts with the availability of having overflow buttons in the control panel as, every time they are clicked, they are instantly closed by the event manager.

My current approach involves removing said listener, but has the downside that overflow menus will not be closed when clicking some places of the control panel. Of course, they will still be closed when clicking into themselves, other overflow buttons or anywhere else.

Apart from that, everything works as intended!

I wanted to write this comment to update the current state of the issue and inquire if I should continue to investigate a more advanced solution regarding the removal of the listener , think of optional approaches or maintain the current one.

Thank you very much!

**Comment by joeyparrish** [comment]
@nbcl, is this work complete now?  Are there other overflow menu items left to push to the main UI bar?

**Comment by nbcl** [comment]
> As I understand, this feature is still not a part of the latest release, right?

As far as I understand the above mentioned pull requests (#3255) (#3465) are still not part of 3.2.1.

**Comment by avelad** [comment]
I close it because all the functionality has already been merged.
