### ISSUE TITLE
Demo fails to save "Custom DRM System" field if it's a well-known DRM system

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#3386]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

NOTE: Not reproducible in the demo of v3.0.11

**Are you using the demo app or your own custom app?**
Demo app

**What browser and OS are you using?**
ChromeOS 90 stable

**What are the manifest and license server URIs?**
Any

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Any

**What did you do?**

1. Add a custom asset
2. Set manifest URL & name (can be fake)
3. In the DRM tab, set license server URL (can be fake)
4. Add a well-known ID to the "custom DRM system" field, such as `org.w3.clearkey`
5. Save the asset
6. Edit the asset again

**What did you expect to happen?**
The custom DRM system field should be the same

**What actually happened?**
It's empty

**Comment by joeyparrish** [comment]
I was mistaken.  It only fails to save it if the field is set to a well-known key system ID, such as `w3.org.clearkey`.

**Comment by joeyparrish** [comment]
It would be nice to be able to use org.w3.clearkey to force the use of clearkey on a custom asset.

**Comment by theodab** [comment]
Right now, if you provide a license server URL, it will attach that URL to every known key system, plus whatever custom key system you provide. We automatically filter out any known key systems when re-loading the dialog, so we don't tell the user that `com.widevine.alpha` is a "custom DRM system" every time they edit an asset with DRM. That's why well-known key system id fields go away when you remake the asset like that.
Do you think it would make more sense for the demo to interpret a custom key system being provided as meaning "only use this key system"? Then, we could interpret an asset having exactly one license server entry as meaning "this had that key server provided as the custom key system".

**Comment by joeyparrish** [comment]
In many cases, the current system is fine.  It basically means "find whatever key system, then use that".  But the license server endpoint usually only accepts requests from one key system.  So in cases where a browser has multiple key systems, you may need the ability to specify one particular standard key system.

Although Chrome only supports Widevine, you can run into this on Chrome if you need to test ClearKey (as I did yesterday).  ClearKey will never be chosen by the player if there are other options, and I couldn't force it through the custom asset dialog.  But it is trivial to force through the config API, so it would be nice to have some way to do it through the custom asset dialog, too.

**Comment by theodab** [comment]
Perhaps we could have, like, a toggle element labeled "Only use the custom key system" or something like that?
That would let us keep the current loosey-goosey way of handling key systems, while also allowing the user to use a specific key system if it makes sense for them.
That might be a bit confusing, though, since from the name "custom key system" it's not clear that you can write in well-known key systems also.

**Comment by avelad** [comment]
Resolved with https://github.com/shaka-project/shaka-player/commit/ab86000dc75a352505875fe6dbc37fe0bdd2857a
