### ISSUE TITLE
Enable everyone to run screenshot tests locally

### ISSUE THREAD

**Issue by valotvince** [shaka-project/shaka-player#3415]
👋 
I am fighting against a potential regression in TTML displaying in v3.1.0 and I am trying to make a test sample with a screenshot test, but I am unable to find how I can start a Chrome through WebDriver using Shaka.

Is there any documentation at all about that process ?

Thank you !!

Edit: Turns out the potential regression is already explained here https://github.com/google/shaka-player/issues/3379 😄

**Comment by avelad** [comment]
Maybe it can help: https://github.com/google/shaka-player/commit/b839340220152c4ab7d9e72439af04dc7f26ef25

**Comment by avelad** [comment]
@valotvince are you working on https://github.com/google/shaka-player/issues/3379 ?

**Comment by valotvince** [comment]
@avelad Nope not yet

**Comment by joeyparrish** [comment]
> Is there any documentation at all about that process ?

Not yet.  :-(

What we do internally is run Karma with a WebDriver-based launcher that connects to a Selenium grid in our private test lab.  For security reasons, we can't make that lab network available outside Google.  And we couldn't possibly expect you to have access to the same set of devices to be able to update all of our screenshots.

What I think might be ideal is if we could make it relatively easy to run the screenshot tests locally in Chrome and/or Firefox.  That would enable you to self-test your UI/subtitle changes on those platforms, and it would be up to us to update the screenshots for everything else in our lab after accepting a PR.

How does that sound?

**Comment by valotvince** [comment]
@joeyparrish That would be nice ;)

**Comment by joeyparrish** [comment]
Renamed and labeled as an enhancement.

Rough outline of the minimum work required:
  1. Simplify installing the correct version of chromedriver.  (Perhaps with something like https://www.npmjs.com/package/chromedriver using the version-detection method it offers `npm install chromedriver --detect_chromedriver_version`)
  2. Offer a command-line argument to test.py to run tests through this chromedriver binary instead of using local browser launchers

Further work could be:
  1. Define a way to specify tests to run against a Selenium grid, and specify particular browsers from the grid (this goes beyond browser name, but also includes OS, possibly version, and maybe browser-specific options; it may be best to offer a separate grid config file instead of complicated command-line arguments)

**Comment by joeyparrish** [comment]
This was resolved by PR #3921, which did not originally tag this issue.
