### ISSUE TITLE
[cast.framework.media.ShakaPlayer] category: 4 code: 4037 with MediaTailor MPD

### ISSUE THREAD

**Issue by xoundboy** [shaka-project/shaka-player#3575]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.10 (via Chromecast cast_receiver_framework.js)

**Can you reproduce the issue with our latest release version?**
No, because DRM fails with 6012 error before this issue can occur 

**Can you reproduce the issue with the latest code from `master`?**
No, because DRM fails with 6012 error before this issue can occur 

**Are you using the demo app or your own custom app?**
custom cast receiver with CAF v3

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chromecast 2nd gen.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
1.49.250946

**What are the manifest and license server URIs?**

Sent via email to shaka-player-issues@google.com

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

I don't know - this is buried in CAF receiver framework JS file

**What did you do?**

playing a live stream generated by AWS Mediatailor

**What did you expect to happen?**
Continuous playback when switching from content to ads and then back to content at end of ad break 

**What actually happened?**

Live playback procedes correctly when regular programme content is playing. Ad breaks generated by Mediatailor as additional periods in the MPD sometimes play back fine but other times cause the [cast.framework.media.ShakaPlayer] category: 4 code: 4037 error to be thrown by the version of Shaka used in the caf receiver (v 3.0.10 at the moment). This can happen at both the beginning and the end of the ad break and sometimes not at all. The manifest sent via email was collected when the error appeared at the beginning of an ad break.

**Comment by xoundboy** [comment]
Hi again. I'm wondering whether anyone has had chance to take a look into this issue yet? It's been a few weeks since I posted it.

One other thing I noticed since I posted this issue is that the codecs used by Mediatailor for ads are not all the same across the varous bitrate representations. I suspect that this might be triggering the 4037 error. See screenshot below:

![DevTools_-_benroberts_eu_ngrok_io_p_sappa__🔇](https://user-images.githubusercontent.com/524404/133083545-d38a0790-e9c8-4a29-b061-2ab835f74a1b.jpg)

**Comment by joeyparrish** [comment]
The hex part of the codec string represents the level, profile, etc of the h264 codec.  It is normal for this to vary across Representations, since they are encoded differently, and each level and profile has certain maximum framerates, resolutions, etc.

Error 4037 is PERIOD_FLATTENING_FAILED [according to the docs](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:4037).  I don't believe these minor differences in h264 codec strings could explain it.

Please try to reproduce the issue outside of CAF, such as in our demo app.  If that can be done, we can take a look.  We are not the team responsible for CAF, and can't directly debug CAF.

I see your original report mentions:

> **Can you reproduce the issue with our latest release version?**
> No, because DRM fails with 6012 error before this issue can occur

Error 6012, [according to the docs](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6012), is NO_LICENSE_SERVER_GIVEN.  This means you have not correctly configured Shaka Player, and you need to provide a license server URL before we can play encrypted content.

To play custom content in the demo, first go to the "custom content" tab at the top:

![custom-content](https://user-images.githubusercontent.com/6843156/133125219-123a88d0-11dd-4972-a087-93d81f392ab3.png)

Next, click the "add" button at the bottom right:

![add-button](https://user-images.githubusercontent.com/6843156/133125244-9ddeb900-df51-4277-8dde-57719e33c084.png)

Then enter a manifest URL and name for the content in the dialog's "main" tab:

![main-dialog](https://user-images.githubusercontent.com/6843156/133125310-58420987-fc12-4640-acd7-122330c09acd.png)

Then click over to the dialog's "DRM" tab and enter a license server URL:

![drm-dialog](https://user-images.githubusercontent.com/6843156/133125351-5d40916e-b67c-4469-8ed0-5c4e3dc17923.png)

Then click save in the dialog, and finally, click the "play" button on the custom content card:

![custom-content-card](https://user-images.githubusercontent.com/6843156/133125515-441e5a21-fe58-454f-8bbc-6823a81d8ec5.png)

**Comment by xoundboy** [comment]
Hi @joeyparrish thanks very much for your response.

> Please try to reproduce the issue outside of CAF, such as in our demo app. If that can be done, we can take a look. We are not the team responsible for CAF, and can't directly debug CAF.

I should have mentioned in the original report that these exact same ad breaks are playing back without issue in Shaka player in Chrome Browser (all versions from 2.5.x to 3.2.0). I've posted an issue on the Chromecast issue tracker now. Hopefully they will have some insight about the what the root cause may be. FYI here's the link https://issuetracker.google.com/issues/200172524
