### ISSUE TITLE
608 Captions demo contains incorrectly-formed files

### ISSUE THREAD

**Issue by micolous** [shaka-project/shaka-player#3715]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Does not appear to be an existing issue, or in the FAQ :)

**What link can we use to reproduce this?**

These two streams are in the demo list:

https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://livesim.dashif.org/dash/vod/testpic_2s/cea608.mpd;panel=ALL_CONTENT;panelData=SUBTITLES;build=compiled

https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://livesim.dashif.org/livesim/testpic_2s/cea608.mpd;panel=ALL_CONTENT;panelData=SUBTITLES;build=compiled

**What version of Shaka Player are you using?**
v3.2.1

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0

**What did you do?**

View the streams with captions enabled.

**What did you expect to happen?**

The captions **should not be displayed,** [because they are invalid](https://github.com/Dash-Industry-Forum/dash-live-source-simulator/issues/99): these files presently contain truncated ATSC A/53 caption SEIs, which can be seen with `ffmpeg`:

```
[h264 @ 0x55c46d8136c0] SEI type 4 size 424 truncated at 423
```

The files similarly do not report caption availability in VLC.

Until 2020-07-02, these files incorrectly positioned the SEI NAL after the picture NAL, which has since been fixed.

**What actually happened?**

The captions were displayed as if they were valid.

**Comment by TobbeEdgeware** [comment]
The test content was erroneous but should now be fixed. The ffmpeg error message is pretty misleading. The captions were not actually truncated but the last byte of the SEI NAL unit was 0xff instead of 0x80 and the payload length signalling included that 0xff byte which it should not. This is discussed is https://github.com/Dash-Industry-Forum/dash-live-source-simulator/issues/99.

It is of course good that the test content is fixed to comply to the standard.

However, I don't think it should be considered an error in Shaka-player to be robust towards this kind of minor error and render all the captions as retrieved from the asset. Another player, `dash.js`, also parses and renders the CEA-608 captions without complaining, but in that case that is due to that the [cea608.js](https://github.com/Dash-Industry-Forum/cea608.js) library was developed in conjunction with the test material so it is not strict on the last byte's value. That hasn't caused any reported problems during the six years the code has been used.

**Comment by joeyparrish** [comment]
Our implementation was independent and largely based on the spec.  So I'm not surprised that it was strict in this way.

I'm not opposed to making changes to make it more forgiving.  But the engineer who contributed this feature is no longer with us, so we would very much appreciate a pull request from anyone who is interested in this issue.  Thanks!

**Comment by TobbeEdgeware** [comment]
My understanding is that this issue is about the NAL unit parsing code not being strict enough regarding the `rbsp_trailing_bits` and length field, so the request is to make the code stricter and not more forgiving.

**Comment by joeyparrish** [comment]
In either case, a PR would be welcome.

**Comment by avelad** [comment]
Can you check if the error still occurs in the main branch? Thank you!
