### ISSUE TITLE
Changing audio track in Edge browser

### ISSUE THREAD

**Issue by mivannikoff** [shaka-project/shaka-player#3750]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.2.1-uncompiled

**What browser and OS are you using?**
Windows 10 and Edge 95 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44)

**What did you do?**
1. Open a demo player.
2. Paste this source - https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
3. Start playing this stream
4. Try to change the audio track (sometimes it works after several attempts)

**What did you expect to happen?**
The audio track changed without errors

**What actually happened?**
In the Edge browser, when trying to change the audio track on the HLS stream, the player gives following error - "Shaka Error MEDIA.VIDEO_ERROR (3 ,, CHUNK_DEMUXER_ERROR_APPEND_FAILED: Buffers parsed out of DTS sequence)"

What do you think about it?
Thank you!

**Comment by theodab** [comment]
Reproduced. Thanks for the report.

**Comment by mivannikoff** [comment]
@theodab I am glad to help! Could you tell me if there is a workaround? It's important for me.

**Comment by theodab** [comment]
After some testing, it looks like this consistently happens if you change the audio language after 6 seconds in. If you change before that point, it works fine.

So if you need a workaround in the short-term, well... it's not ideal, but if your content is VOD you could pause the video, seek back to time=0, change the language, then seek back to your original position. Wait a few moments between seeking and changing language for the buffer to clear. Something like this:
```js
const wait = async (time) => {
  await (new Promise((resolve, reject) => {
    setTimeout(resolve, time * 1000);
  }));
};
const oldTime = video.currentTime;
video.pause();
video.currentTime = 0;
wait(0.25);
// TODO: set language
wait(0.25);
video.currentTime = oldTime;
video.play();
```

Anyway, I'll keep looking into this. If I can prove this is a browser bug I'll file it with the Edge people.

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!

**Comment by mivannikoff** [comment]
@avelad v4.3.3 works without errors. Thank you!
