### ISSUE TITLE
Custom control icons

### ISSUE THREAD

**Issue by dolphincodes** [shaka-project/shaka-player#3822]
How can I replace the existing player control icons with new icons?. I have a few custom control icons for the player.

**Comment by nbcl** [comment]
Hello @dolphincodes!

Currently, the icons library used is [Material Icons Round](https://fonts.google.com/icons?selected=Material+Icons) which is referenced by the `material-icons-round` CSS class to `<i>` or `<button>` tags, with the corresponding icon name as text content.

If you are looking to replace existing player control icons with new Material Icons, then the optimal approach would be to find the desired icon in this [list](https://fonts.google.com/icons?selected=Material+Icons) and changing the corresponding string on [enums.js](https://github.com/google/shaka-player/blob/master/ui/enums.js):

https://github.com/google/shaka-player/blob/73b430248ba76038b466da902b776ecc920b2a35/ui/enums.js#L16-L19

On the other hand, if you are looking to replace them with completely custom CSS, then apparently, manually replacing every single icon is required. For example, when changing the fast forward button:

https://github.com/google/shaka-player/blob/73b430248ba76038b466da902b776ecc920b2a35/ui/fast_forward_button.js#L31-L34

`this.button_` should be modified to suit your new CSS class.

Let me know if this helps!

**Comment by dolphincodes** [comment]
Hey @nbcl,
Thanks for the answer. I have one more question related to your answer.
I want to add icons from outside the material library. I prefer to install the Shaka player from the npm package manager. In that case, is there any way I can extend the existing button class of each button and make changes or do I have to create custom buttons for the icon change?

**Comment by joeyparrish** [comment]
@dolphincodes, you can customize the appearance of existing controls in CSS, or build your own custom controls.

If you want to override the appearance of a button to use something like an external SVG instead of the Material Icons font, I believe you should be able to do this with CSS alone.  For example, since the icons are a "font", you could choose to hide the "text" by setting `color: transparent`, then size them and use `background:` to import an SVG icon.

For more inspiration on what can be done through configuration and CSS, check out this third-party gallery: https://github.com/lucksy/shaka-player-themes

You can also create custom buttons that extend the built-in buttons (literally, through JS inheritance).  Then you can register those custom versions as replacements for the default ones.  For example:

```js
SillyPlayButton = class extends shaka.ui.SmallPlayButton {
  updateIcon() {
    this.button.textContent = 'FOO';
  }
};

SillyPlayButton.Factory = class {
  create(rootElement, controls) {
    return new SillyPlayButton(rootElement, controls);
  }
};

shaka.ui.Controls.registerElement(
    'play_pause', new SillyPlayButton.Factory());

// If there's already a UI instance on the page, force it to rebuild
// the buttons since we replaced one of the built-in ones.
video.ui.configure({});
```

_Note that for this exact code to work in compiled mode, we would need to add the `@export` annotation to the `updateIcon()` method in `SmallPlayButton` and `PlayButton`.  Send a PR if this change would be useful!_

Does this help?

**Comment by dolphincodes** [comment]
Thanks @joeyparrish. I just inherited the whole button class and changed the icon and tooltip message.
Also got access to the button element. Thank you so much for your help.
```
export class PlayButton extends shaka.ui.PlayButton {

  button: HTMLButtonElement;

  constructor(parent: HTMLElement, controls: shaka.ui.Controls) {
    super(parent, controls);
    this.button = parent.lastChild as HTMLButtonElement;
  }
}
```
