### ISSUE TITLE
Should I use shaka-player if I only want to play audio-files on my website?

### ISSUE THREAD

**Issue by stefan-falk** [shaka-project/shaka-player#3846]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
None yet

**Please ask your question**
Hello!

I am not sure if I ended up in the wrong place because all I am actually looking for is a way to play an audio file on my website with the additional requirements that 1) the audio should be downloaded chunk-wise such that the user does not have to wait until the file is downloaded completely and 2) seeking should not break because of that.

Some time ago I tried to implement this using the Media Source API with some success but it's really nothing one writes in just one afternoon. Learning that I should convert all files to fragmented MP4 files and that I have to fetch particular byte-ranges within that file on the backend via HTTP-requests in order to append it to the SourceBuffer really wasn't as much fun as one would expect.

I was now wondering if the `shaka-player` could make my life easier here. It looks as if its main purpose is to show ads during content which is not really what I was looking for though. 

Anyway, can somebody tell me if I should use `shaka-player` for this or is there anything else out there you could recommend to me? 

I'm sorry if my question is a bit out-of-place but 99% of all tutorials or code examples I find simply download the entire audio-file in order to play it.

**Comment by joeyparrish** [comment]
Shaka's purpose is to play adaptive content (DASH & HLS), which is downloaded chunk-wise.  It also supports DRM content and ads, but neither is required.

If you play an audio file (mp4 or mp3 or ogg) with `audioElement.src=...`, then the browser will be in charge of how much to buffer ahead, what size chunks to request, etc.  It will be dependent on the browser implementation, and you won't have control or visibility into it.

If you convert that file into DASH or HLS, you'll have control over how much is buffered (through Shaka's configuration), and you'll be able to offer multiple bitrates to scale the content quality to the user's available bandwidth (this is controlled when the DASH or HLS files are created).  You can also choose to create DASH/HLS in a single bitrate if you wish.

We offer Shaka Streamer to create DASH & HLS content: https://github.com/google/shaka-streamer  You can 
configure that to decide what bitrates to create.  For audio-only, I suggest something simple like AAC stereo at 128kbit and 64kbit.  Or if it's just speech and not music, something smaller could suffice, like AAC mono at 64kbit and 32kbit.

I would be happy to guide you further on both Streamer and Player if you need it.

Does this help?

**Comment by stefan-falk** [comment]
@joeyparrish Hi! Thanks for the explanation!

I'm not sure if I fully got my head around this though.

In my case I don't require live-streams or adaptive content. At least not for now. What I currently do is using the Media Source API in order to fetch the data chunk-wise from my server. For every new chunk I have another HTTP-request which holds the byte-range to fetch from a file which is stored e.g. in a Google Cloud Storage bucket. For these audio-files I am using AAC (stereo) and converted them to a fragmented MP4 format using FFmpeg.

So, I guess, what I am trying to understand is how the `shaka-player` actually deals with the data transfer and will I be able to restrict access only to logged-in users?

**Comment by joeyparrish** [comment]
Shaka Player would deal with the data transfer, but it needs a manifest/playlist format like DASH or HLS to tell it what the URLs & byte ranges of the segments are.  If you have each segment in a separate file, the simplest format is probably an HLS media playlist.

If you want to control how much data Shaka is requesting relative to what your users are hearing, you can configure a specific `bufferingGoal`: https://shaka-player-demo.appspot.com/docs/api/tutorial-network-and-buffering-config.html

As for access control, there are two main options.  One is to control access at the HTTP level through an auth token of some kind.  If you are storing your content in GCS and serving from there, you may want to look into the ACLs that you can place on your cloud storage buckets.  You could also choose to run a service that authenticates your users before serving the content to them, rather than having Google Cloud Storage do it for you.

The other option for access control is DRM.  Your content is encrypted, and can only be decrypted with a license.  You run a license server (or license authentication proxy) that determines whether or not to issue a license.  The actual decryption keys are kept hidden, even from authorized users.

Does this help?
