### ISSUE TITLE
How key rotation works in widevine?

### ISSUE THREAD

**Issue by adgllorente** [shaka-project/shaka-player#3958]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Any version applies.

**Please ask your question**

Hi,

We want to rotate widevine keys on the fly in our streams.

I have seen the issue #3193 where another user says that key rotation is supported on shaka-player but we haven't found any official documentation about it.

- Is there a standard way supported in shaka-player?
- Could you please give me some information or documentation about it?
- Does shaka-player support any other mechanism?

Thanks.

**Comment by joeyparrish** [comment]
There has never been any Shaka documentation on key rotation because there isn't any specific player configuration for it.  It's all managed by the Widevine license policies and how the content is encrypted.

In key rotation, different parts of the content will use different key IDs.  License sessions will only contain a few keys, and will have short expiration times.  As the content plays, the CDM will generate additional license requests and sessions for new key IDs.  The player will close the expired sessions.

Does this help?
