### ISSUE TITLE
Production ads download problem

### ISSUE THREAD

**Issue by mmatsuk-sc** [shaka-project/shaka-player#4004]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.2

**Please ask your question**
Have issue in production build. After player initialization i have preroll ads, which should be shown. But i can't see it, video start playing, but no ads here. I got such error in console.
![image](https://user-images.githubusercontent.com/86662841/156180181-23e8b7af-06ab-4192-80d7-5c5b69823191.png)

In my opinion it wants to get isLinear() from **this._ad** object, but somehow it is null. May be ads it's not downloaded yet, or it's not downloaded at all, idk.

The main problem of this issue is that when i run it locally, everything is working perfect - i see preroll ads and video after it. Can't reproduce it locally. I'm using **"shaka-player/dist/shaka-player.compiled.js"**. May be you can help me with that? Thanks!

**Comment by avelad** [comment]
I tried to reproduce the issue with https://shaka-player-demo.appspot.com/demo/#audiolang=es-ES;textlang=es-ES;uilang=es-ES;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=;panel=HOME;build=compiled and I don't see the error, can you share more details? Thanks!

**Comment by jukart** [comment]
Hi, I could reproduce this problem (with version 3.3.7).
It happens if there is an error before `onAdStart_` is called.
In my case it can be triggered with an empty vast response like this: `<VAST version="3.0" />`
With the debug version the player reports:
- `There was an ad error from the IMA SDK: AdError 1009: The VAST response document is empty.`
- `Resuming playback.`

The problem starts here: https://github.com/shaka-project/shaka-player/blob/d6bdf9a4c2ac1d8085bcc925492eb0526fe82c33/lib/ads/client_side_ad_manager.js#L137

`onAdComplete_` is called in `onAdError_`.

In `onAdComplete_` we have: https://github.com/shaka-project/shaka-player/blob/d6bdf9a4c2ac1d8085bcc925492eb0526fe82c33/lib/ads/client_side_ad_manager.js#L430
which is not checking if `this.ad_` is defined.

**Comment by joeyparrish** [comment]
> Hi, I could reproduce this problem (with version 3.3.7 and 4.1.4).

Could you please double-check your version numbers?  v4.1.4 doesn't exist yet.

**Comment by joeyparrish** [comment]
Wonderful!  Thank you!  I'll assign the issue back to you then, and we look forward to your PR.
