### ISSUE TITLE
index-dot-shaka-player-demo.appspot.com broken

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#4074]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What did you do?**
Open https://index-dot-shaka-player-demo.appspot.com/

**What did you expect to happen?**
v3 versions are shown 

**What actually happened?**
v3 versions are missing

**Comment by joeyparrish** [comment]
The fix in PR #4116 appears to have an issue.  I'm now seeing:

> **Internal Server Error**
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I'll reopen the issue for now.

**Comment by joeyparrish** [comment]
The call to `google.appengine.api.modules.modules.get_versions()` is ultimately failing with `AssertionError: No api proxy found for service "modules"`.  This worked fine with the now-deprecated Python 2 engine, and it's not clear that there's a functioning equivalent in the new runtime.  (Or maybe there is, but it requires the setup of additional services or something.)

Since the Google Cloud docs are unhelpful on this, I suggest we just stop depending on this app-engine-specific code at all.  Back when the index service was launched, it was its own thing, and looking up appspot subdomains from inside appspot made sense.

Now that we have GitHub Actions, there's no reason for any dynamic code in this thing at all.  It could be purely static content, regenerated and redeployed each time a release is tagged on GitHub.

I think that's the way forward.  It's also independent of Google Cloud.  Even if we have no plans to host it elsewhere, the index will be more portable this way.

**Comment by joeyparrish** [comment]
Still broken, sadly.  The automated deployment failed.  But I have another fix, and I've tested it through a manual deployment this time.

**Comment by joeyparrish** [comment]
Broken again!  This time it seems to be caused by the workflow not having checked out the full repo history.  Since the static content is based on git tags, we need those to be present.  This didn't come up when I ran it locally, because of course, I had the full history in my local clone.

**Comment by joeyparrish** [comment]
While I'm waiting on review for PR #4126, I've done another manual push to fix the currently-deployed index.  After the PR lands, the process should be fully automatic in the future.

**Comment by joeyparrish** [comment]
Actions can be so obnoxious.  There should be a linter for Actions YAML files, since a typo will ruin everything.
