### ISSUE TITLE
hosting content locally fail

### ISSUE THREAD

**Issue by NonameASecret** [shaka-project/shaka-player#4102]
Sloved

**Comment by NonameASecret** [comment]
@vaage Are You Know About this?


[Refference](https://github.com/shaka-project/shaka-player/issues/1645)

**Comment by joeyparrish** [comment]
We're glad you were able to solve your issue, but editing the post to say "solved" may leave out useful information for others.  Instead, I would suggest reverting the OP to show what the issue was, and leave an additional comment with some information about how you solved it.  Then, anyone who has a similar issue in the future can benefit from what you learned.  Thanks!
