### ISSUE TITLE
Origin http://shaka.player.test.com is not allowed by Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by jason-liujunhui** [shaka-project/shaka-player#4106]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.2

**Please ask your question**
I have a Fairplay DRM protected HLS content being hosted on a remote web server and with remote DRM server. I am trying to integrate a simple Shaka Player to play this content. A local http server shaka.player.test.com is running to host this simple Shaka player and the Shaka Demo player from Github. However, on Safari browser, this content can be successfully played with Shaka Demo player, but not with my simple Shaka Player. A CORS error is raised for the CKC request. Why is that? What else should I do in my integration?
![Screenshot2022_04_08_150545](https://user-images.githubusercontent.com/1510899/162441517-da063c46-83d8-46eb-b9df-97da2706a0e7.jpg)
![Screenshot2022_04_08_150713](https://user-images.githubusercontent.com/1510899/162441756-9fe37772-bb83-4dd5-a9fc-197bc2dbbeed.jpg)

Piece of code:

```
  player.configure({
    manifest: {
        hls: {
            useFullSegmentsForStartTime: true,
        },
    },
    drm: {
      servers: {
        'com.apple.fps.1_0': licenseUri,
      },
      advanced: {
        'com.apple.fps.1_0': {
           serverCertificate: new Uint8Array(hlsCertificate),
        }
      },
      logLicenseExchange:true,
      initDataTransform: initDataTransform
    },
  });


    if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
      // This is the specific header name and value the server wants:
      //request.headers['CWIP-Auth-Header'] = 'VGhpc0lzQVRlc3QK';
      console.log("====RequestFilter RequestType.LICENSE====");

      const originalPayload = new Uint8Array(request.body);
      const base64Payload = shaka.util.Uint8ArrayUtils.toBase64(originalPayload);
      request.headers['Content-Type'] = 'application/x-www-form-urlencoded';
      request.body = 'spc=' + base64Payload;
    }

```

**Comment by joeyparrish** [comment]
CORS restrictions are controlled by the server you're contacting, and enforced by your local browser.  If that server doesn't want to allow access from your domain, then there's nothing you can do about it in production.

For development purposes, most browsers have a way to disable CORS restrictions.  This can help you work around a restriction at development time, but can't be a real solution for your end-users.

Ultimately, whatever is serving responses for the CKC request will have to explicitly allow your domain access.  If your production domain is already allowed, you can disable CORS in your browser for your development domain (since shaka.player.test.com doesn't look like a real domain).

General information on CORS can be found here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Also, you're not alone in having CORS issues.  You can browse flagged CORS issues going back many years, in case they are helpful to you in understanding your issue: https://github.com/shaka-project/shaka-player/issues?q=is%3Aissue+label%3A%22flag%3A+CORS+issue%22+

Does this help?

**Comment by jason-liujunhui** [comment]
Thank you @joeyparrish for your detailed reply. But I think the problem I have isn't a CORS ISSUE as I could successfully play the same content on the same webserver by hosting the Shaka demo player. The only difference is Shaka demo player can, but my player can not. I think it is an integration issue on my side, but I can't think about a clue. What could be the implementation differences between Shaka Demo player and my player? The difference could result in CORS error?
The error code is 1002 inside the error 6007.
Error code – 6007 – "object"
Object

category: 6

code: 6007

data: [Object] (1)

handled: false

message: "Shaka Error DRM.LICENSE_REQUEST_FAILED (shaka.util.Error {↵  \"severity\": 2,↵  \"category\": 1,↵  \"code\": 1002,↵  \"data\": [↵  …"

severity: 2

stack: "@http://shaka.player.test.com/shaka-fairplay/node_modules/shaka-player/dist/shaka-player.compiled.debug.js:174:84…"

Object Prototype

**Comment by joeyparrish** [comment]
> message: "Shaka Error DRM.LICENSE_REQUEST_FAILED (shaka.util.Error {↵ "severity": 2,↵ "category": 1,↵ "code": 1002,↵ "data": [↵ …"

This is a license request failure, with another error nested within that showing what caused the license request failure.  The license request failure was caused by a network failure, and that network failure looks like a CORS error (1002 is usually CORS, by JS can't differentiate for sure).  If you check the console logs in an interactive console in Chrome, for example, CORS errors would be clearly logged (directly by the browser) as CORS errors.  You could also look at the network panel to see what request failed, and why.  It's possible that the browser stopped the request for some other reason than CORS.

The issue does not appear to be a CORS issue with the content, but rather the license server.  (I assume you can't host your content and player in the same place as your license server.)

One thing that may be different between the demo and your dev server is that our demo is always served over HTTP**S**.  CORS works on origins, which are made of protocol + domain.  [For example](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#examples), `http://shaka.player.test.com/` is an origin.  So if you have specifically allowed access to your license server from that specific domain, please make sure you allow access to the plain `http` origin.

Does this help?

**Comment by jason-liujunhui** [comment]
Hi @joeyparrish 
Thank you for your tips. I will check what network failure "This is a license request failure, with another error nested within that showing what caused the license request failure. The license request failure was caused by a network failure, and that network failure looks like a CORS error (1002 is usually CORS, by JS can't differentiate for sure)"
And thanks for the second part about the https vs http hosting the player. Though in my case, I Shaka Demo player is also hosted on the same web server over http side by side with my player. But it is worth to keep it in mind when configure license server.
Thanks a lot again. You can close this ticket. I have always believed the issue is on my side but just be exhausted in the corner to find out what error/mistake could be on my side. I will keep checking.

have a lovely day!
