### ISSUE TITLE
Is EME polyfill still necessary for MS?

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#4113]
Is EME polyfill still necessary for MS? See: https://github.com/shaka-project/shaka-player/blob/main/lib/polyfill/patchedmediakeys_ms.js

According https://caniuse.com/eme it's only necessary for IE, but in the code of the polyfill I see comments about Edge 12, but the last Edge was 18 (the same used in Xbox).

@joeyparrish , is it possible to test on the xbox in the lab if it's still needed and if not delete it? (it's a big file about 700 lines, so we can save some bytes if we remove it)

**Comment by joeyparrish** [comment]
Yes, can do.

**Comment by joeyparrish** [comment]
Some of our tests get skipped if the necessary feature isn't available.  This happens with DRM, for example, where tests are skipped if none of the test's supported key systems are available.

Without changes, `--browsers XboxOne --drm --filter DrmEngine` ran 90 tests, all of which passed.

With the polyfill removed, I got the same results.  If the polyfill had been providing PlayReady support, some of those tests would have been skipped.

So it looks safe to remove.  I'll put up a PR now since I've already made the change locally.
