### ISSUE TITLE
Recommended iOS alternative for `registerRequestFilter`?

### ISSUE THREAD

**Issue by agconti** [shaka-project/shaka-player#4129]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
`^3.3.0`

**Please ask your question**

_Is there a recommended way to argument request uris on iOS?_ 

As you've mentioned [here](https://github.com/shaka-project/shaka-player/issues/3912#issuecomment-1024725124) and in a few other issues, we cannot update request uris with `registerRequestFilter` on iOS because there is no MSE support. If we still need to update the URLs on this platform what's the best way to do so?

For context, my use case is appending a query parameter to request URLs to allow our CDN to choose where to fetch content from. On desktop, we're doing this with  `registerRequestFilter`, but this can't be used on iOS.

```javascript
player.getNetworkingEngine().registerRequestFilter((type, request) => {

      // updates URLs from 'https://my-origin.com/out.mpd' => 'https://my-origin.com/out.mpd?id=123'
      request.uris = request.uris.map(uri => {
        const url = new URL(uri)
        url.searchParams.set('id', id)
        return url.href
      })
    });
```

From what I gather, the next best thing that iOS would support is to set a cookie instead. While that can work, it won't work if your server's domain is different than the domain the content is being played back from. Additionally, there are some strong caveats to using cookies in different parts of the world and whether users allow them in the first place.

Do you have a recommendation on the best approach to use with Shaka player?

**Comment by joeyparrish** [comment]
If the platform is responsible for fetching content, as it is on iOS, your control is limited, but there are some ways to tweak things.

If you need to change the URL of the master playlist before playback starts, that's easy.  Just modify the master playlist URL before calling player.load().

If you need to change the URL of the media playlists instead, you could:

1. Fetch the master playlist in JavaScript
2. Modify the content of it so that the media playlist URLs have your query parameter
3. Turn all of that content into a blob or data URI
4. Call player.load() on the blob/data URI (and pass the HLS MIME type so that we know what it is)

So long as Safari would accept a blob or data URI (I have no idea if it would), this could work, and would work for any type of content (VOD, event, live).

If you need to change the URLs of the segments, you could go deeper:

1. Fetch the master playlist in JavaScript
2. Parse the master playlist
3. Fetch all media playlists in JavaScript
4. Parse those
5. Modify the content URLs in the media playlists
6. Turn those media playlists into blob URLs
7. Replace the media playlist URLs in the master playlist
8. Turn the master playlist into a blob/data URI
9. Call player.load() with that blob/data URI

This last idea wouldn't work on a live or event stream, though, since the media playlists would become static.

Does this help?

**Comment by agconti** [comment]
This helps a lot, thanks for your thoughts @joeyparrish!
