### ISSUE TITLE
Switching audio languages clears buffer and stalls playback for a second.

### ISSUE THREAD

**Issue by rybi** [shaka-project/shaka-player#4172]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** yes

**What version of Shaka Player are you using?**
3.3.2

**Please ask your question**

When I switch between audio languages, the player seems to remove all buffer and tries to immediately switch to the selected streams. 
Example can be seen on the official web page: https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=HOME;build=compiled

Is there a way to make the switch more fluid, e.g. after the new stream has buffered for a second?

**Comment by rybi** [comment]
As an example of different UX, the dash.js player switches streams on language change seamlessly after about 2 seconds in this example: https://reference.dashif.org/dash.js/latest/samples/multi-audio/multi-audio.html
which is also not ideal, as 2 seconds are quite long. 
Is there a way to preload other audio tracks in some way or run them in parallel perhaps to make switching audio instantaneous?

**Comment by joeyparrish** [comment]
Unfortunately, you really can't have it both ways.  Either we buffer the new thing first and delay switching (as dashjs seems to), or we clear the buffer and switch immediately.  Currently, we switch immediately.

The thinking is that if I need to change audio languages, it's because I can't understand the current one.  That should be an immediate change.

We have audio language preferences in the configuration, so that we can select the best language upfront.  If you know your user's preferred languages, you can set that.  If you don't have user settings for language in your application, you can use `navigator.language` to fill the player configuration.

Buffering other languages all the time during playback, just in case the user wants to switch to one later, would be wasteful of bandwidth.  I wouldn't be interested to merge something like that.

Does this answer your question?

**Comment by rybi** [comment]
Thank you for the thorough response! 

I understand the reasoning and yes, from the UX point of view, if a user selects something critical and the change needs 2+ seconds to propagate, it would just feel unresponsive.

My use case is a bit special, I'm looking to create language learning exercises based on voluntary (and fast) switching between languages. Basically, once the user is tired of listening to a film scene in a foreign language, they can move the mouse to a different field and listen in a language they understand better. That way, people would be able to pick up some context when they need it, and would be less frustrated when overwhelmed for a moment. 

So, now I'm either looking up into solutions that would sync up different media files - like http://webtiming.github.io/timingsrc/doc/exp_mediasync.html 
or into getting Shaka Player to buffer the other audio streams all the time. I like Shaka Player for how well it handles many things, but I just started looking into the code base yesterday. If you could point me in the direction on which code parts I should focus in order to enable buffering all audio streams, that would be greatly appreciated!

**Comment by joeyparrish** [comment]
You can't buffer all audio streams at once.  That's not how the underlying MediaSource API works as far as I know.

You could modify Shaka Player to allow you to treat language changes specially.  Instead of clearing the buffer, you could clear the buffer some small distance ahead of the playhead.

The issue with that is seeking.  If the user seeks back, they are getting the old language again.  If you really want to buffer everything all the time, and just dynamically change which language is _rendered_... that's not a thing we've ever considered, and I'm not sure how best you would achieve it.

From a pure audio point of view, ignoring the way Shaka and DASH/HLS work, you could imagine having multiple synchronized audio elements, and separately toggle the `muted` status of them based on some custom UI.  Then everything buffers in parallel, independently, and you don't have to think about what language you buffered in any given part of the presentation.

Would this work?  I think I could guide you on synchronizing multiple media elements.  I've done it recently in another project.

You could still use Shaka Player for adaptive video resolution/bitrate if you want, and handle audio separately with direct mp4 playback.

Or if you want to do DRM or ABR for audio, you could still use multiple instances of Shaka Player for the video and the various languages, each with their own audio element synced to the video element.

Or if you don't care about ABR or DRM for any of it, you wouldn't really need Shaka to begin with.  Just plain `<video>` and `<audio>` elements and some JS to sync them.

Let me know if this helps, or if you'd like to see a code snippet to sync multiple media elements.

**Comment by joeyparrish** [comment]
Okay, here's a sketch based on a side-project I have yet to release.  Google already released copyright of that side-project to me, and you (all) have my permission to use this as you see fit:

```js
mainMediaElement.addEventListener('timeupdate', () => {
  for (const secondaryMediaElement of secondaryMediaElements) {
    secondaryMediaElement.playbackRate = computePlaybackRate(
        mainMediaElement, secondaryMediaElement);
  }
});

function computePlaybackRate(mainMediaElement, secondaryMediaElement) {
  const seeking = this.mediaElement.seeking || extraElement.seeking;
  const ended = this.mediaElement.ended || extraElement.ended;
  if (seeking || ended) {
    return 0;
  }

  const diff = mainMediaElement.currentTime - secondaryMediaElement.currentTime;
  if (diff > 1) {
    // Seek to catch up.
    secondaryMediaElement.currentTime = mainMediaElement.currentTime;
    return 0;
  } else if (diff > 0.2) {
    return 1.02;
  } else if (diff > 0.1) {
    return 1.01;
  } else if (diff < -1) {
    // Seek to catch up.
    secondaryMediaElement.currentTime = mainMediaElement.currentTime;
    return 0;
  } else if (diff < -0.2) {
    return 0.98;
  } else if (diff < -0.1) {
    return 0.99;
  }
  return 1;
}
```

You will also want to listen to some other events on `mainMediaElement` and use them to synchronize state to the secondary elements:
 - play
 - pause
 - waiting (treat like pause)
 - canplay (play secondary if main not paused)
 - seeking (sync time and paused state)
 - ratechange (if the main element's rate can be changed, multiply with the computed secondary rate)
 - volumechange (if the main element has audio)

I hope this helps!  It has been working well for me so far in my project.

**Comment by rybi** [comment]
Thank you Joey for the code and the permission to use it. 
That's a great answer to my question!
