### ISSUE TITLE
Custom ABR Manager & mean bitrate ahead

### ISSUE THREAD

**Issue by valotvince** [shaka-project/shaka-player#4197]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**Please ask your question**
While using VBR streams with big size differences between segments, I'd like to calculate the "mean" bitrate ahead (for the next x seconds of content, or x segments), rather than using the avg bitrate given by the manifest (DASH & HLS). I'd also like to quantify each segments for its size/quality compared to a mid-level quality track.

The goal is to ensure we have enough bandwidth & buffer level to download the next few segments ahead and prevent interruptions.

So far I've developed a loop that runs each time a segment is downloaded, which checks if the segmentIndex for each variant video is created, and if not run `createSegmentIndex` method. From there, I am able to check for each video track what is the mean bitrate ahead. Another solution would be to build a list of each video tracks at startup, with segment information (bitrate, size quantile, ...) and re-use it to take abr decisions, but It would be some duplication from what Shaka already knows.

So my questions are, from your point of view:
- What are the implications of creating the segmentIndex of each video track ? (on memory / cpu, I guess this was done to prevent memory over-usage ?)
- I seem to have seen that segmentIndex is released whenever it isn't used for the stream, is there any means to prevent that behaviour ? (again, with the same drawbacks as above)
- Is there any other (better) means to achieve what I am trying to do ? (even with contributions from my end)

Thank you !

**Comment by joeyparrish** [comment]
> While using VBR streams with big size differences between segments, I'd like to calculate the "mean" bitrate ahead (for the next x seconds of content, or x segments), rather than using the avg bitrate given by the manifest (DASH & HLS). I'd also like to quantify each segments for its size/quality compared to a mid-level quality track.

How do you get size information per segment?  Do the segments all have byte ranges in the manifest?  I think this would be nearly impossible to do efficiently without byte ranges.  If each segment has its own URL, I think you wouldn't have the necessary information.

> So my questions are, from your point of view:
> 
> * What are the implications of creating the segmentIndex of each video track ? (on memory / cpu, I guess this was done to prevent memory over-usage ?)

Yeah, we defer segment index creation to keep memory usage down.  There are other implications depending on whether its DASH or HLS, and what type of DASH (SegmentBase, SegmentTemplate+duration, SegmentTemplate+SegmentTimeline, SegmentList).

> * I seem to have seen that segmentIndex is released whenever it isn't used for the stream, is there any means to prevent that behaviour ? (again, with the same drawbacks as above)

There isn't currently any means to prevent a SegmentIndex from being released.

> * Is there any other (better) means to achieve what I am trying to do ? (even with contributions from my end)

Can the information you need be computed in advance and stored alongside or inside the asset?

Shaka Player already supports the `minBufferTime` attribute in DASH, which is supposed to be related to the variance in bitrate.  If you want to ensure we have buffered ahead enough to handle bitrate peaks, `minBufferTime` would do that.

This seems to break down into two problems:
 - get per-segment bitrate info
 - make ABR decisions with it

You should really explore the AbrManager plugin interface for the second part.  It's meant for the application to be able to override the decision-making logic, and it can be based on whatever you want.  (You could even imagine an AbrManager that uses buffer fullness instead of bandwidth estimation, or separate probe requests instead of segment download times.)

**Comment by valotvince** [comment]
> How do you get size information per segment? Do the segments all have byte ranges in the manifest? I think this would be nearly impossible to do efficiently without byte ranges. If each segment has its own URL, I think you wouldn't have the necessary information.

I test if the manifest has byte range segment information, and if not I fallback to the simple_abr_manager of Shaka. Using the public methods from SegmentReference I am able to get back the bitrate of each segment.

> Yeah, we defer segment index creation to keep memory usage down.
Ok so I could run createSegmentIndex, pre-compute the track segments information, and remove the index right after. That would make a memory spike, but won't have a huge memory footprint over the long run.

> Can the information you need be computed in advance and stored alongside or inside the asset?

Well that would be an answer but we don't want to make some extra request on another service to get that info. I'll check if this is something we could send through the manifests (existing spec or custom)

> You should really explore the AbrManager plugin interface for the second part

Yep I've already been playing with it 😄

Thanks for the answers.
