### ISSUE TITLE
Non DRM video fails to play with error 4032 when DRM config is set

### ISSUE THREAD

**Issue by wjywbs** [shaka-project/shaka-player#4207]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.0.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
demo

**What browser and OS are you using?**
Chrome, without hardware widevine support (HW_SECURE_ALL)

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=CUSTOM%20CONTENT;build=compiled

Add a custom content. Manifest url:
https://cf-sf-video.wmspanel.com/local/raw/BigBuckBunny_320x180.mp4/playlist.m3u8

Extra config:

```
{
  "drm": {
    "servers": {
      "com.widevine.alpha": "/na"
    },
    "advanced": {
      "com.widevine.alpha": {
        "videoRobustness": "HW_SECURE_ALL"
      }
    }
  }
}
```

**What did you do?**
With the widevine HW_SECURE_ALL config that the host does not support, the non DRM video fails to play.

**What did you expect to happen?**
Play the non DRM video.

**What actually happened?**
Failed to play. Error 4032.

**Comment by joeyparrish** [comment]
This is working as expected.  Here is why:

For DRM live streams with unencrypted ad periods, we can't always tell from the content that there will be any encrypted content.  If we join a stream in the middle of an ad break, we may only see unencrypted segments at that moment.  But if we don't set up DRM, and DRM content appears later, it will be too late.  So any time DRM is configured, we set it up, because we assume you (the app developer) know whether or not your content is encrypted.

If your content is unencrypted, you should not configure a license server.  The license server is what we look at to expect encrypted content, rather than the robustness level.

Does this help explain what is happening?

**Comment by wjywbs** [comment]
Thanks, I assume the web app needs to add the check of DRM content, and conditionally set DRM configs to the player.

> The license server is what we look at to expect encrypted content, rather than the robustness level.

By the way, setting videoRobustness to SW_SECURE_DECODE will play the unencrypted video.

**Comment by joeyparrish** [comment]
> Thanks, I assume the web app needs to add the check of DRM content, and conditionally set DRM configs to the player.

Yes, that's one solution.

> By the way, setting videoRobustness to SW_SECURE_DECODE will play the unencrypted video.

That's because it's a robustness level that the platform actually supports.  You can do that, too, if you like.  There's nothing wrong with requesting DRM playback of clear content.  It's the unsupported robustness level that's causing the failure, and that's decided by the platform, not the JavaScript app.
