### ISSUE TITLE
Time to playing, initial number of segments and DRM license calls

### ISSUE THREAD

**Issue by SivanA-Kaltura** [shaka-project/shaka-player#4262]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.0

**Please ask your question**
We are using Shaka player to play a live DASH stream with a Widevine DRM. minBufferTime in the dash manifest is set to 2 seconds, and maxSegmentDuration is 3 seconds.

![image](https://user-images.githubusercontent.com/88330203/171220619-08fb75e3-eef4-47b0-b067-389726ff3852.png)

It seems that the playback always waits for at least 3 to 5 segments to be downloaded before firing the "playing" event. 
Am I correct in assuming that what prevents playback start at an earlier point in time is the license requests not being resolved yet ? 
If so, is it possible to somehow configure Shaka to invoke the license requests sooner ?

**Comment by avelad** [comment]
Can you share your Shaka config and tell us is your mpd uses a minBufferTime? Thanks!

**Comment by SivanA-Kaltura** [comment]
This is the config:
{
    "streaming": {
        "ignoreTextStreamFailures": true,
        "bufferingGoal": 60,
        "alwaysStreamText": true,
        "lowLatencyMode": true,
        "inaccurateManifestTolerance": 0,
        "retryParameters": {
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000,
            "maxAttempts": 10,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5
        }
    },
    "abr": {
        "enabled": false,
        "restrictions": {},
        "defaultBandwidthEstimate": 500000,
        "useNetworkInformation": false
    },
    "manifest": {
        "retryParameters": {
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000,
            "maxAttempts": 10,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5
        }
    },
    "drm": {
        "retryParameters": {
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000,
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5
        },
        "servers": {
            "com.widevine.alpha": "...",
            "com.microsoft.playready": "..."
        },
        "advanced": {
            "com.widevine.alpha": {
                "videoRobustness": "SW_SECURE_CRYPTO",
                "audioRobustness": "SW_SECURE_CRYPTO"
            }
        }
    }
}

And these are the time attributes from the manifest MPD element:
- minimumUpdatePeriod="PT2S" 
- timeShiftBufferDepth="PT1H" 
- maxSegmentDuration="PT3S" 
- minBufferTime="PT2S"

**Comment by joeyparrish** [comment]
The `playing` event you're referring to comes from the video element, correct?  I believe that's based on some state in the browser, and it could perhaps be gated on a license for DRM content.  Do you see the behavior you expect for clear content?

Shaka does not delay a license request as far as I can tell.  If the manifest contains PSSHs, we can request licenses in parallel with segments.  What I'm seeing in your screenshot is a license request that's very slow to get a response (we can't change that) and which starts after the first segment is complete.  This makes me think maybe your manifest is missing PSSHs.

Here are ways you can speed up the initial license exchange:
 - Make sure your packager puts PSSH information into the manifest, so that we don't depend on init segments for that
 - Supply a service certificate in the advanced DRM config, so that only one round-trip to the license server is needed for an actual license

You could also consider using a "clear lead" on your encrypted content.  This is usually 10 seconds or less of clear segments before the encrypted segments begin, so that even an early, manifest-based license exchange won't become a latency issue.

Does this help?
