### ISSUE TITLE
Major Garbage Collect every 5 sec after Shaka init

### ISSUE THREAD

**Issue by TavenCFC** [shaka-project/shaka-player#4305]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.1.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Yes

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 79.0.3945.79

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
LG model: 32LK615BPLB 
OS: webOS 4.4.0, 
firmware: 05.40.26

**What are the manifest and license server URIs?**
no manifest used

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default configuration

**What did you do?**
Initialize new shaka.Player(videoElem);

**What did you expect to happen?**

**What actually happened?**
I see the Major garbage collector runs every 5 seconds after Shaka player is initialized with Chrome DevTool Performance tab. This creates interface lag. It is not necessary to load the manifest to reproduce the issue. After the disposing of the player, the problem disappears. 
![mgc](https://user-images.githubusercontent.com/41690735/174084529-30781bfe-9d47-495a-b4ea-5cc8241dbfed.jpg)

**Comment by joeyparrish** [comment]
Is this reproducible in desktop Chrome, or only on WebOS?

Does the inspector show you what is being collected?

**Comment by joeyparrish** [comment]
I started looking at the timers in Shaka Player, to see if I could find any that run when the system is otherwise idle.  There are a total of 29 timers in the core Shaka Player source (lib/).

14 are one-off timers that are to delay specific events.  15 left.

I'm ignoring the 2 for live content in the HLS and DASH parsers, since nothing is loaded.  Same for the one that is for live DASH content in SegmentIndex, and the 3 for network retries, stalls, and timeouts.  9 left.

The CastReceiver class does some polling, but that's not running here, because it's not a receiver app.  8 left.

DrmEngine, GapJumpingController, PlayRateController, Playhead, PlayheadObserverManager, RegionTimeline, UITextDisplayer all poll for various things, but they are not running before we load content.  Player has a recurring timer that doesn't start until playback.  That's all of them in lib/.

Are you using the Shaka Player UI?  I haven't audited those timers in detail yet, but none of them run on anything close to a 5-second interval.

**Comment by TavenCFC** [comment]
I can reproduce it only on webOS.

I tried to run this [demo](https://developer.mozilla.org/ru/docs/Web/API/MediaSource) on LG and found that Major GC runs every 5 sec after this line:
`video.src = URL.createObjectURL(mediaSource);`
But in this case, on a html page with only video tag, it reports that 0 kb has been collected.
It looks like it's built into the webOS.

What do you think can be done with this issue?

**Comment by joeyparrish** [comment]
> I tried to run this [example](https://developer.mozilla.org/ru/docs/Web/API/MediaSource) on LG and found that Major GC runs every 5 sec after this line:
> `video.src = URL.createObjectURL(mediaSource);`

It's wonderful that you were able to figure that out!  Thank you!

> What do you think can be done with this issue?

That's a good question.  `createObjectURL` is a necessary part of any MSE application, including Shaka, and it's built into the browser implementation, so the details are inaccessible to us.

In Shaka Player, we call `URL.revokeObjectURL` as soon as the URL has been used to open a MediaSource instance, to avoid a leak.

I loaded the Shaka Player demo app and put breakpoints in those parts of the library, and I see that revokeObjectURL is being called automatically on the correct event, even before content is loaded.  So it appears that there is nothing we can do to control this GC effect on your device.

You may want to reach out to LG support.  Is this happening on a newer WebOS version, or an older one, or on every version you've tried?  Is the affected version of WebOS still supported by LG with firmware updates?

**Comment by aluklon** [comment]
We faced the same problem:
https://developer.lge.com/community/forums/RetrieveForumContent.dev?detailContsId=FC24191431&sMenuId=53&contsTypeCode=QUE&prodTypeCode=TV

**Comment by joeyparrish** [comment]
It looks like LG support has not come back with a solution or workaround in that forum post.

I'm really not sure that there's anything we can do in Shaka Player to influence this.  If the issue is triggered by `URL.createObjectURL`, and persists even after the URL is revoked, then there is no way to avoid it with MSE playback.
