### ISSUE TITLE
VOD HLS on Safari - the reported duration is the sum of length of downloaded chunks 

### ISSUE THREAD

**Issue by zilinx** [shaka-project/shaka-player#4311]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v4.1.1-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15

**What did you do?**
_Reproducible using this asset_: https://multiplatform-f.akamaihd.net/i/multi/april11/sintel/sintel-hd_,512x288_450_b,640x360_700_b,768x432_1000_b,1024x576_1400_m,.mp4.csmil/master.m3u8
_Preconditions_: slow internet connection. I used Network Conditioner to limit download to 1 mbps.

**What did you expect to happen?**
Duration (the time to the right of the timeline) is equal to the duration of the asset (4:09).

**What actually happened?**
Duration started with correct value. Once .ts segments started loading, the duration dropped and was equal to the sum of duration of chunks which were downloaded so far (therefore easier to reproduce on slow network), slowly increasing as more segments were downloaded. 

- could be reproduced on iPhone
- could not be reproduced with the same setup on Chrome (MacOS)
- could not be reproduced with default test assets
- could not be reproduced with hls.js player on Safari with the same setup.

**Comment by joeyparrish** [comment]
> * could be reproduced on iPhone
> * could not be reproduced with the same setup on Chrome (MacOS)

If this is the case, the issue is with Apple's HLS implementation.  On iPhone, we are forced to use Apple's HLS, and not our own implementation in JavaScript.  Therefore the duration behavior you see on iPhone is due to Apple, and the behavior you see on macOS is due to Shaka.

On iPhone, we merely set the `src` attribute of the video element to the m3u8 URL.  You can try doing this directly to see if that makes a difference in the duration.  If it does, please reopen the issue by putting `@shaka-bot reopen` in a comment, and we will take another look.

> * could not be reproduced with default test assets

This may indicate that the difference is in the encoding, structure, or specific tags in your content.  You may also want to report this to your encoder vendor.

Sorry we can't do more for you on this!
