### ISSUE TITLE
getPlayheadTimeAsDate() drift with MSE (mux.js transmux) & native Safari.

### ISSUE THREAD

**Issue by matvp91** [shaka-project/shaka-player#4330]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
Latest.

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `main`?**
Yes.

**Are you using the demo app or your own custom app?**
Both.

**If custom app, can you reproduce the issue using our demo app?**
Yes.

**What browser and OS are you using?**
Chrome, but anything that relies on MSE and mux.js for transmuxing.

**What are the manifest and license server URIs?**
Sent a manifest to shaka-player-issues@google.com.

**What did you do?**

First, the manifest contains a valid `X-EXT-PROGRAM-DATE-TIME` tag, when we play the first mpeg2ts file in the playlist and match it with what's present in the date time tag, the timing seems correct.

Load the manifest in Safari. Using the same calculation that Shaka uses when calling `getPlayheadTimeAsDate()`, the timestamp matches the burned-in-signal timestamp.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/12699796/176915664-0f6a7f9d-78e2-4d68-9ce6-acc82236577b.png">

The same HLS stream with shaka on Chrome (MSE, mux.js transmux), `getPlayheadTimeAsDate()` seems slightly off.

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/12699796/176916276-7ebe5410-bac5-4862-b1bd-ec5f236551ee.png">

**What did you expect to happen?**
Whether playback is based on native Safari or MSE, the playhead time should reflect the burned in timecode.

I'm having a hard time wrapping my head around these two functions:
- https://github.com/shaka-project/shaka-player/blob/main/lib/media/presentation_timeline.js#L232
- https://github.com/shaka-project/shaka-player/blob/main/lib/hls/hls_parser.js#L451

As far as my understanding goes, shouldn't it be sufficient enough to add the presentation time (reflected in `videoElement.currentTime`) to the first `X-EXT-PROGRAM-DATE-TIME` from the first playlist?

**Comment by joeyparrish** [comment]
> As far as my understanding goes, shouldn't it be sufficient enough to add the presentation time (reflected in `videoElement.currentTime`) to the first `X-EXT-PROGRAM-DATE-TIME` from the first playlist?

What we're actually doing in `getPlayheadTimeAsDate()` is this:

```js
const presentationTime = this.playhead_.getTime();
const timeline = this.manifest_.presentationTimeline;
const startTime = timeline.getPresentationStartTime();
return new Date(/* ms= */ (startTime + presentationTime) * 1000);
```

That differs slightly from what you suggest, but you're right in spirit.

`presentationTime = playhead.getTime()` should almost always be the same as `video.currentTime`, except in edge cases, such as during startup before we are able to seek to the initial position.  The video element's `currentTime` might still be `0` during this time, even though playback will begin at `playhead.getTime()` when the video element becomes seekable.

`startTime` should be roughly the same as the first `EXT-X-PROGRAM-DATE-TIME`, except that `EXT-X-PROGRAM-DATE-TIME` has to be extrapolated backward in some cases if the first one is mid-playlist instead of on the first segment.

I think what may be happening is that the HLS parser is using some features of `PresentationTimeline` that were designed for DASH and may not be necessary now that we have `EXT-X-PROGRAM-DATE-TIME` support (a recent development).  In particular, it looks like the parser sets the start time to 0, then relies on the default `autoCorrectDrift` setting to compute a dynamic start time based on the availability window and segment times.  This is likely unnecessary in many cases.

It's also the case that today, we only use `EXT-X-PROGRAM-DATE-TIME` to manage sync between audio and video playlists, so all we really care about in current Shaka Player is the relative difference between those values for audio & video.

Plese also note that unlike DASH, HLS has no facility for clock sync between client and server, and the local time (`Date.now()`) is a factor in the drift computation.  Is your client clock correct?  It's surprisingly common for individual machines to have some unnoticed problem with NTP on Linux or Microsoft's builtin time sync on Windows.

**Comment by matvp91** [comment]
Sorry for my delayed answer, I wasn't available for the past couple of weeks. I've verified the client clock and it is correct.

The `autoCorrectDrift` adjusts the startTime of the `PresentationTimeline` and once "corrected", the startTime is off as shown above. I quickly built a version with the `autoCorrectDrift` setting set to false in the HLS parser (where the PresentationTimeline is created, https://github.com/shaka-project/shaka-player/blob/main/lib/hls/hls_parser.js#L1864), and the stream does not start (I haven't had the time yet to figure out why).

**Comment by matvp91** [comment]
@joeyparrish, I don't think this should be closed as the behaviour is clearly different from the native HLS implementation on Safari, which makes me suspect that this is a bug.

@shaka-bot reopen

**Comment by joeyparrish** [comment]
Okay.  I'm setting this at a low priority for my team, though.  No promises on when we can get to it.

If you want to investigate yourself in the mean time, let me know how I can support you.

**Comment by avelad** [comment]
Can you check again against the main branch? Thanks!
