### ISSUE TITLE
Problem reproducing liveTV DASH streams with large timescale value

### ISSUE THREAD

**Issue by rskrok** [shaka-project/shaka-player#4337]
Hello,
our customer is an IPTV provider and wants to use Shaka player on smartTV devices: Samsung and LG.
However, they are using a very large timescale in the DASH manifest file (10000000), which we know that is generally not recommended for JavaScript players. Our customers is using these streams with these setting for years for other devices (set top box, mobile, etc.) with other players. For that reason they are very afraid of changing the streams (lowe the timescale) in order not to affect other devices/players.
Some of the TV channels work properly, however there are a number of other channels that present issues:
- shaka player on any device reports "gaps", like this "Jumping forward 0.12310194969177246 seconds because of gap starting at 1646642061.815654 and ending at 1646642061.858355" We belive these are not real gaps in the stream source, but gaps which a product of calculations with overflow caused by high value of the timescale. This is not a very big problem though on most of the devices, since the player resumes reproduction immediately after reporting the gap and this negligible for the user experience
- shaka player on smartTVs however freezes when these "gaps" happen. The most affected are Samsung/Tizen3 devices.

Is there any possibility to change in the player that the overflow does not happen?
If not, then is it possible to make some improvements in the player to avoid freezing on smartTVS?

**Comment by joeyparrish** [comment]
The JavaScript language has no integer type.  All numbers are double-precision floats, which means integer precision within that is limited to 53 bits.  If the timescale is so large that the integers for DASH's `$Time$` template exceeds 2^53, then rounding will occur at the JavaScript language level, and the wrong URLs can be generated.  This may also cause other issues we are unaware of.

Because of that, if a very large timescale causes an integer timestamp to overflow 2^53, the content is not supported by Shaka Player.  This is mentioned in the README (I know it can be hard to find anything there), and you can refer to #1667 for the original discovery and discussion of this.

Does this help?

**Comment by rskrok** [comment]
Hello, I understand that nothing can be addressed here in Shaka projects, so if it is the case then yes please clos it.
Out customer refuses to reduce the timescale value, so we need to switch to a commercial player, that can find out a work around for freezing, stalling and looping.

**Comment by theodab** [comment]
In #1667, we said that we did not want to include a third-party BigInteger library, due to file-size concerns.
However, a BigInt type was added to the JavaScript language, in the [ECMAScript 2020 specification](https://262.ecma-international.org/11.0/). According to MDN, [it is now supported on every browser besides IE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#browser_compatibility). The Closure Compiler supports ES 2020 too, apparently; see [here](https://github.com/google/closure-compiler/wiki/Releases#january-6-2021-v20210106).

That support graph does not mention some of the environments we officially support, such as Tizen or ChromeCast, so we would need to do some testing to see if it's actually an option for us.

I think that, if we do find that all of our supported platforms implement BigInt, it might be reasonable to change the timescale to use BigInts instead of numbers.

**Comment by joeyparrish** [comment]
According to MDN, Chrome added BigInt support in M67 (in 2018).  According to [Tizen docs](https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html), Samsung only moved from Chrome M63 to M69 in their 2020 model year devices.  So if anything, we're lucky that Chrome introduced support so far ahead of the ratification of the spec, since Tizen is always ~2 years behind in Chrome releases.

If we adopt BigInt:
  1. It will not be a high priority for the team.  It could be done much sooner if someone from the community did the work.
  2. If BigInt became a hard requirement, that would not be backward compatible with earlier releases.  So BigInt would have to be optional to avoid a bump to Shaka v5.
  3. A BigInt polyfill such as https://github.com/peterolson/BigInteger.js would be required for older platforms to play large timescales.  This one adds 5% to the size of Shaka Player.

For backward compatibility, I would suggest that:
  1. If a device doesn't have native BigInt or a polyfill installed, we should fall back to Number and still be able to play content with reasonable timescales.
  2. If a device doesn't have native BigInt or a polyfill installed, and the timescale is large (threshold TBD), we should refuse to play the content and throw a specific error code.  The docs for the error code should point people at a polyfill.

If we do it this way, it would not be considered breaking compatibility, and would not require a bump to Shaka v5.

I'll convert this into a low-priority feature request and mark it as seeking a PR.
