### ISSUE TITLE
How to check video robustness level for current playback

### ISSUE THREAD

**Issue by klimenkomaksim** [shaka-project/shaka-player#4369]
As stated in [this comment](https://github.com/shaka-project/shaka-player/issues/4013#issuecomment-1119213874) when no video robustness level is specified by the app it is up to the browser/platform to set default robustness level. For instance, for Widevine in Chrome, if no robustness is specified Shaka will default to the lowest robustness, but even this logic is may change at any time and should not be relied on.

So the question is, is there any API in Shaka and/or in the browser to check what robustness level is being used for the current playback?

**Comment by joeyparrish** [comment]
The default robustness level for the Widevine CDM must realistically be based on the content types in the `requestMediaKeySystemAccess` query.  If only one robustness level is available for the content, then that one will be selected.  If you have contractual obligations to use a certain minimum version, then specify it in the Shaka config, and you'll either get that, or a failure (which would match your contractual obligations).

If you can stream certain resolutions to a lower robustness level and others to a higher level, that is best handled in the license server proxy, which can decide which keys to return based on the device characteristics.  Content security shouldn't be managed in the JavaScript client, which is trivially modifiable.  If you don't return the keys in a license request, the CDM can't decrypt those streams, and the player will use other streams that we _do_ have keys for.

I think Chrome is wrong to log a warning when no level is specified.  I've long argued against that both internally and in the W3C.  I think it's nonsense.

So, with all that as context, there is no API to query the robustness level being used.  This goes beyond Shaka, as the EME API does not ever return robustness information other than what was in the query.  For example, you can try this in a debugger:

```js
basicVideoCapabilities = [
  {contentType: 'video/mp4; codecs="avc1.42E01E"'},
];
basicConfig = {
  initDataTypes: ['cenc'],
  videoCapabilities: basicVideoCapabilities,
};
mksa = await navigator.requestMediaKeySystemAccess('com.widevine.alpha', [basicConfig]);
mksa.getConfiguration();
```

You'll see a configuration like:

```json
{
  "audioCapabilities": [],
  "distinctiveIdentifier": "required",
  "initDataTypes": ["cenc"],
  "label": "",
  "persistentState": "not-allowed",
  "sessionTypes": ["temporary"],
  "videoCapabilities": [{
    "contentType": "video/mp4; codecs=\"avc1.42E01E\"",
    "encryptionScheme": null,
    "robustness": ""
  }]
}
```

As you can see, since we didn't ask for a specific robustness, and the configuration was accepted, EME's reported configuration is an empty string for robustness.  So there's no way for Shaka to extract and report a chosen robustness level.

But as I explained earlier, the correct place to control access based on device characteristics is in the license server proxy, which can get device info via the Widevine SDKs.  I think the Chrome warning log is (and has always been) misleading, confusing, and useless.

Does this answer your question?

**Comment by klimenkomaksim** [comment]
Thanks a lot
