### ISSUE TITLE
ui undefined when ui.configure(config)

### ISSUE THREAD

**Issue by jaime2m1** [shaka-project/shaka-player#4397]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 4.1.2

My code looks like this
```
            const video = document.getElementById('video');
            const ui = video['ui'];
            const config = {
                addSeekBar: false
            };
            ui.configure(config);
```
ui is undefined and i can´t call configure()
I don´t know why ui it´s not a shaka object

![image](https://user-images.githubusercontent.com/31405248/183885616-901de395-cac0-4925-9587-610c6d33663c.png)

**Comment by joeyparrish** [comment]
Is the video element tagged properly as we show in the tutorials?

```html
    <div
         style="max-width:40em"
         data-shaka-player-container
         data-shaka-player-cast-receiver-id="07AEE832">
       <!-- The data-shaka-player tag will make the UI library use this video element.
            If no video is provided, the UI will automatically make one inside the container div. -->
      <video autoplay data-shaka-player id="video" style="width:100%;height:100%"></video>
    </div>
```

Those `data-` attributes are what the library uses to find and populate DOM elements on startup.

Did you create the DOM elements dynamically after the library loaded and scanned the DOM?  If so, you could try using the UI API instead of relying on DOM scanning.  See "Programmatic UI setup" in the UI tutorial: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

Does this help?
