### ISSUE TITLE
How to get textTrack's source url?

### ISSUE THREAD

**Issue by raxxarr** [shaka-project/shaka-player#4400]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**
Hi.
Is there a formal way to get the source url of text tracks from a hls manifest? I want to handle vtt subtitles with some other module, which needs the urls. But i can just get them from `drm.getManifest().textStreams[0].segmentIndex.g[0].i()`, this seems strange and may change at any time. Any better way is suggested to get these urls?
Thanks.

**Comment by joeyparrish** [comment]
You mean the URL of a segment?

You should not use the minified names (`g` and `i` in your example) because as you guessed, those can change at any time.  They are automatically assigned by the compiler and can vary from one release to the next.

Instead, you can use exported methods of `SegmentIndex`: https://shaka-player-demo.appspot.com/docs/api/shaka.media.SegmentIndex.html

You could ask for a segment by time with `segmentIndex.find(time)` (returns a position) or `getIteratorForTime(time)` (returns an iterator over `SegmentReference`), or look up by position with `get(position)` (returns a `SegmentReference`).

Also, `SegmentIndex` implements the general JS interface `Iterable.<!shaka.media.SegmentReference>`, so you can use `Array.from(segmentIndex)` to get an array of all `SegmentReference`s.

Lots of options!  All of these are stable, exported (not renamed) methods that are part of the public API to support manifest parser plugins.

Once you have a `SegmentReference`, you can get an array of URIs for that segment (more than one if there's a failover) with `reference.getUris()`: https://shaka-player-demo.appspot.com/docs/api/shaka.media.SegmentReference.html#getUris

So instead of `drm.getManifest().textStreams[0].segmentIndex.g[0].i()[0]`, you could perhaps do `Array.from(drm.getManifest().textStreams[0].segmentIndex)[0].gerUris()[0]`.

Does this help?

**Comment by raxxarr** [comment]
Thanks so much, it helps a lot!
