### ISSUE TITLE
Contributing to the migration to a new build system

### ISSUE THREAD

**Issue by IsaacSNK** [shaka-project/shaka-player#4423]
Hi Team. I've seen many comments in different threads about migrating Shaka to a new build system. Do you have any roadmap or a list of changes that you think are required for this to happen? I can definitely contribute with a few hours of my time every week.

**Comment by joeyparrish** [comment]
At this point, we don't have a concrete plan.  I suspect it is best left until a TypeScript migration, at which point the old build scripts and compiler will be easily deleted.

**Comment by IsaacSNK** [comment]
Is it worth migrating start by changing the code to use ESModules instead of goog.requ and goog.provide? Assumming that Closure plays well with ESModules.

**Comment by joeyparrish** [comment]
Perhaps.  It has been discussed ([here](https://github.com/shaka-project/shaka-player/issues/2647) and [here](https://github.com/shaka-project/shaka-player/pull/4016)), but I've done very little research on this personally.

If people would like to experiment with this, I would suggest we start a new branch for it and PR into that branch.  I would want to avoid doing releases from main with a half-complete implementation of a goog.module transition.

Let's move discussion to #2647, though, since we already have an open issue for goog.module.
