### ISSUE TITLE
Unable to generate shaka-player.compiled.js using the python and Docker commands

### ISSUE THREAD

**Issue by jookeboxpm** [shaka-project/shaka-player#4619]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**What browser and OS are you using?**
Windows

**What did you do?**

Cloned the "shaka-player" repo for branch "v4.2.x"
Ran the command "python build/all.py" to generate the shaka-player files.
Also ran the command "docker-compose run --rm shaka-compiler" to generate the shaka-player files

**What did you expect to happen?**
To get a set of Shaka player docs

**What actually happened?**

The commands to generate the Shaka docs from the repository, as detailed in the docs([https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html]), threw the following errors:
Python:
![Shaka_Python](https://user-images.githubusercontent.com/63845268/198017327-3b087d0b-6a71-4c82-9f67-dd11df0bd6f4.PNG)

Docker:
![Shaka_Docker](https://user-images.githubusercontent.com/63845268/198017355-7b5d115f-d3c5-4cdc-a77b-089ac9d25553.PNG)

For Docker, I attempted to install the package "eslint-plugin-shaka-rules@latest" but it threw the error: 
`npm ERR! Cannot convert undefined or null to object`

I request your help to resolve this

**Comment by joeyparrish** [comment]
The first error says "A required dependency is missing: ... node.exe".  You have to install nodejs if you haven't yet.

Does this help?

**Comment by jookeboxpm** [comment]
Nodejs is already installed and the ".exe" file is present at the exact location mentioned in the error.

**Comment by joeyparrish** [comment]
There are two issues in this issue: 1. you can't build on Windows directly, and 2. you can't build in Docker.

Since the issue title is about Docker, I'm going to focus on that.  You can file a separate issue for Windows if you want.

Using my normal working directory for Shaka Player, I'm seeing the docker-compose command fail for me (in Debian Linux) because of a permissions error.  The docker container's user ("node") can't write to the host home directory (where I have a different user ID).

It looks like you're having a different issue than what I'm seeing.

I will try to fix my issue first by cleaning up and rewriting some of this docker mess, then see if that helps you with your issue or not.  Thanks for your patience.

**Comment by joeyparrish** [comment]
Please try the Dockerfile and other changes in #4633, which was just merged.  Does it work for you now with the updated Dockerfile and commands?

**Comment by jookeboxpm** [comment]
Yes. It works now. I ran the updated commands from the shaka docs([https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html]) and the docs were generated as expected. I used Ubuntu 20.04 to accomplish this
