### ISSUE TITLE
Is it possible to set low latency configuration for live streams after manifest is parsed?

### ISSUE THREAD

**Issue by fredrik-telia** [shaka-project/shaka-player#4681]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest

**Please ask your question**

We have live streams where some may be low latency DASH streams, and some might not be.

Is there a way to ask shaka if what we're playing is detected as a low latency stream, and based on that information configure the player with low latency parameters?

So far we've tried:
 * listening to the `manifestParsed`-event, can't find information if the stream is low latency, updating the config with lowLatencyMode: true doesn't seem to work (shaka still warns that we're playing a low latency stream without the correct configuration)
 * adding a manifestFilter and looking for the `availabilityTimeOffset`-parameter manually (as this seems to be what shaka is using to know if the stream is low latency) setting configuration here doesn't seem to work either, shaka still warns that we're playing low latency without the correct configuration

**Comment by joeyparrish** [comment]
Have you tried the `streaming.autoLowLatency` config?

https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.StreamingConfiguration

This is off by default because it conflicts with an older Shaka Player feature: response filters.  If you're not using response filters for segments, you can safely set autoLowLatency to true for all content.

Does this help?

<rant type="future-vision">

I think in the future, we should consider doing the inverse: always using LL features, except when response filters are configured for segments.  If someone is using segment response filters, we could issue a warning and turn off LL features.  We can't do that trivially today because response filters don't declare what type they care about (segment, license, manifest, etc).  Instead, the filter has to check the response type in its callback.  But with a v5 release and a breaking API change for filters, we could make LL require no configuration at all, which is arguably much more common and important than response filters.

</rant>

**Comment by fredrik-telia** [comment]
Using autoLowLatency works, but we would like more control over other settings (defaultPresentationDelay and rebufferingGoal) and toggle these settings based on if the manifest is low latency or not

As I understand it, using autoLowLatency, rebufferingGoal will be set to 0.01 unless otherwise specified.

I'll toggle it on and run some tests though, thank you!

**Comment by martinstark** [comment]
> response filters for segments

we're using synchronous response filters for segments to read the headers, autoLowLatency still seems to give us an improvement though. What's the potential issue that can happen here?

**Comment by martinstark** [comment]
We're running some custom filters to prevent stream stalls (detecting manifests that continuously update without causing shaka to fetch any segments) and detecting CDN switching on segments. Is there no way to get access to the segment headers for LL streams without patching fetch/xhr?

**Comment by joeyparrish** [comment]
LL DASH uses the `ReadableStream` API to pipeline data from the network directly to `MediaSource`.  There is no point in that flow when Shaka Player has a complete segment in memory to filter.

This is partly because the filter API allows both reading and writing.  You could imagine a read-only version of filters that still worked for LL, but would receive the data after it was consumed by MediaSource instead of before.  This, however, doesn't exist in Shaka Player today.

**Comment by martinstark** [comment]
Ok, there's probably something I don't understand here. The `ReadableStream` you use skips Fetch completely? As in, it's not using the `Response.body` `ReadableStream` part of the Fetch API?

**Comment by martinstark** [comment]
Does the `ReadableStream` you use somehow skip Fetch completely, or are you referring to the `Response.body` `ReadableStream`? I'm wondering if patching fetch to read the headers could be an option for us.

A readonly API would be nice, or any kind of solution that would make it possible to access the `Response.headers`.

**Comment by joeyparrish** [comment]
Perhaps we could offer a flag for response filters that indicates "read-only is okay" or one that indicates "headers only is okay".  Then those filters could still run in LL-DASH.

I think "headers only is okay" will be much cheaper to implement, FWIW.

**Comment by martinstark** [comment]
That would be a good feature for us to have access to. With some pointers it's possible I could have a go at implementing the change, I'm not sure where I should start looking.

**Comment by joeyparrish** [comment]
@martinstark, please look at the definitions for registerResponseFilter and related types (some in lib/net/ and some in externs/shaka/).  If you want to add a flag or alternate registration method for read-only, headers-only response filters, that would be the place to start.
