### ISSUE TITLE
[Suggestion] Update documentation regarding useNetworkInformation

### ISSUE THREAD

**Issue by camhart** [shaka-project/shaka-player#4691]
From what I've seen, browser connection bandwidth estimates (at least in Chrome) are very inaccurate at high connection speeds.  My videos kept playing back in the poorest quality (480p) for the first 10-30 seconds, and it was driving me nuts.  I could manually adjust it to 4k (45mbps), and my connection would handle it just fine.  Disabling useNetworkInformation caused shaka player to work as I was expecting it to.

My suggestion is to update the documentation to indicate that browser network information is a guess at best, and can cause initial playback to play in much lower quality than necessary.  I'd also add that when useNetworkInformation is enabled (and available), it overrides the defaultBandwidthEstimate.

**Comment by friday** [comment]
`useNetworkInformation` (default `true`) means use [downlink](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/downlink), if available (Chrome) to set the initial default estimate instead of the config option  `config.abr.defaultBandwidthEstimate` (default 1mbit/s).

There's really nothing more to NetworkInformation than that, but there's a lot more to the bandwidth estimation.

The default estimate is just the starting point it uses to select the variant it tries to use first. Then as it's downloading the segments for that it continuously updates the bandwidth estimation by timing the requests. Timing requests is unreliable, so it uses an algorithm called EWMA (Exponentially Weighted Moving Average) to get a more reliable average. It runs two separate instances of this algorith. One "slow" and one "fast". The slow one is for when your network speed increases and the fast for when you drop speed (since that has to be updated fast). You can set how slow/fast these should be with `config.abr.advanced.slowHalftime` and `config.abr.advanced.slowHalftime`

In addition to those config options `config.abr.bandwidthDowngradeTarget` and `config.abr.bandwidthUpgradeTarget` sets the breakpoints for when Shaka tries to upgrade or downgrade the variant as your estimate changes.

However that's not the full story either, because measuring network requests is tricky. Small requests are bad for determining the speed, so there's a config option for this too. Secondly, the estimate includes both the header lookup and the download. I think this is a flaw that can be corrected for better estimates, but either way you do it it can't be super accurate. The time it takes in the javascript vm is not the actual time the request took, so it won't be like the developer tools.

What in particular makes it unreliable is that Shaka doesn't filter out cached requests, so some requests can be ridiculously off. You can use a service worker to set a [`X-Shaka-From-Cache`](https://github.com/shaka-project/shaka-player/blob/main/docs/tutorials/service-worker.md#cache-header) header to mark requests so they won't be used for the bandwidth estimate, except that header isn't respected in the progress events.

You can't viably solve this with a service worker anyway, which is probably why no one complained about that.

**Comment by avelad** [comment]
@theodab can you review it? Thanks!

**Comment by joeyparrish** [comment]
@camhart wrote:
> My suggestion is to update the documentation to indicate that browser network information is a guess at best, and can cause initial playback to play in much lower quality than necessary.

This is not the case in our experience.  It generally results in higher quality at startup, since the default estimate is conservative and based on no data at all.  At least Chrome's initial hint is based on data from other applications/tabs.

> I'd also add that when useNetworkInformation is enabled (and available), it overrides the defaultBandwidthEstimate.

True.  We can add details to the documentation.

If you prefer, your application can both disable NetworkInformation and set a custom defaultBandwidthEstimate.  If you know, for example, that your application is generally used by desktops and not 3G mobiles, then you could afford to raise defaultBandwidthEstimate.

As a middleware library, though, we don't have that prior knowledge of the application's user base, so we keep defaults conservative.  In the absence of information, we prefer to start quickly and adapt up than to start slowly and adapt down.

I hope that helps explain things.

@friday wrote:
> I suspect the Shaka team prefers to work on things that can actually be solved/improved than this, but I agree this could be better documented.

I would be happy to see the docs updated.  Docs PRs are very welcome!  (Use `docs: ` in the PR title.)

> I don't think Shaka could handle this much better other than a couple of small things. Maybe you have too many or too few variants, or something else is slowing it down.

We're also open to improvements to bandwidth estimation and ABR in general, if you have ideas.  We'll keep this issue focused on docs, but you can file any feature requests or suggestions separately.  Thanks!

@friday, @camhart, would either of you be interested in updating the docs about bandwidth estimation?
