### ISSUE TITLE
Uncompiled deps file path error

### ISSUE THREAD

**Issue by downquark** [shaka-project/shaka-player#4706]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.0

**Please ask your question**
I'm having an issue with [shaka player](https://www.jsdelivr.com/package/npm/shaka-player) package's [uncompiled](https://cdn.jsdelivr.net/npm/shaka-player@4.3.0/shaka-player.uncompiled.js) version.

I'm trying to follow the instructions at the bottom of this page: https://shaka-player-demo.appspot.com/docs/api/tutorial-debugging.html
But the [deps.js](https://cdn.jsdelivr.net/npm/shaka-player@4.3.0/dist/deps.js) file has the wrong path in it on jsDelivr.
Would it be possible to update as follows?
'../../../../' should be ''../../"

See below error:
It should be going to something like this:
https://cdn.jsdelivr.net/npm/shaka-player@4.3.0/lib/polyfill/pip_webkit.js

GET https://cdn.jsdelivr.net/lib/polyfill/pip_webkit.js net::ERR_ABORTED 404
goog.writeScriptTag_ @ base.js:579
goog.importScript_ @ base.js:545
goog.writeScripts_ @ base.js:644
goog.require @ base.js:347
(anonymous) @ shaka-player.uncompiled.js:44

![Screenshot from 2022-11-13 10-48-53](https://user-images.githubusercontent.com/650273/201680562-ba25f73c-7387-42ec-90b4-8e4194f22d51.png)

**Comment by joeyparrish** [comment]
`deps.js` is an artifact of the Closure Compiler and Closure base library.  If jsdelivr.net has deployed those to different locations than they were originally, we can't control or fix that.  Changing `deps.js` paths to match jsdelivr's layout would break someone else's (including our own appspot demo or the local builds from GitHub).

The relative paths in deps.js are supposed to be relative to the folder for Closure's `base.js`, which when you clone the repo, is located at `node_modules/google-closure-library/closure/goog/base.js`.  So `../../../../` will get you back to the project root.

If you're loading base.js from here:
https://cdn.jsdelivr.net/npm/google-closure-library@20200101.0.0/closure/goog/base.js

and deps.js from here:
https://cdn.jsdelivr.net/npm/shaka-player@4.3.0/dist/deps.js

Then even `../../` would not be the correct root for deps AFAICT.  It would be more like `../../../../shaka-player@4.3.0/`.

Instead, I **recommend** you do uncompiled-mode debugging from local sources instead of jsdelivr.

---

If you really want to make it work from the CDN, there **may** be a way.  I've never done this, though.  Digging through Closure Library's sources, it appears you could override `goog.basePath` in between loading `base.js` and loading `deps.js`.  Something like this might work:

```js
goog.basePath = '../../../../shaka-player@4.3.0/test/test/assets/3675'`;
```

This is an arbitrary, but real, path that is four levels deep within Shaka's sources on jsdelivr.  It **might** work, even if there is some reason the full relative path needs to exist before collapsing the `../` parts.  If it doesn't work, though, see my recommendation above that you just clone the source from GitHub instead.  What I *think* it this will do is make `base.js` construct paths like this relative to `https://cdn.jsdelivr.net/npm/google-closure-library@20200101.0.0/closure/goog/base.js`: `../../../../shaka-player@4.3.0/test/test/assets/3675/../../../../lib/text/cue.js`.

That path **looks** silly... and it **is**.  Closure's deps system was the best thing we had when this project began in 2014.  Some time in 2023, we will give more serious effort to a TypeScript and module migration, but that would get rid of "uncompiled" "builds" anyway.

---

Does this help?

**Comment by downquark** [comment]
Thank you so much, I know it was silly but CDN worked with the following:
```
    <!-- Closure base: -->
    <script src="https://cdn.jsdelivr.net/npm/google-closure-library@20200101.0.0/closure/goog/base.js"></script>
    <script>goog.basePath = 'https://cdn.jsdelivr.net/npm/shaka-player@4.3.0/test/test/assets';</script>
    <!-- Deps file: -->
    <script src="https://cdn.jsdelivr.net/npm/shaka-player@4.3.0/dist/deps.js"></script>
    <!-- Shaka Player uncompiled library: -->
    <script src="https://cdn.jsdelivr.net/npm/shaka-player@4.3.0/shaka-player.uncompiled.js"></script>
```

Looking forward to TypeScript whenever it comes
