### ISSUE TITLE
In stats, what is the difference between licenseTime and drmTimeSeconds?

### ISSUE THREAD

**Issue by kiran-dcunha** [shaka-project/shaka-player#4725]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
-

**Please ask your question**
In stats, what is the difference between licenseTime and drmTimeSeconds? I read the [docs](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Stats) and it looks like both are same. Can I get a detailed explanation?

**Comment by Robloche** [comment]
My understanding is that `licenseTime` encompasses all the operations related to the license, and downloading the first DRM key (`drmTimeSeconds`) is only one of these operation.

**Comment by kiran-dcunha** [comment]
![image](https://user-images.githubusercontent.com/102036812/203975902-87e2820d-e16a-421d-8ded-a6fed21b596b.png)
That is what I would thought, but this is the behaviour on an LG webOS TV. `drmTimeSeconds` is more than `licenseTime`

**Comment by Robloche** [comment]
I agree with you: that's very strange, and not what the docs seem to explain...

**Comment by theodab** [comment]
`licenseTime` is the total time spent downloading license requests.

`drmTimeSeconds` is the time between when we create the DRM engine and when we finish updating the `MediaKeySession` with the first license. This includes some non-downloading-related operations; it includes the time we spend waiting for a `message` event from `MediaKeySession`, the time we spend waiting for `MediaKeySession.update` to resolve, that sort of thing.

So `drmTimeSeconds` is expected to be higher, unless multiple licenses were downloaded in which case `licenseTime` might be higher (since `drmTimeSeconds` only measures the first request). For `drmTimeSeconds` to be more than a second longer, I guess that means that DRM operations are slow on LG webOS TV?

I guess the docs don't explain that distinction very well, though.

**Comment by Robloche** [comment]
This part of the docs could indeed benefit from a revision.
