### ISSUE TITLE
If I click the full screen button of the video in the div that contains the video tag, I want to apply the top-layer to the Div tag, what should I do?

### ISSUE THREAD

**Issue by dnxodl1001** [shaka-project/shaka-player#4758]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.3.1

**Please ask your question**
Hello This is Steve.

Shaka player confirmed that when the full screen button is clicked, top-layer is applied to the div tag, not the video tag, as shown in the image below.

By the way, when I work locally, when I click the full screen button, the top-layer is applied to the video tag, so can I know how to make it work with the shaka player?

I'd really appreciate it if you could answer me.

Thank you.

![image](https://user-images.githubusercontent.com/117717284/203887384-824bace4-bbf4-4505-ad7b-640ba8f184e2.png)

![image](https://user-images.githubusercontent.com/117717284/203887856-fd98deea-a255-47bd-aba0-bdd4c1570908.png)

**Comment by joeyparrish** [comment]
Hi Steve,

Unfortunately, I don't completely understand your question.

I'm going to make some guesses, so please correct me if I'm wrong.

It seems like you might be observing how when our demo app goes to fullscreen, it uses the video container element (div) instead of the video element.  This is done using the fullscreen API in the browser, which lets you request a specific element.  That API is called by the fullscreen button of the Shaka Player UI, which is used by our demo.

If you use Shaka Player without our UI, and use the `controls` attribute of the video element instead, you get a fullscreen button provided by the browser natively, and it behaves differently.  That button will only make the video element fullscreen.

Did I infer that correctly?

To get the fullscreen behavior of the demo app, you can either use our UI (check out the UI tutorial), or you can turn off the native browser controls and add your own that invoke the fullscreen API on the element of your choice.

Does this help?  If I misunderstood, please see if you can find a different way to phrase your question, and I will try again to answer it.
