### ISSUE TITLE
Closed Captions are not displaying at Top of the Player

### ISSUE THREAD

**Issue by suraj-discovery** [shaka-project/shaka-player#4761]
The subtitles/closed captions in the video are placed on the top of the video by a flag "**isPlacedOnTop**" flag, which gets true value whenever there is an induction of forced narratives. There are no identifiers for forced narratives, but vttCue.line values signify at which stream of events the closed captions must be placed on the top of the player when forced narratives will be displayed at the bottom of the player.
This logic is applying for HLS when we are playing the video in the Safari browser, but the same is not happening for Shaka Player when we are playing the Chrome browser. Moreover, the subtitles are embedded in the video itself and are not coming separately via Web VTT files.
**Do we have a provision to log the vttCue objects, and if yes then where should we place the logs, followed up by does, Shaka explicitly alters the value vttCue.line ?**

**Comment by subhanahmed047** [comment]
Looking at the [WebVTT specs](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#cue_settings), if the cue's `line` property is set to positive, the captions would appear starting from the top of the page. i.e. `0` would make them appear at the very top. Similarly, setting it to negative makes them appear from the bottom. i.e. `-1` would make them appear at the very bottom. 

I did not test your particular scenario, but I was trying this with Shaka `v4.3.0` the other day with a dash manifest and the formatting was as expected for me. 

It would be of more help If you could provide more details about your manifest, and the shaka version you're using.

**Comment by suraj-discovery** [comment]
Currently, we are using Shaka v3.2.0.

**Comment by joeyparrish** [comment]
We have released many updates to the v3.2 branch since v3.2.0.  I would advise you to try the latest version in that branch, v3.2.16, before you do anything else.

If you still have an issue on v3.2.16, I would ask you to try the latest releases from our other active branches next:
 - v3.3.14
 - v4.2.5
 - v4.3.1

If none of those work, please file a new issue using the "bug" template, and provide all the information requested there.  Then we will be able to reproduce your issue and debug it for you.

Does this help?
