### ISSUE TITLE
Playlist with mixed segment with and without DRM (ClearKey)

### ISSUE THREAD

**Issue by st-oka** [shaka-project/shaka-player#4774]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.3.0

**Please ask your question**
I am trying SSAI using [Google IMA DAI SDK for HTML5](https://developers.google.com/interactive-media-ads/docs/sdks/html5/dai)
When playing the playlist which main content (non-advertisement part) is encrypted with AES-128 and advertisement is not encrypted, I get the following error before mid-roll is played.
![Screen Shot 2022-12-01 at 12 14 58](https://user-images.githubusercontent.com/54257797/204961439-cae4b567-98c7-4949-91ba-307752161940.png)

Also, if the playlist that neither of which is encrypted, can play mid-roll without any problem.
I assume that this issue is caused by the shaka-player not being able to handle the switching between encrypted (ClearKey in this case) and unencrypted segments.
Could you confirm my understanding is correct? Thank you in advance for your answer.

**Comment by joeyparrish** [comment]
Switching between encrypted and unencrypted content in the player is a no-op.  We don't do anything special.  It is all handled by the browser's CDM and decoders.

**Comment by joeyparrish** [comment]
Mixed encrypted/unencrypted content is extremely common, especially for server-side ad insertion.  This structure should not be an issue.  In fact, even without ads, some encrypted VOD content begins unencrypted for several seconds (called a "clear lead") to allow time for the license exchange without delaying startup.

Please check `chrome://media-internals` to see logs of what the browser is doing, and what errors are occurring at that level.  That might give a clue that leads you to the root cause.

**Comment by st-oka** [comment]
Thanks for sharing this useful information. I also understood that mixed encrypted/unencrypted content is extremely common.
I checked chrome://media-internals, and indeed this gives more information about player's behavior, but it didn't seem to help with this issue.
I've attached a screenshot of what I tried, could you think of anything that might have caused it from these?
(There is an error at the last event "kPause" in the first file)

![FireShot Capture 465 - Media Internals - media-internals](https://user-images.githubusercontent.com/54257797/205539547-95cbb6c2-74a4-44bd-b8c9-ca0c85a47309.png)
![FireShot Capture 465 - Media Internals - media-internals2](https://user-images.githubusercontent.com/54257797/205539584-38e2731c-69e4-4c58-ad30-22cb1a9d22b4.png)
![FireShot Capture 465 - Media Internals - media-internals3](https://user-images.githubusercontent.com/54257797/205539604-b5f4bb2b-7f08-43e1-9ee3-094bc38065c9.png)

**Comment by joeyparrish** [comment]
> (There is an error at the last event "kPause" in the first file)

I don't see it.  In the first screenshot, kPause is the last event shown.

After re-reading your issue, I noticed something inconsistent that we should clarify.  Are you using ClearKey (which is an open, demo DRM system)?  Or HLS's AES-128 (which uses _clear keys_, but not ClearKey DRM)?  There is an important distinction, and they have to be implemented in completely different ways in the player.

**Comment by joeyparrish** [comment]
It's pretty confusing.

AES-128 is a block cipher, and there are many "modes" in which you can use it, by combining it with other operations in some kind of chain, or by feeding it with certain data.

All standardized DRM (the "Common Encryption" standard) uses AES-128 at its core, in one of two common modes (CTR or CBCS).  However, the "AES-128" encryption used by Apple in HLS is incompatible with all of those DRM schemes.  It uses CBC mode, but encrypts the entire segment instead of just parts of it.  It's also not considered DRM.  What makes it harder to understand is that Apple's FairPlay DRM uses Common Encryption, not the encryption they describe in HLS.

All DRM uses the EME API in the browser.  Encryption and key requests are handled inside the browser in something called a CDM (Content Decryption Module).  Apple's FairPlay, Goggle's Widevine, and Microsoft's Play ready are all DRM.  ClearKey DRM is not "real" DRM because the keys are in the clear, but it is handled by a CDM and uses the same decryption as the other DRM systems.

HLS's "AES-128" encrypts the entire segment (unlike DRM), so the CDM can't decrypt it.  Even the ClearKey CDM is incompatible with this.  So this content is decrypted using WebCrypto APIs in JavaScript.

I'm going to assume you're using HLS's AES-128 full-segment encryption.  So what might be happening is that the player is decrypting a clear ad with the key for the previous main content.  Then what gets fed to the browser for that ad is random-looking garbage, and it fails to decode.

Can you please provide an accessible playlist URL for us to debug?  I'll relabel this as a bug.  Thanks!

**Comment by st-oka** [comment]
Thank you for your uncomplicated explanation.

Please use the following assekey for your debugging playlist: `wXx6SY-wRcW7uJCK4Y619w`
We will try to keep it running until **this week** for once as our encoder resources are limited.

**Comment by avelad** [comment]
@st-oka is the issue the same as https://github.com/shaka-project/shaka-player/issues/4846?

**Comment by avelad** [comment]
Can you check with the main branch?

**Comment by st-oka** [comment]
@shaka-bot reopen

**Comment by st-oka** [comment]
I can confirm that this issue no longer occurs thanks to this fix.

**Comment by st-oka** [comment]
@shaka-bot reopen
