### ISSUE TITLE
Shaka Player not working on Samsung Tv running Tizen

### ISSUE THREAD

**Issue by sarthaknerd** [shaka-project/shaka-player#4857]
The Shaka player is showing, but it is not playing. It works fine in VS CODE and even in Tizen Studio with the watch. I have tried the following troubleshooting steps: cleaning the project, updating and installing all required modules from the package manager, using console.log (which did not work), reconfiguring the emulator, and giving internet permission in the config file.

****

**Comment by joeyparrish** [comment]
It's working for us in our automated tests.  In that context, we're creating a Tizen TV app based on a simple template, with an iframe that loads the automated tests from a test runner called Karma.

Here's the template we use: https://github.com/shaka-project/generic-webdriver-server/tree/main/backends/tizen/app-template

You might compare the config.xml file to your own.

If you need more specific help with Shaka Player on Tizen, please use the issue template for bugs and provide URLs and other details so that we can reproduce your issue.

Thanks!
