### ISSUE TITLE
mediaCapabilities queries include keySystemInformation for unencrypted content

### ISSUE THREAD

**Issue by Wayne-Morgan** [shaka-project/shaka-player#4868]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.1

**Can you reproduce the issue with our latest release version?**
I assume so. There don't look to be changes in this area

**Can you reproduce the issue with the latest code from `main`?**
I assume so. There don't look to be changes in this area

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
Not possible to define DRM licence server URL

**What browser and OS are you using?**
Windows, Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://dash.akamaized.net/dash264/TestCasesUHD/2b/11/MultiRate.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
DRM servers are defined for widevine and playready. The exact values aren't significant, as this is an unencrypted stream, but it's significant that they are defined

**What did you do?**
Try to play the content

**What did you expect to happen?**
The content plays

**What actually happened?**
The content doesn't play. I see "4032-Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER()"

We have always kept the same DRM configuration whether playing encrypted or unencrypted content, and for most content this has been fine, but when we tried the HEVC stream listed above it failed. Tracing the code it seems that it's because the `keySystemInformation` is included in the query to `navigator.mediaCapabailities.decodingInfo()` even though the content is unencrypted.

Is it possible to exclude `keySystemInformation` from this query for unencrypted content, while maintaining the `drm.servers` configuration?

**Comment by joeyparrish** [comment]
This is not feasible, because we can't be certain that content is actually unencrypted just from the manifest.

For server-side ad insertion in live streams using multiple DASH Periods, you typically end up with unencrypted ad Periods and encrypted main content Periods.  At the time we join the stream, it is possible that only unencrypted ad Periods are listed in the manifest.  So we rely on the configuration of the player to know that encrypted content is _expected_.

If your content is unencrypted, and you know this, you should remove the DRM servers from your player config.  Decoding capabilities can vary between encrypted and unencrypted content on the same system, since the CDM may only be able to securely communicate with certain decoders and not others.

**Comment by Wayne-Morgan** [comment]
Thanks @joeyparrish. I appreciate the feedback.
