### ISSUE TITLE
HLS - Invalid (ambiguous) video codec string

### ISSUE THREAD

**Issue by AltFreq07** [shaka-project/shaka-player#4901]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.3

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Edge (109.0.1518.49) - Windows 11 (22H2 - 25276.1000)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://stream4.debrid.link/stream/*Removed*/playlist.m3u8;panel=CUSTOM%20CONTENT;build=debug_compiled

```
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-high",LANGUAGE="eng",AUTOSELECT=YES,DEFAULT=YES,NAME="English",URI="audio/high-2/segments.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5382144,CODECS="avc1.64001b,mp4a.40.2",AUDIO="audio-high",RESOLUTION=-1080x1080
video/1080p/segments.m3u8
```

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default on the demo website
Personal website player configuration is minimal changes
```
{
      preferredTextLanguage: 'en',
      preferredAudioLanguage: 'en',
      preferForcedSubs: true,
      streaming: {
        lowLatencyMode: true,
        bufferingGoal: 120
      }
    }
```

**What did you do?**
Tried to play the HLS stream

**What did you expect to happen?**
Video plays as it does on other video platforms
Works on both:
- https://videojs.github.io/videojs-contrib-hls/
- https://hls-js.netlify.app/demo/

**What actually happened?**
Same error on the demo application and my personal website.
![image](https://user-images.githubusercontent.com/36876748/212575682-178d651c-b99a-4ad2-a85c-0670ea43820a.png)

**Comment by AltFreq07** [comment]
```
MediaSource.isTypeSupported('video/mp4; codecs="avc1.64001b,mp4a.40.2"')
true
document.createElement('video').canPlayType('video/mp4; codecs="avc1.64001b,mp4a.40.2"')
'maybe'
```

**Comment by avelad** [comment]
@AltFreq07 your stream returns a 404. Can you review it? Thanks!

**Comment by AltFreq07** [comment]
> @AltFreq07 your stream returns a 404. Can you review it? Thanks!

Unfortunately, the stream doesn't last too long, anywhere you know of I can upload a copy.

Updated stream https://stream2.debrid.link/stream/54a0a409-a8ad-4fdf-b409-8745f4955868/playlist.m3u8

**Comment by avelad** [comment]
<img width="675" alt="Captura de pantalla 2023-01-16 a las 9 59 32" src="https://user-images.githubusercontent.com/8983024/212638138-80a7787d-ccb9-4ce6-bad9-c3effd11452e.png">

Now, I get a 403

**Comment by AltFreq07** [comment]
I'll work on rehosting the file somewhere else, otherwise i might find another source which would fix the issue for me but not the overall problem unfortunately.

**Comment by AltFreq07** [comment]
I've managed to upload a copy to here - https://pzname.b-cdn.net/54a0a409-a8ad-4fdf-b409-8745f4955868/playlist_1.m3u8
The file does not have audio though but still presents the same.

**Comment by AltFreq07** [comment]
Appears to be working in Firefox v108.0.2 using the latest 4.3.3 demo site using the above URI.

**Comment by theodab** [comment]
If you run:
```js
navigator.mediaCapabilities.decodingInfo({
    type: 'media-source',
    video: {
        contentType: 'video/mp4; codecs="avc1.64001b"',
        width: 1920,
        height: 1080,
        bitrate: 5382144,
        framerate: 1
    }
})
```
Chrome fires the "Invalid (ambiguous) video codec string" warning you mentioned, and the return value is that the config is not supported.
Firefox does not give the error, and reports that the config is supported.
Safari is also okay with it.

So it looks like the Chromium implementation of the MediaCapabilities API does not like that codec string.
Not sure why, honestly. I tried reading [mime_util_internal.cc](https://chromium.googlesource.com/chromium/src/+/b6be2ef08a6cc5ae86dcc4a9cd2b3e3066353726/media/base/mime_util_internal.cc), which is where Chromium decides if a codec string is "ambiguous", but I'm not exactly a Chromium codebase expert and I ended up confusing myself.

**Comment by theodab** [comment]
I assume that means that other players don't use the MediaCapabilities API?
Yeah, I just checked and HLS.js doesn't use it at all. Meanwhile, DASH.js has support but it's disabled by default.

We don't have any way at the moment to manually disable MediaCapabilities. I guess we could add some way of doing it. Maybe a configuration value or something?

Alternatively... well, we already have to have special support for `vp9` codecs, and for RFC-4281 formatted `avc1` codecs. I guess we might also be able to add some kind of mapping to add support for "ambiguous" `avc1` codecs, such as the `avc1.64001b` you are using.
I don't know if making a special case for just `avc1.64001b` is the right solution though. I wish I knew why Chrome was rejecting the codecs, so I could at least suggest a more future-proof way of... disambiguating them, I guess.

**Comment by joeyparrish** [comment]
@AltFreq07, it's not a matter of "ignoring" the warning.  In fact, we can't see that warning in the player at all.  It is logged by the browser directly to the dev console.

That warning, however, explains the API failure.  The call @theodab showed you above:

```js
await navigator.mediaCapabilities.decodingInfo({
    type: 'media-source',
    video: {
        contentType: 'video/mp4; codecs="avc1.64001b"',
        width: 1920,
        height: 1080,
        bitrate: 5382144,
        framerate: 1
    }
})
```

Returns:

`{powerEfficient: false, smooth: false, supported: false, keySystemAccess: null}`

When the browser tells us "**supported: false**", we **can't** ignore it, because it generally means that playback will fail if we continue.

-----

As for what that codec string means, according to [Mozilla](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter#iso_base_media_file_format_mp4_quicktime_and_3gp), the codec string is of the format:

> `avc1.oo[.PPCCLL]` (AVC video)
> `oo` is the OTI describing the contents, while `PPCCLL` is six hexadecimal digits specifying the profile number (`PP`), constraint set flags (`CC`), and level (`LL`). See [AVC profiles](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter#avc_profiles) for the possible values of `PP`.

That would make 64001b mean:
 - profile 100 (0x64) = [High Profile](https://en.wikipedia.org/wiki/Advanced_Video_Coding#Profiles)
 - no constraints (0x00)
 - level 27 (0x1b) = [1b](https://en.wikipedia.org/wiki/Advanced_Video_Coding#Levels)

I had never heard of level "1b" before.  Experimentally, I find that changing the level bytes to "0a" (level 1.0) or "0b" (level 1.1) both work.

When I Google "level 1b", I find [this page](https://blog.pearce.org.nz/2013/11/what-does-h264avc1-codecs-parameters.html) that says:

> Level 1b is an oddball encoding, and is encoded as 11 decimal with the constraint_set3_flag equal to 1. If the constraint_set3_flag is not equal to 1, level 1.1 is encoded.

So perhaps the constraint bits are set in a way that is inconsistent with the level, or perhaps Chrome simply doesn't recognize that level.

-----

I recommend you update/fix the encoder to output the correct (recognizable) codec string.  If you can, update the level to 1.1, since level 1.1 decoders can handle everything allowed by level 1b.  That would be "avc1.64000b".

There's nothing more for us to do in the player, since the browser is telling us explicitly that your original codec string is unsupported.

I hope this helps!  Feel free to point your encoder vendor to this page if they need more information.  Also, feel free to file a bug against Chrome at https://crbug.com/ if you feel that Chrome's behavior is wrong.

**Comment by AltFreq07** [comment]
Thanks for the information.

Unfortunately I don't have access to the encoder. Is there any way to force
a codec and see if that works temporarily or modify the manifest at run
time?

Feel free to close this issue :)

**Comment by AltFreq07** [comment]
Modifying the manifest on the fly using blob urls may be a solution in the
mean time depending if changing codec and uris can be successfully changed
