### ISSUE TITLE
[HLS] Player crashes when switching audio tracks in stream with PDT tags

### ISSUE THREAD

**Issue by fredrik-telia** [shaka-project/shaka-player#5014]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.3.4 and nightly

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome, macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

see separate email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default config, only change is setting `preferredAudioLanguage` to `sv`

**What did you do?**

Play the url provided in separate email
email will also include instructions on how to update the url in case it has expired

**What did you expect to happen?**
Content should play without type errors in Chrome

**What actually happened?**

With `sv` configured as preferredAudioLanguage, one particular HLS stream will cause a TypeError in Chrome.
In Firefox it will play without any error

<img width="737" alt="image" src="https://user-images.githubusercontent.com/56258400/219632647-3f05a5b1-2290-4ac9-836a-5ba3dd40031e.png">

**Comment by martinstark** [comment]
The player seems to keep playing through this error, but since we cannot know if a native Error thrown by Shaka is fatal to the playback session, we opt to close the player in our production environments on uncaught errors thrown inside Shaka. 

Effectively, Shaka is broken in Chrome for us with 100% start up error on this kind of stream on 4.3.4.

**Comment by fredrik-telia** [comment]
`git bisect` results:

```
8f9162f154cd63404bbe95667396a9b12fe73ca6 is the first bad commit
commit 8f9162f154cd63404bbe95667396a9b12fe73ca6
Author: Joey Parrish <joeyparrish@users.noreply.github.com>
Date:   Thu Jan 12 14:22:40 2023 -0800

    fix: Sync each segment against EXT-X-PROGRAM-DATE-TIME (#4870)

    Closes #4589
```

**Comment by martinstark** [comment]
We've investigated ignoring the error, doing so allows the stream to start, but changing audio tracks throws another error. 

Ignoring that error will leave the player with an infinite spinner, because it is unable to find a track to select. The TypeError error is fatal.

Given that, this seems like a pretty serious issue.

**Comment by martinstark** [comment]
Removing the `preferredAudioLanguage` configuration parameter causes the player to stall/crash when switching audio track, so it is not strictly related to this configuration.

**Comment by fredrik-telia** [comment]
We have some new findings, will update the url sent by email

**Comment by avelad** [comment]
@martinstark @fredrik-telia are you interested on send a PR to fix it? Thanks!

**Comment by avelad** [comment]
@fredrik-telia Can you test against the main branch? Thanks!
