### ISSUE TITLE
Doubt regarding getVariantTracks multiple entries

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#5028]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.2

**Please ask your question**
1st. I have a manifest where it has got 7 representations all in standard format video heights from `1080p` to `320p` However, `getVariantTracks` function returns me 42 entries. https://github.com/shaka-project/shaka-player/blob/main/ui/resolution_selection.js#L83 As per the login in UI Library we are filtering out all the first matching tracks. Question is from where is our manifest parser getting these many tracks. Among 42 tracks I filtered all the tracks with height `1080`
`const sample = test.filter((t) => t.height == '1080')` 

![image](https://user-images.githubusercontent.com/61311751/221287293-c962e7af-eb9d-4e8c-9a69-329a5ed235af.png)

Now, I got 6 tracks then I created a function which checks which property is uncommon among all of them Found that it is just `audioBandwidth` and `bandwidth`, so from where is the parser inferring these props? I couldn't find these values in the manifest? Rather in manifest 
`<Representation id="1" width="1920" height="1080" frameRate="25/1" bandwidth="3000000" codecs="avc1.640028">`
the bandwidth for this track is `3000000` which doesn't match with any one from all those 6 tracks returned above. Is there some preference play here in our manifest parser? 

2nd. I am create a hook/function `useQuality` in  react which for user which will return him these tracks. Now, as per the logic in UI Library we select random or the first one, So should I return the track with highest bandwidth?

3rd. In case of `ABR` will these tracks be selected depending upon the bandwith?

**Comment by peaBerberian** [comment]
@WINOFFRG 

I'm not a shaka-player dev but for the first question, I guess that's because you also have 6 audio `Representation` in your MPD for that Period, the shaka-player combines audio and video Representations into "variant" tracks, presumably to improve code and API compatibility between HLS (which rely on this concept of multi-type "variants" for specific bandwidth values) and DASH (which have mostly independent `AdaptationSet` and inner `Representation` instead, the latter being linked to those bandwidth values).

So 6 audio `Representation` * 7 video `Representation` in the MPD == 42 "variant" tracks in the shaka-player whose characteristics represent every combination of both.
I agree it's not obvious and may be surprising to someone just familiar with DASH but I guess they had to make compromises when handling both HLS and DASH tech.

**Comment by WINOFFRG** [comment]
Sounds reasonably correct, Thanks for the explanation! 

Keeping the issue open for 2nd and 3rd query.
