### ISSUE TITLE
Demo app: 'REPORT BUG' button does not use bug report template and does not add 'type: bug' label

### ISSUE THREAD

**Issue by zangue** [shaka-project/shaka-player#5056]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.5-uncompiled

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Yes

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

n/a

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

n/a

**What did you do?**

1. Go to https://shaka-player-demo.appspot.com/
2. Click on 'REPORT BUG' button

**What did you expect to happen?**
A new issue using the `bug_report.md` template with label `type:bug` to be opened

**What actually happened?**

A new issue with a template different from `bug_report.md` and no label opened

**Comment by theodab** [comment]
The bug report button having a different template from the default bug report template is intentional. If you're pressing that button, it's assumed you're having an issue with the demo... so questions like "are you using the demo app or your own custom app?" aren't very relevant.
This special template hasn't been kept up to date, though, and I agree that it should apply the bug label by default.

Instead of using a different template, maybe it would make more sense to use a copy of the default template with values pre-filled...
