### ISSUE TITLE
Why do subtitles remain on Safari when playing live content through Shaka Player?

### ISSUE THREAD

**Issue by valletgood** [shaka-project/shaka-player#5151]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.0

**Please ask your question**

When playing HLS live content through the Shaka Player in Safari, the subtitles continue to be displayed and are not disappearing. When checking the activeCues through the Web API textTracks, it was found that some cues have an endTime of Infinity. What is the reason for this phenomenon?

**Comment by joeyparrish** [comment]
If you're using native HLS in Safari, Shaka Player has no control over the subtitles.  Please check the [`streaming.useNativeHlsOnSafari`](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html) config.  If it is set to true, then you'll need to file this issue against Apple at https://bugs.webkit.org/

You can set that flag to false explicitly to see if it changes the behavior, but that flag is effectively always true on iOS, because native HLS is the only option for iOS.

**Comment by valletgood** [comment]
Thank you for your response. Upon checking, it was found that streaming.useNativeHlsOnSafari was set to true. I will need to file this issue with Apple.

**Comment by joeyparrish** [comment]
Thanks for the update!
