### ISSUE TITLE
Mac OS Safari Browser Playback issue (3016)

### ISSUE THREAD

**Issue by suhaibk7** [shaka-project/shaka-player#5162]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.3.5

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
custom app
**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Safari Browser 16.3 and MacOS Ventura

**What did you do?**
<img width="1440" alt="Screenshot 2023-04-20 at 2 13 47 PM" src="https://user-images.githubusercontent.com/70581980/233311231-425df6bf-2617-4476-9643-93c8276dbe17.png">

**What did you expect to happen?**
Videos are expected to play on both chrome and safari browser without any issue. 

**What actually happened?**
Videos are playing as expected on Chrome browser but the same video is not playing on Safari browser.

**Comment by suhaibk7** [comment]
Hi, it has been a while since I posted this question. It is kind of really important for me to get a solution for this question. Any help would be much appreciated.

**Comment by imtiaz101325** [comment]
Hey @suhaibk7

My comments aren't a direct solution to the problem, so feel free to ignore them.

I see you are a bit concerned with people not helping you out when you really need it, and I get it.

But you have to understand that this is an open source project and the maintainers are incredibly busy.

Following would be ways you can try and help yourself:
- Brush up on video playback basics if you haven't already
- Understand why Safari is a bit of an odd ball when it comes to video playback 
- Use tools like documentation, this project's GitHub issues, Google, Stackoverflow, and ChatGPT to get more clues
- If you still haven't figured it out then come back to us with what you have tried so far with as much information as possible so that the maintainers can just tell you what's wrong at a glance

I hope you will find this helpful 😄

**Comment by joeyparrish** [comment]
A screenshot makes it very difficult for someone to reproduce your issue.  Please either provide code in a block with triple backticks like this:

```js
// here is the code
```

Or provide links.  If the problem is reproducible in our demo, please copy the demo URL when the content is playing, and that will include the asset URI so that people can quickly reproduce your issue and provide you with feedback and/or fixes.

**Comment by suhaibk7** [comment]
@joeyparrish thanks for the suggestion sharing code snippet here.

`<!DOCTYPE html>
<html>
  <head>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.3.5/shaka-player.compiled.js"
      integrity="sha512-K0vnbY/0ZJ+TRetnq8EK9ge2au+MBu7L1gjfiJiQlpGOmPh/qlJudl7IA2cUmvlFmSQqlJ49+wr8aw3S1vb/yQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/mux.js@5.5.1/dist/mux.min.js"
      defer
    ></script>
    ,

    <script>
      const manifestUri =
        'https://stagingvideocdn.adda247.com/ivs/9426/masterpl.m3u8';

      function initApp() {
        shaka.polyfill.installAll();

        if (shaka.Player.isBrowserSupported()) {
          initPlayer();
        } else {
          console.error('Browser not supported!');
        }
      }

      async function initPlayer() {
        const video = document.getElementById('video');
        const player = new shaka.Player(video);

        window.player = player;
        player.addEventListener('error', onErrorEvent);

        try {
          await player.load(manifestUri);
          console.log('The video has now been loaded!');
        } catch (e) {
          onError(e);
        }
      }

      function onErrorEvent(event) {
        onError(event.detail);
      }

      function onError(error) {
        console.error('Error code', error.code, 'object', error);
      }

      document.addEventListener('DOMContentLoaded', initApp);
    </script>
  </head>
  <body>
    <video id="video" width="640" controls></video>
  </body>
</html>
`

**Comment by veronicamirada** [comment]
We are experiencing an issue that can be the same as the described one.
Since we upgraded to ventura 13.3.1 and Safari 16.4 we cannot reproduce any video.
On shaka player Demo, we are unable to play "angel one" content.

[https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=HOME;build=uncompiled](https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=HOME;build=uncompiled)

**Comment by naktinis** [comment]
I can confirm this is still happening and has been happening for a while. It may be related to this issue: https://github.com/shaka-project/shaka-player/issues/4538

**Comment by avelad** [comment]
Can you try the main branch? Thanks!
