### ISSUE TITLE
Playback Error in iPad Version 13 and 14 on Safari

### ISSUE THREAD

**Issue by YutaMoriJP** [shaka-project/shaka-player#5182]
Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?
Yes

What version of Shaka Player are you using?
Latest version

Can you reproduce the issue with our latest release version?
Yes

Can you reproduce the issue with the latest code from main?
Yes

Are you using the demo app or your own custom app?
Demo app

If custom app, can you reproduce the issue using our demo app?
Yes

What browser and OS are you using?
OS : iOS (iPad)
Browsers : Safari/605.1.15 

For embedded devices (smart TVs, etc.), what model and firmware version are you using?
N/A

### The Problem:
When using Safari on iPad (v13 and v14), changing the tab and going back to the tab, and playing the video causes the playback to fail. This occurs both in my own video app and in the Shaka player demo app as well. The issue seems to only happen in version 4 and not in version 3...

Error objects I'm getting are:
```js
category: 3
code: 3015
data: [InvalidStateError: The object is in an invalid state.] (1)
handled: false
severity: 2
```

```js
category: 3
code: 3016
data: [3, undefined, undefined] (3)
handled: false
severity: 2
```

**Comment by veronicamirada** [comment]
We are experiencing an issue that can be the same as the described one. 
Since we upgraded to ventura 13.3.1 and Safari 16.4 we cannot reproduce any video.
On shaka player Demo, we are unable to play "angel one" content.

**Comment by loicraux** [comment]
Idk if it's related, but I observed this in Safari on iPadOS 16 :

1. I have a tab open with my video app using shaka-player 4+
2. I open another tab, I scroll a bit in it...
3. I come back to the first tab containing my video app
4. I click on play

Expected behavior:

The playback starts at the beginning, so at 00:00:00

Observed behavior:

The playback starts later, for example at 00:01:50 (the numbers may vary)

This behavior is not observed if I stay in the first tab containing my video player before I hit the play button...

**Comment by avelad** [comment]
Can you test if the main branch still has the problem? Thanks!
