### ISSUE TITLE
Getting 3016 error while playing video content in WebOS LG TV

### ISSUE THREAD

**Issue by ParthGit-sudo** [shaka-project/shaka-player#5215]
We are using shaka-player v4.2.3
When we play the video on TV and then turn off, we are getting 3016 error code every interval of 1 minute.

You can check the log below :
`ShakaPlayer.error Error: Shakaplayer closed{"severity":2,"category":3,"code":3016,"data":[4,null,null],"handled":false}`

**Comment by ParthGit-sudo** [comment]
Hi @joeyparrish , 
Do we able to get the solution for this problem in v4.4 ? and when v4.4 will be published ?

**Comment by theodab** [comment]
WebOS LG TV is considered a community-supported platform for us (see the support matrix). I don't believe we have a testing machine for it in our lab at the moment?
That is to say, we don't really have a good way of testing LG TV issues at the moment. You shouldn't expect this to be fixed anytime soon, at least by us.

I'll mark this as seeking PR for the moment.

**Comment by stevenewing** [comment]
Can confirm this happens on LG2017 exclusively.

LG2016 works/LG2018 works.

Also worth noting that we have seen this issue since Shaka Player 2.x.

We were able to get playback by using Widevine instead of Playready.

WebOS 3.5-3.8 did have a different version of Playready compared to WebOS 3.0-3.3 which seems to only work through the Luna APIs.

I am doubtful it can be fixed in Shaka Player, it is low level DRM stuff. (Happy to try anything out in our lab if anyone has any ideas on this cryptic issue though)
