### ISSUE TITLE
Skip the start of a period

### ISSUE THREAD

**Issue by soualid** [shaka-project/shaka-player#5256]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.6

**Please ask your question**
Is it possible to use `Period` `start` attribute or `SegmentTemplate` `presentationTimeOffset` attribute to skip the first seconds of a `Period`?

Like, if the second period media contains a preroll that we want to skip, is it possible by just modifying the MPD somehow?

**Comment by joeyparrish** [comment]
If you modify the manifest, yes, you can adjust period starts and presentation time offsets, and remove segment references as well (if they are explicit in the manifest).  You can also remove whole periods if you want.

These modifications would only work well if all of the metadata agrees when you are done.  (Period durations, start times, and presentation duration, for example, should all agree.)  If you are doing this by text editor rather than with some more intelligent tools, be careful.  (Also, I don't have any tools to recommend for this particular problem.)

Does this help?

**Comment by soualid** [comment]
Yes, many thanks to confirm that it should be doable! 

Still, I guess I am missing something to set the metadata properly.

Here, I tried to play the first period for 2 seconds, and then a second one of the same segments with an offset of `51200`, with a duration of 4 seconds, to make a 6 seconds media.

It's not playing properly but I guess I'm just missing something somewhere.

[Archive.zip](https://github.com/shaka-project/shaka-player/files/11619344/Archive.zip)

(the original manifest is called `original-manifest.mpd` in the archive, and is containing the original and properly playing manifest)

Many thanks!
