### ISSUE TITLE
HLS(iOS/macOS) not supported error

### ISSUE THREAD

**Issue by mihoc925** [shaka-project/shaka-player#5302]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
-> Yes

**What version of Shaka Player are you using?**
-> 4.3.6

**Can you reproduce the issue with our latest release version?**
-> Yes

**Can you reproduce the issue with the latest code from `main`?**
-> Yes

**Are you using the demo app or your own custom app?**
-> custom app

**What browser and OS are you using?**
-> Safari

**What are the manifest and license server URIs?**
-> Pallycon

--------------------

**What did you do?**

I was streaming hlsuri without any issues, but after upgrading the version of shaka-player,
I encountered a 6007 error which caused Safari to stop.

I performed several tests using shaka-player.ui(min).js and discovered that there was a problem with the JS.
Specifically, I noticed an error occurring after version 4.0.0 (Error Occurred Version: 4.0.1~4.3.6).

DASH content plays fine, but it appears that there have been some modifications related to HLS.

**Comment by WINOFFRG** [comment]
This should most probably some issue with your player configurations. Make sure to read here https://pallycon.com/docs/en/multidrm/clients/html5-player/#shaka Also make sure to check Network tab for any HTTP errors. 
Otherwise I think it will be best to share the manifest URLs if they are public already.
