### ISSUE TITLE
What is the best way to add costume headers to each ShakaPlayer request in Safari

### ISSUE THREAD

**Issue by MeirHebrew** [shaka-project/shaka-player#5348]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**Please ask your question**

I'm facing an issue with ShakaPlayer while loading it through an iframe. 
In order for the player to function properly, a specific header with a predetermined value needs to be set.
Failure to include this header results in the CDN blocking the player.

I have successfully addressed this problem for Chrome browsers using the following code snippet:

`
Player.getNetworkingEngine().registerRequestFilter(function(e, r) {
  return r.headers.MyHeaderName = "mySpecialValue", Promise.resolve(r);
});
`
However, when it comes to Safari browsers, this filter doesn't seem to be effective.
I tried to debug it using a console.log statement to verify its execution, and it appears that the filter is never called. 
Additionally, I discovered a related issue on GitHub (https://github.com/shaka-project/shaka-player/issues/3912#issuecomment-1024725124), which suggests limitations on using filters in Safari.

Therefore, I'm seeking guidance on the best approach to resolve this issue specifically in Safari. How can I set the required header information in Safari to ensure the proper functionality of ShakaPlayer?

**Comment by theodab** [comment]
I assume you are talking about an HLS manifest here?
A filter not working for HLS content on Safari is because, by default, Shaka Player does not actually play HLS content in Safari, it just asks the browser to play the content. We did that because the Safari implementation of MediaSource has historically been quite buggy.
If you are talking about desktop Safari or iPadOS Safari, set the `streaming.useNativeHlsOnSafari` config value to `false` to make Shaka Player start playing content itself.
For iOS Safari, there's no way for this to work, because iOS Safari doesn't implement MediaSource. See [CanIUse](https://caniuse.com/mediasource).
