### ISSUE TITLE
aac support in shaka

### ISSUE THREAD

**Issue by neerajgulati-airtel** [shaka-project/shaka-player#5398]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.7

**Please ask your question**
With release of v4, is shaka able to support aac audio codec in hls. I am getting error only sometimes that "Skipping unsupported HLS stream audio/aac trailer_Kadaisi_Vivasayi_Streaming_Now_Hindi96k.m3u8".

**Comment by WINOFFRG** [comment]
This might help you https://github.com/shaka-project/shaka-player/issues/4746#issuecomment-1324303317

**Comment by joeyparrish** [comment]
You should be able to play raw AAC in HLS if it's supported by your browser.  You may also want to try adding mux.js to your app, since that enables certain transmuxing options that are not available otherwise.  We are getting more built-in transmuxing capabilities without mux.js in v4.4+ (upcoming).

Does this answer your question?
