### ISSUE TITLE
Shaka Player method to detect DRM configure usage

### ISSUE THREAD

**Issue by whatever1211** [shaka-project/shaka-player#5628]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Version 3.3.19

**Please ask your question**
Hi Shaka team,

We want to ask is there a method that can help detect a stream is using DRM configure or not?

We have situation of using a player DRM configures for both DRM and Clean streams. Now we want to identify between the stream. Is there a player method that can help us?

Thanks.

**Comment by whatever1211** [comment]
Hi @avelad,

I have tried using:
keySystem()
drmInfo()

And here is the result for DRM stream
![DRM](https://github.com/shaka-project/shaka-player/assets/32158927/2fdd6eae-d56a-4c0f-801c-cced93e8479d)

Clean stream
![Clean](https://github.com/shaka-project/shaka-player/assets/32158927/13b2922c-879f-4ab0-8240-fb1b3584cac2)

keySystem() always return com.widevine.alpha
drmInfo() does not return null

**Comment by joeyparrish** [comment]
If the player is configured for DRM, we set up DRM and playback happens through the CDM.  We have to do this based only on the configuration, because we can't know in advance if the content is clear or encrypted.  Mixed clear+encrypted content is common and we may not be able to see all metadata at once in a live stream , so even checking the manifest doesn't provide a definite answer.

If you're trying to determine whether the content is encrypted or not after playback begins, you'll need to look at the `initData` field or the `keyIds` field in `drmInfo()`.  If there is no initialization data, we didn't create any key sessions for DRM.  If there are no key IDs, we don't have a DRM license.  Either of those indicates that we have only seen clear content *__so far__ at the time you queried it*.  If it's a live stream, and you join during an unencrypted ad break, the answer could change later if the encrypted main content returns.

Does this help?

**Comment by whatever1211** [comment]
Ok I understand,

So in case of Pure DRM and Pure Clear (No mixed). I can use `getKeyStatuses()` to identify the content. Empty object as Clear, and Non-Empty object as DRM?

**Comment by joeyparrish** [comment]
`getKeyStatuses()` will show you if you have a license or not, but there may be a license request in progress.  `drmInfo().initData` will show you if there are any DRM sessions, even if they don't have a license yet.  So that may be better.

**Comment by whatever1211** [comment]
Thank you for your help, I got it.
