### ISSUE TITLE
Access response detail when the response is not successful

### ISSUE THREAD

**Issue by zangi-dev** [shaka-project/shaka-player#5719]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, found something related here: https://github.com/shaka-project/shaka-player/issues/3533

**What version of Shaka Player are you using?**
4.0.1

**Please ask your question**
Any way to see the response detail (headers, status code) when the status code is >= 400?

I tried to use:

- ResponseFilter: can see only successful responses
- downloadfailed event: no details about the response only the request. httpResponseCode is 0

Is downloadfailed only showing the request because the response is available with some other method?

Thanks!

**Comment by theodab** [comment]
I will make a PR to expose more information inside the `downloadfailed` event.

**Comment by theodab** [comment]
Actually, this is looking like it might not be possible.
I tested an experimental change on a manifest someone sent for testing that produces a `403` issue.
The fetch call throws the error: `TypeError: Failed to fetch` before even creating a response object, which means we have no way of getting what the error code was. The XHR API also did not seem to have any way to get the info of a failed request, though I admit I did not spend as much time looking with that.
According to this Chromium bug report, this might be intentional?
https://bugs.chromium.org/p/chromium/issues/detail?id=118096#c5

I don't understand the reasoning myself, but I tested this on Firefox also and it has the same behavior so I guess that must be part of the spec.
