### ISSUE TITLE
Incorrect detection of MediaCapabilities on Chromecast, resulting in MEDIAKEYS_UNSUPPORTED error

### ISSUE THREAD

**Issue by alexgerv** [shaka-project/shaka-player#5776]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.3.4 (default version included in CAF)

**Can you reproduce the issue with our latest release version?**
Did not attempt yet, as issue is not reproducible at will, only sporadically.

**Can you reproduce the issue with the latest code from `main`?**
Did not attempt yet, as issue is not reproducible at will, only sporadically.

**Are you using the demo app or your own custom app?**
custom receiver app using CAF

**If custom app, can you reproduce the issue using our demo app?**
No. Issue is not reproducible at will, only sporadically.

**What browser and OS are you using?**
Chromecast (all models)

**What are the manifest and license server URIs?**
Issue happens before starting playback. We can provide URLs if necessary. 

**What configuration are you using?**
Default Chromecast configuration. 

**What did you do?**
We have a spike of `MEDIAKEYS_UNSUPPORTED` errors after we released a new version of our Chromecast Receiver App with the latest CAF (3.0.0111) which also updated Shaka to version 4.3.4. 

From the data we have, a user would try to start a new casting session and immediatly get this error, but after disconnecting and trying to cast again, it would work. 

Reverting the Shaka version to **3.2.2** (the one bundled with the previous CAF) solves this issue, but we are trying to understand the cause of this error so we can use a more recent version of Shaka.

We never managed to reproduce the issue ourselves, but looking at the data we have from production, it seems like there is sometimes a problem during initialization which causes the device/Chrome/Shaka to report as **not supporting any video codecs**. We see that when the error happens, our calls to `canDisplayType` on the CAF context also always report `false` for that session even for parameters we know should work on that device. For example, a Chromecast v3 would report as not being able to display a 1080p 30fps avc1.640028 stream which it easily should be able to do.

The fact this error is only happening with newer versions of Shaka is really puzzling us, since from what we can see Shaka simply calls `navigator.requestMediaKeySystemAccess` and throws `REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE` or `NO_RECOGNIZED_KEY_SYSTEMS` when it fails and those errors are then mapped to `MEDIAKEYS_UNSUPPORTED` by the CAF. 

The only thing we can think of is that there were some changes in the timings of the player initialization or in the polyfills used to manage that.

**Comment by alexgerv** [comment]
Hi @joeyparrish :) knowing the Cast focus of the Shaka team, do you think you could have a look at this issue ? 
Very though one because we don't have repro steps, but also very annoying for our customers because they get random failures to initiate streams. Thanks in advance !

**Comment by avelad** [comment]
@theodab @JulianDomingo can you review it? Thanks

**Comment by simonlary** [comment]
From looking more into it, the issue is caused by the changes in #4727. The `navigator.mediaCapabilities.decodingInfo()` polyfill now checks `cast.__platform__.canDisplayType()` on Chromecast devices, but this sometimes returns `false` when the device is actually able to play the media.

This bad reporting seems to happen in setups where the Chromecast device is being casted to, but the display is not actually opened. Like when a user starts to cast to have the audio on their AC receiver, but don't open their TV.

Overriding the new polyfill with the old one fixes the issue, but we would obviously like a better long-term solution. 🙂

**Comment by alexgerv** [comment]
@JulianDomingo would you have any opinion on the reliability of `cast.__platform__.canDisplayType()` ? It seems this check sometimes fails, which causes misdetection of capability in some cases when display is not fully ready upon loading the cast receiver application.

**Comment by theodab** [comment]
I spent a while examining the code behind `cast.__platform__.canDisplayType()`.

My current theory is that in the situation @simonlary described above (display has not yet opened), it might not yet know what the maximum resolution is. Before the maximum resolution is known, it looks like the code defaults to it being 0 by 0. If that is the case, it would reject any content with a known width or height... and we attach the width and height of the video, in that polyfill.

I don't have much more time to look into this issue, unfortunately. It sounds like you have a setup to test it, though, so you could try commenting out these lines in the polyfill:
https://github.com/shaka-project/shaka-player/blob/3a14047a1208a6e03431aa088030dc0cbc96952c/lib/polyfill/media_capabilities.js#L271-L272
If we stop providing the width and height and suddenly the issue stops reproducing, that would suggest it is due to the canDisplayType method rejecting content with width and height values before the maximums are known.

If that is the case, we might be able to handle this on the Shaka Player level by periodically running a query along the lines of:
```js
cast.__platform__.canDisplayType('video/mp4; codecs="avc1.42E01E"; width=1; height=1')
```
And delaying calls to `decodingInfo` until that query passes. Perhaps with a timeout attached, in case the display never powers on. It'd be crude, but a more immediate fix than something that would involve changes to the Cast end.

**Comment by joeyparrish** [comment]
I tested this on both models I have at home, and I found that the Android-based devices (latest) do not have this problem.  Only the older Linux-based models have this issue.

Sadly, this means we can't rely on a firmware update to fix it, since some of these are devices that no longer receive updates.  We will have to work around it either in the Cast SDK or in the player.  I have not yet determined if a fix in the Cast SDK is possible.

**Comment by alexgerv** [comment]
Hi Joey, 
I confirm your observations from above, only Linux-based devices were affected.

From @simonlary and my perspective, solution number 1 (always ignoring the resolution in canDisplayType, like before) would be perfectly fine.

**Comment by joeyparrish** [comment]
Internally, we are discussing several related steps, though only the first addresses this issue:

1. removing width/height in canDisplayType
2. memoize/cache canDisplayType results to reduce startup latency (these are synchronous calls involving IPC)
3. using MediaCapabilities on certain Cast devices instead of always using canDisplayType (needs research into which devices have trustworthy implementations of MCap)

**Comment by avelad** [comment]
> > @joeyparrish can we enable MCap for Android Cast-devices? (See: [65903aa](https://github.com/shaka-project/shaka-player/commit/65903aa27b5723632ff16a92059cb20c4879fc59), I think we should remove native TS support everywhere for this to work properly)
> 
> It depends on whether or not MCap is correctly implemented there. We're investigating implementations with the various platform teams. There are broadly three different types of OSes and runtime implementations on Cast devices: Linux, Fuchsia, and Android.

Do you have the result of the investigation? Thanks!

**Comment by avelad** [comment]
Sorry, was a mistake
