### ISSUE TITLE
Why is the default Shaka version at 4.3.4 in Chromecast receiver?

### ISSUE THREAD

**Issue by kirandcunha** [shaka-project/shaka-player#6179]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

No

**What version of Shaka Player are you using?**

**What browser and OS are you using?**

**Please ask your question**
Why is the default Shaka version at 4.3.4 in Chromecast receiver?
Is there a significance to this version, like it is tested more extensively by Cast/Shaka team?
Why does this not get updated to the latest version automatically, as there is an options for shakaVersion in the configuration?

**Comment by avelad** [comment]
@theodab can you review it?

**Comment by theodab** [comment]
The cast receiver doesn't put out new releases very fast, and the last time it was changed in an update was [last july](https://developers.google.com/cast/docs/release-notes).

I don't think that updating the Shaka version automatically would be a good idea; Shaka Player gets to release frequently without a lot of oversight from Google, as it is an open-source project. Making the default Shaka version be whatever the newest one is would make it easier for security vulnerabilities to slip into the cast receiver code.

For example, this line: https://github.com/shaka-project/shaka-player/blob/3537dc0a68eeb22890ffc7e658e5eb940eb1fd43/ui/seek_bar.js#L598
It seemed innocent enough to me when I was doing code review, but in retrospect it is a security vulnerability by Google standards and practices as it is loading resources from an unknown, potentially-unsafe url. It's loading an image, so it's probably not a realistic attack vector, but it'd still need to be addressed to be up to Google standards.

For us to update the Shaka version, I think we'd have to first address that line (and a few other such problems). Because of that, there's no way the cast receiver could update it automatically.

**Comment by kirandcunha** [comment]
Is there a timeline available as to when we can expect the Shaka version to be updated? Or how often we can expect the version to be updated?

**Comment by joeyparrish** [comment]
> Why is the default Shaka version at 4.3.4 in Chromecast receiver?

Because that was the latest version at the time we made a particular branch to our internal SDK code.  That was a release we ultimately put out in June of 2023.  When we branched for the next release, we chose not to update the default so that we would minimize surprise for users of the SDK.

Unlike Shaka Player, the Chromecast SDK is currently a global update to a single URL used by all apps that follow our guidelines, so there are major risks to making big changes in the SDK or in the SDK defaults.  We do it periodically, but with great caution and at great expense in testing.

> Is there a significance to this version, like it is tested more extensively by Cast/Shaka team?

Yes and no.  Yes, it's more tested in context of the SDK, but only because we haven't changed the default for so long.  No, because it's not necessarily better or less buggy than newer versions.

> Why does this not get updated to the latest version automatically, as there is an options for shakaVersion in the configuration?

It doesn't get updated automatically in part because there are integration risks for partners (as I mentioned above), and in part _because_ we have the `shakaVersion` configuration.  Since you, the app developer, have the ability to decouple the Shaka Player version from the SDK version, you can roll forward or backward to meet your app's needs without waiting for the SDK release.  For the last few years, we have only released SDK updates twice a year.  (We hope to improve that soon.)

> Is there a timeline available as to when we can expect the Shaka version to be updated? Or how often we can expect the version to be updated?

No, there is no specific timeline for that default to be updated.  I believe we will update it in at least one release in the next year, as soon as we come out with new features that support the migration to Shaka as the default HLS player in the SDK.  But until there is a Shaka release that supports that migration effort directly with a feature or critical bug fix, we will probably not rush to update the default version.  Every change we make to the SDK, including the defaults, has to be vetted against myriad partner apps to ensure we don't accidentally break them, and you wouldn't _believe_ how much time and effort that takes.

I hope this context helps!

**Comment by kirandcunha** [comment]
Yes this helps. Thanks!
