### ISSUE TITLE
Player.load requires startTime in presentation timestamps

### ISSUE THREAD

**Issue by jakubvojacek** [shaka-project/shaka-player#6241]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.7.9

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
my own app, since I don't think that I can use demo to force start from certain second

**What browser and OS are you using?**
Chrome + MacOS

**What are the manifest and license server URIs?**
https://edge1.motv.eu/s1/channels/recordings/eurosport-2-clear-40-71/2024/02/10/40-65bf6e622eed0-2024-02-10-11-45-cyklistika/data/40-65bf6e622eed0-2024-02-10-11-45-cyklistika-clear.mpd

Hopefully this URL will work for some time, if not, I will share a new one

**What did you do?**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Video Player</title>
    <!-- Shaka Player Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.7.9/shaka-player.compiled.debug.min.js" integrity="sha512-C0WsjfEA5l9y+QmVK7BkSxEWGnLD4FE2qslS20ZeRq6V91ryFO8h2sq0PURIatqGPsj/4uXmOXtnlqnPSyHImg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.7.9/shaka-player.ui.debug.min.js" integrity="sha512-9veM994T5eBzgybgFwqis2eGd+gzAYHPlYNaYnsnFxHxPw+2vbw3sQlTgLubEI4Bhs5q8b0O+MaFykG7QdykgA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Shaka Player Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.7.9/controls.min.css" integrity="sha512-4RC6gy+J9tI06Vqu8sntJdArqFk86ufXyDaDIzvAp/zMTcFzC0IQiH2iWOsL1i5/2+r6igS0xxtKCJZnPL2NTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div id="channel-player" style="max-width: 800px;">
        <video id="video" style="max-width: 500px;" autoplay></video>
    </div>

    <script type="text/javascript">
        // Initialize Shaka Player
        const videoElement = document.getElementById('video');
        const localPlayer = new shaka.Player(videoElement);

        const ui = new shaka.ui.Overlay(localPlayer, document.getElementById('channel-player'), videoElement);

        const contentStartTimestamp = 60;

        localPlayer.load('https://edge1.motv.eu/s1/channels/recordings/eurosport-2-clear-40-71/2024/02/10/40-65bf6e622eed0-2024-02-10-11-45-cyklistika/data/40-65bf6e622eed0-2024-02-10-11-45-cyklistika-clear.mpd', contentStartTimestamp);
    </script>
</body>
</html>
```

It is really very basic app, it just opens the MPD and attempts to start from 60th second.

**What did you expect to happen?**
I expected the content to start to be played at 60th second.

**What actually happened?**
It started at zero second.

And I know why. It is because the content is "special" - it does not start from zero. 

```
<SegmentTemplate timescale="90000" initialization="audio_clear_eng_stereo.mp4" media="a_clear_eng_stereo/$Number$.mp4" startNumber="1" presentationTimeOffset="71994">
          <SegmentTimeline>
            <S t="6479452576" d="549120"/>
            <S t="6480001696" d="864000" r="754"/>
          </SegmentTimeline>
        </SegmentTemplate>
```

the SegmentTimeline starts from nonzero `t` and with nonzero PTS.

Calling `player.load(url, 60)` does not work. In this case, I'd have to call `player.load(url, 6479452576 / 90000 + 71994 + 60` and it works like a charm and starts at 60th second. 

The content was created using shaka-packager by capturing static part of live stream. Unfortunately, I cannot tell shaka-package to start the MPD from zero and therefore I was hoping it would be possible to resolve in Shaka-player.  For example, exoplayer (also google product but from another team) handles this seamlessly and it works with `timeStart = 60` out of the box. 

I know I could wait for the content to load, check for example seekRangeStart and update `video.currentTime = player.seekRange().start + offset` but its far from ideal. Because the player loads the chunks twice, once from beginning and once from given offset.

Do you please have any idea how to achieve seamless player.load(url, 60) in shaka-player? 

Thank you for any advice
Jakub

**Comment by jakubvojacek** [comment]
```

**Comment by jakubvojacek** [comment]
```js
videoElement.addEventListener('loadedmetadata', () => {
          videoElement.currentTime = localPlayer.seekRange().start + 60
        });
```

this works but as I said, its not ideal + working with video.currentTime gets difficult because its starts for every catchup from different value. But shaka player is somehow capable of calculating the correct value - since it shows in the UI correct time

**Comment by absidue** [comment]
Don't use the video element's `metadataloaded` event, instead use the player's event e.g. in your case you want to listen to the `streaming` one: https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#.event:StreamingEvent .

**Comment by jakubvojacek** [comment]
@absidue thank you, but unfortunately, that does not help.

## does not work, does not seek at all
```js
player.addEventListener('streaming', () => {
          player.updateStartTime(60)
        });
```

## works, seeks to 60th second
```js
player.addEventListener('streaming', () => {
          player.updateStartTime(6479452576 / 90000 + 71994 + 60)
        });
```

The goal is to be able to be able to seek without the complicated formula

**Comment by absidue** [comment]
Didn't realise I had to spell every single step out for you, as I thought that it was obvious that you would need to use seek range start as well (that's the earliest point that your manifest indicates that can be seeked to). shaka-player uses the timeline that you specify in your manifest, so if you manifest doesn't start at zero, you cannot reasonably expect to be able to seek to a position starting at 0 either.

**Comment by jakubvojacek** [comment]
You dont have to spell out anything. Your advice to use streaming event instead of loadedmetadata was completely useless. As per my first post, I knew how to work around the manifest timing. 

I was asking whether its possible to add some configuration to shaka-player so that it would ignore the timeline offset and start from zero - like some other players, such as ExoPlayer, do out of the box without any additional configuration (or the player that Roku uses). If others can do it, shaka surely could too, therefore yes, I could _reasonably_ expect it. 

Thank you

**Comment by jakubvojacek** [comment]
Also, shaka already kind of does the recalculation, in the UI, it shows the start from zero and not from 77381. So I think either shaka should honor the time in all places, that is in the calculations as well as in the UI or not. Right now it displays one thing while showing another in the background. Shouldn't it be consistent? 

<img width="494" alt="Screenshot 2024-02-11 at 11 47 10" src="https://github.com/shaka-project/shaka-player/assets/3463456/65725856-1cde-45ec-8750-882be46a945d">

**Comment by absidue** [comment]
> Your advice to use streaming event instead of loadedmetadata was completely useless.

It's most certainly not useless, it addresses this part of your original post:

> I know I could wait for the content to load, check for example seekRangeStart and update video.currentTime = player.seekRange().start + offset but its far from ideal. Because the player loads the chunks twice, once from beginning and once from given offset.

Additionally this should have been opened as a question or a feature request, as your misunderstanding of how developer facing APIs work is most certainly not a shaka-player bug.

Also no the developer facing API is correct in using absolute values (that's also what videoElement.currentTime uses), as that's what you specified in your content. Imagine how horrible it would be for live streams if the value you passed it, would seek to a different position every time. shaka-player is respecting your wish as a developer to use those large offsets and correctly exposing those implementation details in the developer facing APIs, but as the user of the UI/the viewer couldn't care less about how the actual content is setup, the UI does a bunch of extra calculations to hide those implementation details.

The easier option would be to fix your content (if you don't want shaka-player to use large offsets, don't use them in your manifest), otherwise you'll want to replicate the UI calculations in your own code.

**Comment by joeyparrish** [comment]
Hey, it looks like this discussion is getting heated.  Let's avoid rude language that implies that others are less capable:

 * "Didn't realise I had to spell every single step out for you"
 * "I thought that it was obvious"

@absidue, please consider this a formal warning.  If someone misunderstands you, please do not disparage them over it.  Every one of us has misunderstood something at one time or another, and this is a big, complex project where it can be hard to get to the root of any issue.

I know we participate here because we want to be helpful to one another, so let's let our language reflect that spirit of community.  Thanks!

**Comment by joeyparrish** [comment]
@jakubvojacek, I can explain what is happening in the UI vs the player.

There are several distinct timelines involved in playback.  The most relevant ones are:

 * The media timeline: the timestamps in actual media segments.
 * The presentation timeline: the timestamps in the "presentation".  The timestamps seen by MediaSource and the video element, which may differ from the media timestamps.  These are adjusted when consumed by MSE.  For DASH, the formula is (media timestamp + period start time -  presentation time offset).
 * The seek range: the available content you can seek to.  This is a subset of the presentation timeline.
 * The UI range: the seek range, but offset to start at 0 for VOD content.

It's a little messy, but there's a diagram showing some of these relationships here: https://shaka-player-demo.appspot.com/docs/design/timeline.svg

---

The player API and the video element API (used for seeking) do everything in terms of the presentation timeline.  So when you seek with `video.currentTime = 60` or load content with `player.load(url, 60)`, you are specifying a presentation timestamp.  What you may not know is that the player will clamp that timestamp into the seek range.

Because 60 is before the start of the seek range, clamping that timestamp will move it to the earliest available time stamp.  This *looks* like it's ignoring your time because it's starting at the beginning.  But if you had picked a timestamp past the end of the seek range, such as 152000, it would move the playhead to the end of the seek range.

The UI can see that the content is VOD, and VOD content that doesn't start at 0 doesn't make much sense to the end user.  So it offsets the displayed timestamps so that the seek range starts at 0:00.

---

The reality of the "presentation" and the timestamps in the presentation timeline is dictated by the DASH manifest, which says:

```xml
  <Period id="0" start="PT71996S" duration="PT79249S">
<!-- ... -->
        <SegmentTemplate timescale="90000"
                         initialization="audio_clear_eng_stereo.mp4"
                         media="a_clear_eng_stereo/$Number$.mp4"
                         startNumber="1"
                         presentationTimeOffset="71994">
<!-- ... -->
            <S t="6479452576" d="549120"/>
```

You have a single period starting at timestamp 71,996 seconds, with a duration of 79,249 seconds.  This puts the end of the presentation at time 151,245, which is what the player reports for the end of the seek range.

The first segment of this audio track is at 6,479,452,576 (in the media timeline, in timescale units) with an offset of 71,994 (also in timescale units).  The timescale is 90,000, and the period start is 71,996 (in seconds).  Putting all this together, the first audio segment is at presentation time ((6479452576 - 71994) / 90000) + 71996 = 143,989.118 seconds, which is what the player reports for the start of the seek range.

Note that although the period start is 71,996 seconds, the first segment is at 143,989.118 seconds.  The segments get clipped to the period range, but it is the segments within the period that define availability and the seek range, not the period itself.

---

So if you want to start at a specific timestamp in the presentation timeline, use `player.load(url, timestamp)`.  If you want to start at a specific timestamp relative to the seek range, and you don't know it before loading the content, you should use the `streaming` event, as suggested by @absidue:

```js
  localPlayer.addEventListener('streaming', () => {
    videoElement.currentTime = localPlayer.seekRange().start + 60;
  });
  localPlayer.load(url);
```

---

I hope this all helps to explain how it works and why.

And to address your earlier comment:

@jakubvojacek wrote:
> So I think either shaka should honor the time in all places, that is in the calculations as well as in the UI or not. Right now it displays one thing while showing another in the background. Shouldn't it be consistent?

I can understand why you might think that.  But from my perspective, it is consistent... it's just that there are multiple constituencies and views, each of which is self-consistent.

The API is consistent in its use of presentation timestamps and the presentation timeline for everything.  The API is for developers, who need to know how content works.

If we used the UI timeline in the API, it could make certain app features and decisions more difficult.  For example, if you know an actual timestamp from your DASH presentation, perhaps extracted from another service, and you want to use it to seek to a position or overlay metadata or whatever, using the UI timeline in the player would require even more info about the presentation timeline, which the player wouldn't be using and therefore wouldn't make available in this scenario.

The UI is consistent in showing the content that is available to the user.  The UI is for users, who just want to watch it and shouldn't have to know or care about how the underlying content works.

If we used the presentation timeline in the UI, users would be mad that they couldn't seek to "0", or wouldn't understand why their video started at time 39:59:49 (in the case of your sample content above).

Does this all make sense now?

**Comment by absidue** [comment]
Hiya @joeyparrish

I'm sorry for using such aggressive language. It rubbed me the wrong way seeing a question/feature request being reported as a bug. I'll refrain from commenting on issues on this repository in the future to avoid a similar situations arising.

As I can't contribute any code because of the CLA (having to doxx myself to contribute to an open source project is rather undesirable, also know that many people see CLAs as going against the spirit of open source), I thought I could make myself useful on the issue tracker, so that I can at least help out in some way, I'm sorry that I made things worse.

**Comment by joeyparrish** [comment]
@absidue, the CLA is Google policy that is out of my control, and I respect your choice not to sign it.

You are welcome to continue to contribute here on the issue tracker.  Just please use respectful language and remember that everyone, at some point, will need to have something patiently explained to them, including you.  That's just the nature of human communication.  And likewise, everyone, at some point, has been impatient or rude to others, including me.  I believe everyone has been in situations like this before, from every side, and we can all learn and move on productively.  I hope you won't let this small moment keep you from being a member of the community.

**Comment by jakubvojacek** [comment]
Hello @joeyparrish 

thank you for the detailed explanation. I was aware that I might have to workaround the content timing in code. Its just that we heavily use exoplayer and it works very differently there and the timing for such content starts from zero. That is why I was hoping that such a feature could be ported shaka player, perhaps under some flag. Since both players are from Google, it would make some sense that they'd behave the same I guess. 

Once again, thank you 🙏

**Comment by joeyparrish** [comment]
I understand.  Exoplayer is a great project, but Exo & Shaka are maintained by two very different teams and we differ in philosophy in some areas.  We apologize for any inconvenience, and we thank you for your understanding.
