### ISSUE TITLE
Is it possible to play MEDIA RAW DATA?

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#6276]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yep

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yep

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
4.5.0v

**What browser and OS are you using?**
Window & MAC

**Please ask your question**
I am grateful to use Shaka Player.

Is it possible to upload the raw video data to the browser RAM and play it with Shaka Player without playing the video through CDN? (Use blob X)
Playback format: FMP4

**Comment by joeyparrish** [comment]
I'm not sure I understand your question.  It sounds like you want to do something other than stream DASH/HLS/MSS the way people typically do.

---

If you want to do something custom, you might want to learn about Media Source Extensions (MSE) and how that works.  Maybe also DASH and HLS streaming formats.

Shaka Player can be thought of as a stack like this:

 - Parse and interpret DASH or HLS metadata
 - Make streaming decisions (what piece of media to fetch, and when)
 - Feed those media segments to MSE (where the rest happens inside the browser)

So if you want to do something custom, you might want to build on top of the browser's MSE API.

---

If you're talking about doing something more typical (like DASH or HLS), but getting media segments from somewhere other than the network, you can do that in Shaka.  First, you can play a blob URI of a single MP4 if you specify the MIME type when you call load().  (But you can also skip Shaka and just set `videoElement.src = 'blob:...'`.)

You might want to look at Shaka's offline storage system, which leverages a URI scheme plugin to get data from IndexedDB instead of the network.  You can also register your own URI scheme plugins.  For example, you can register a plugin for `foo` URIs, so that when you want to load `foo:bar`, your plugin gets to decide what that means and what data and headers to return.

---

Do either of these help?

**Comment by brodiddev** [comment]
Hmm, I don't quite understand.

I wonder if the following operations are possible in shakea player.
1. Save raw data of fmp4 video to browser memory
2. Play with shaka player
* CDN and blob should not be used.

**Comment by joeyparrish** [comment]
> I am curious about whether it is possible to download an fmp4 video, save it in an arrayBuffer, and customize and play the video's stats, pts, and fragment information like the loader API of hls.js.

> CDN and blob should not be used.

Why not?  If the whole file is already saved in a single ArrayBuffer, it would be the simplest and most efficient thing you could do.  You don't even need a player for that.  Download the fmp4 into an ArrayBuffer, create a blob or a data URI, then play that with `videoElement.src = URL.createObjectURL(blob)`.

But I think I don't really understand your goal.  Maybe if you explain your high-level goal instead of the specific solution you're thinking of, I might be better able to see another option for you, or I might be able to understand why you are avoiding `Blob`.

But as it stands, it seems like you don't need a player for this.  fetch + ArrayBuffer + Blob + createObjectURL + HTMLVideoElement are all built into the browser and will allow you to buffer an mp4 into memory, then play it.

**Comment by brodiddev** [comment]
My explanation was insufficient as I relied on a translator. sorry.
I have the following goals:
1. Download the segment.
2. Play downloaded files with shake player without server request without using fetch or XHR on the server.

I'm thinking of using registerScheme to change the scheme to a randomly created scheme when an https url comes in and play it.
But currently, the shaka 3018 TRANSMUXING_FAILED error occurs.

When outputting targetData, it comes out as shown in [A] below. Do you know what the problem is?

```
async function fileDownload(fileInfoList) {
    return await Promise.all(fileInfoList.map(each => {
        return new Promise((resolve, reject) => {
            let xhr = new XMLHttpRequest;
            xhr.open("GET", each.url, true);
            xhr.responseType = 'arraybuffer';
            xhr.send();
            xhr.addEventListener('load', function () {
                if (xhr.status === 200) {
                    resolve({
                        name: each.name,
                        url: each.url,
                        data: xhr.response
                    });
                }
            }, false);
        });
    }));
}
const customScheme = function(uri, request) {
	return new Promise((resolve, reject) => {
		const targetData = getFile(downloadFiles, uri);
		if (targetData) {
			resolve({
				data: targetData.data,
				uris: [uri],
				headers: {'content-type': 'application/octet-stream'}
			});
		}
	});
};
shaka.net.NetworkingEngine.registerScheme('https', customScheme, shaka.net.NetworkingEngine.PluginPriority.APPLICATION);
await player.load(downloadFiles[0].name);

[A]
data: ArrayBuffer(334)
name: "invalid_playlist_url.m3u8"
url: "/test-streams/big_buck_bunny_mp4_h264_aac_fhd.m3u8"
```

**Comment by joeyparrish** [comment]
@brodiddev, if your goal is to download segments and store them for later playback without the network, you should look at Shaka's offline API.  We already support this directly.  We can store any VOD content, and we use registerScheme with the `offline` scheme to serve the content later.

What our offline system does that your code snippet doesn't do is support serving both playlist/manifests and the segments themselves.  For example:

`offline:5` represents a piece of downloaded content.  When Shaka requests `offline:5` with `HEAD`, it gets back a `Content-Type` header that indicates the offline `ManifestParser` should be used to parse the response.  The offline `ManifestParser` uses the URI to look up the data in the database under ID `5`.  It then returns a manifest structure to the player that includes segment URIs like `offline:5/3/1`, `offline:5/3/2`, etc, where `5/3/1` means "content 5, stream 3, segment 1".

---

It seems like our offline APIs do everything you want to do.  I would **highly** recommend you try them.

If you want to build it yourself, you can, but you'll need to think about both stages of loading content: manifest and segments.  Your offline scheme can return a text manifest that is parsed by a normal parser like DASH or HLS (which may be complex to generate), or you can register a custom `ManifestParser` to go with your custom network scheme.  Either way, the manifest needs to contain segment URIs that point to your custom scheme to serve the segments.

Good luck!
