### ISSUE TITLE
Shaka player clock synchronization

### ISSUE THREAD

**Issue by chris-meekin** [shaka-project/shaka-player#6294]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Unrelated

**What version of Shaka Player are you using?**
The Cast SDK default, currently 4.3.4

**What browser and OS are you using?**
Chromecast

**Please ask your question**
Can you please advise which UTC Timing scheme is best to configure for DASH manifests when using the Shaka player as per [DASH-IF implementation guidelines: restricted timing model § 13.1. Clock synchronization](https://dashif-documents.azurewebsites.net/Guidelines-TimingModel/master/Guidelines-TimingModel.html#clock-sync) guidelines e.g. scheme urn:mpeg:dash:utc:http-iso:2014 with a value of https://time.akamai.com/?iso&ms or otherwise.

**Comment by joeyparrish** [comment]
It's entirely up to you.  There are always tradeoffs to make, though.

* If you use `http-iso`/`http-xsdate`, you need an active server that will be available when you need it and whose clock you can trust.  If you trust Akamai's endpoint for accuracy and availability, use that.  It's free.  If you don't trust Akamai, you can run your own, which will surely cost you some money that will scale with your traffic.
* If you use `http-date`, you need an available server whose clock you can trust and whose CORS headers allow access to the `Date:` header.  This could be anything, including the CDN you already use, if it has the right CORS headers and its clocks are accurate.  So the advantage over `http-iso` is that you may be able to rely solely on one service.  But again, you need to know you can trust their clocks and that the CORS settings allow access to the `Date:` header.
* If you use `direct`, then the manifest needs to be fresh every time it is requested.  This sounds like the most expensive option to me, but it also eliminates the need for any additional queries.

If you want a recommendation, personally, I would use `http-iso` with Akamai's time endpoint.  I think it's reliable.

But you have to judge the risks for yourself.  It's not an endpoint you control.  If something you don't control ever goes down or has a bad clock, you can't do anything about it but switch endpoints.  How long would that take you?  Weight that against how much you can rely on Akamai.  I doubt Akamai would ever shut it down with very little notice, for what that's worth, but it's not my business on the line if they ever do.

Does this help?

**Comment by joeyparrish** [comment]
?iso appears to return a full date and time in [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601).  Without that parameter, you get a Unix-style timestamp, in seconds since 1970 UTC.

?ms appears to add milliseconds to each of the above.  Without this parameter, sync may be off by as much as 1 second.

No matter which of these 4 you use, for `http-iso` or `http-xsdate`, Shaka Player parses it with `new Date(stringFromTheEndpoint)`.  If the input is a string, the Date() parser will handle ISO 8601 format, but not a unix timestamp.  So the difference in your results is probably caused by Shaka taking a string like "1709152523" and passing it to new Date as a string, which results in "Invalid Date" in the debugger.

To handle the unix-style timestamps, we would have to do something like:

```js
  if (isNumericString(stringFromTheEndpoint)) {
    // String is seconds, Date wants milliseconds:
    date = new Date(parseFloat(stringFromTheEndpoint) * 1000);
  } else {
    date = new Date(stringFromTheEndpoint);
  }
```

But these numeric strings with unix timestamps don't appear to conform to `http-iso` or `http-xsdate`.  The DASH spec (5th ed, 2022) says:

Of `http-iso`:

> The timing information is contained in the message body of the HTTP response to the above HTTP GET request and contains time value formatted according to ISO time code as defined in ISO/IEC 8601.

Of `http-xsdate`:

> The timing information is contained in the message body of the HTTP response to the above HTTP GET request and contains the time value which shall be formatted according to xs:dateTime as defined in W3C XML Schema Part 2: Datatypes specification.

If you look up the specs for `xs:dateTime` from XML, you see that it is also ISO-8601 format.

So the non-ISO URLs from Akamai are actually out of spec for use with `http-iso` or `http-xsdate` in DASH.

The only URLs that are spec-compliant for this purpose are https://time.akamai.com/?iso&ms and https://time.akamai.com/?iso .  Of the two, I suggest https://time.akamai.com/?iso&ms because it is more accurate.

Does this help?

**Comment by chris-meekin** [comment]
@joeyparrish yes that helps! Thank you very much for your help. Closing issue now.
