### ISSUE TITLE
The player does not play hls with x-program-date-time in the past (dvr)

### ISSUE THREAD

**Issue by Able1991** [shaka-project/shaka-player#6317]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
`v4.7.11-uncompiled`
Have error from 4.7.4 version

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
The demo

**What are the manifest and license server URIs?**
I sent it by mail

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default

**What did you do?**
try to play

**What did you expect to happen?**
playing

**What actually happened?**
player does not play
warnings in console like
```
log.js:141 (video:2) cannot find segment lookupTime: 104.24699997901917 presentationTime: 106.24699997901917
```

**Comment by theodab** [comment]
We're assuming that the live edge is at the current clock time, and trying and failing to find the segment that corresponds to that time. In the end, the player doesn't know what segment to append first.
I don't believe HLS has anything similar to the `UTCTiming` elements in DASH, so this might require adding a HLS configuration value to allow the developer to supply the DVR window themselves.

**Comment by Able1991** [comment]
this worked fine before the changes in version 4.7.4, this works correctly in hls.js and in the native player

**Comment by theodab** [comment]
Ah, I see. According to a git bisect, the culprit is 776b69dcb99e1f5dbd22181e40c22898f0b8e47a. No wonder I had been so confused about why the issue was happening, it was caused by a PR that someone else code reviewed!

It looks like disabling the code in that change causes your problem to go away, so I guess I'll need to find a different solution for that problem. Annoyingly, it looks like the test stream they provided for #5939 is no longer up. I'll try to reproduce their issue with other content.
