### ISSUE TITLE
Shaka player does not identify audio tracks with same language 

### ISSUE THREAD

**Issue by radiantmediaplayer** [shaka-project/shaka-player#6323]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Y

**If the problem is related to FairPlay, have you read the tutorial?**

N

**What version of Shaka Player are you using?**

4.7.11

**Can you reproduce the issue with our latest release version?**
Y

**Can you reproduce the issue with the latest code from `main`?**
Y

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**
Y

**What browser and OS are you using?**
Chrome 122 for Windows 11

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
https://streaming-vod.rtp.pt/dash/nas2.share//teste/faixas_audio_2024/saida_language_igual_titlediferente.mp4/manifest.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default from https://shaka-player-demo.appspot.com/demo

**What did you do?**
Start the DASH URL above in demo player

**What did you expect to happen?**
Player should show the audio tracks picker to select between the 2 audio tracks presented in the manifest

**What actually happened?**
Player starts but there is only one audio language to choose from when the manifest has 2 audio tracks documented
getAudioLanguagesAndRoles returns {language: 'pt', role: '', label: 'Português com audiodescrição'}
getAudioLanguages returns ['pt']
I understand that the audio tracks from the manifest could have <role> tags and that Shaka player properly picks on those audio tracks with different roles, but for this project we are using a DASH packager that does not support <role> tags. Yet we need to display the 2 audio tracks to the viewer but Shaka player is not returning the audio tracks with getAudioLanguagesAndRoles or getAudioLanguages. Note that dash.js correclty shows the audio tracks as can be seen at https://reference.dashif.org/dash.js/v4.7.4/samples/dash-if-reference-player/index.html with the same DASH URL. Also note that the audio tracks have different labels (Português vs. Português com audiodescrição).
How do we support this use-case?

**Comment by joeyparrish** [comment]
Your use of label is really what roles are for.  And the method getAudioLanguagesAndRoles() is doing exactly what it says: it's returning audio languages and roles, not tracks.  So this isn't a bug.

Have you tried getVariantTracks()?  I expect you would find all your tracks there.  If not, let us know, and we can investigate.

**Comment by radiantmediaplayer** [comment]
I understand getAudioLanguagesAndRoles or getAudioLanguages are not what I am looking for here. I also undertand now I can do all that I want with getVariantTracks. I guess this was more a question/feature request than a bug report, but I would like to provide the following feedback:
- There are getTextTracks|selectTextTrack methods to get|set textTrack and I was expecting to find the same for audio tracks but I could not find this in the documentation, am I correct to assume that getAudioTracks|selectAudioTrack do not currently exist in Shaka player? The reason I ask is because we have from time to time a use-case to support where a ABR MPEG-DASH stream has 2 audio tracks encoded at different bitrates but with the same language and no specific role set (as with the other sample DASH stream above). Example https://5b44cf20b0388.streamlock.net:8443/vod/smil:bbb.smil/manifest.mpd. This DASH stream has 2 audio tracks, the same language and same codec but are encoded at different bitrates. We still need to present to the viewer a UI to select from the audio track. Again I understand that getVariantTracks|selectVariantTrack can do what we want, there is just a bit more code management for us, but this is allright we can do it. 
- How is the default ABR logic in Shaka player affacted by this case-scenario, especially for https://5b44cf20b0388.streamlock.net:8443/vod/smil:bbb.smil/manifest.mpd? If I play that stream at https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=CUSTOM%20CONTENT;build=uncompiled I can see there is only 1 audio track presented to the viewer. Does this mean that the ABR logic in Shaka player also ignores 1 of the audio tracks? How does Shaka player select the audio track for ABR streaming in this case scenario? Is there a way to force a default audio track for ABR streaming? 
Thanks again for answering, you guys are doing a great job with Shaka player, from a developer standpoint this is a joy to play with this kind of library.

**Comment by joeyparrish** [comment]
In DASH, video and audio are always separate.  The variants are always (all video) x (all audio).  When we only supported DASH (many, many years ago), we had a selectAudioTrack().

In HLS, there may a more limited set of variants you can choose from.  In any give HLS playlist, there could be every combination of (video) x (audio), or it could be more limited.  It's just an inherent possibility in the structure of HLS.  It is also frequently the case that HLS streams are multiplexed, with audio+video in the same segments.  In that case, separating audio and video streams from a variant is really ugly.

So this is why we have selectVariantTrack() now instead of selectAudioTrack().  You can always express DASH content in terms of variants by multiplying (audio) x (video), but you can't always separate HLS variants into audio & video.

> I can see there is only 1 audio track presented to the viewer. Does this mean that the ABR logic in Shaka player also ignores 1 of the audio tracks? How does Shaka player select the audio track for ABR streaming in this case scenario?

Player gives AbrManager a list of variants it can pick from.  It has another layer of filtering after that based on config.abr.restrictions.

```js
    const adaptationSet = this.currentAdaptationSetCriteria_.create(
        playableVariants);
    this.abrManager_.setVariants(Array.from(adaptationSet.values()));
```

> This DASH stream has 2 audio tracks, the same language and same codec but are encoded at different bitrates. We still need to present to the viewer a UI to select from the audio track. Again I understand that getVariantTracks|selectVariantTrack can do what we want, there is just a bit more code management for us, but this is allright we can do it.

I think I see a solution.  I forgot we had this method, added back in 2019:

https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#selectVariantsByLabel

```js
player.selectVariantsByLabel('Português com audiodescrição');
```

It sets `this.currentAdaptationSetCriteria_` in Player to filter variants for ABR based on their audio label.

So long as every audio has a unique label, you can use this method.  You may also want to contribute something like `getAudioLabels()` to Player to make it easier to create the list for your UI.

Does this help?
