### ISSUE TITLE
registerRequestFilter seems to not work with mp4 videos

### ISSUE THREAD

**Issue by adrienprsn** [shaka-project/shaka-player#6347]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.7.11

**What browser and OS are you using?**
OSX 14.3.1 + latest Chrome

Hi !
I use shaka-player with React (custom implementation), for loading and viewing mp4 videos.
The videos I plan on using will be on a Amazon S3 bucket and require authentication.

I was planning on using `player.getNetworkingEngine().registerRequestFilter(() => {... })` to handle the auth but it seems like `registerRequestFilter` is only called when dealing with segmented videos like DASH-MPEG or HLS formats.

Is it accurate ?
If so, what would be an alternative ?

I need to authenticate each requests so that the auth token doesn't expire in the middle of a video.

Here is a minimal repro, you can the the console.log is never printed (see App.js line 26)

https://codesandbox.io/p/sandbox/festive-jang-l3l8qm

Thank you for your help

**Comment by joeyparrish** [comment]
Playing single MP4 video uses the src= attribute of the video element, where the browser makes all requests.  Single MP4 videos are not generally compatible with MediaSource playback, where the player makes all requests (and where it can pass them through a filter for you).

Unfortunately, due to the fact that MediaSource can't ingest general MP4s (only segments or fragments of fragmented MP4), there is nothing we can do to help you with this.

One alternative is that you could use a tool like Shaka Packager to package the content into fMP4 and DASH or HLS.

**Comment by adrienprsn** [comment]
Thank you for the explanation.
