### ISSUE TITLE
Google Cast not working when casting to v3 CAF Receiver

### ISSUE THREAD

**Issue by mrp1no** [shaka-project/shaka-player#6456]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

v4.7.12

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**

**If custom app, can you reproduce the issue using our demo app?**
Demo app uses CAF v2, not v3

**What browser and OS are you using?**
Chrome 123.0.6312.105, Ubuntu 22.04 LTS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://sherazadelibrary.org/test-stream/stream2/master.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default Shaka UI config from https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html
(Exact same code, except for receiver ID which is 9EC644F7)

Hosted on https://sherazadelibrary.org/shaka-player/cast-test.html

**What did you do?**

Cast video from https://sherazadelibrary.org/shaka-player/cast-test.html
Using Google codelabs Receiver demo

**What did you expect to happen?**
Receiver playing video with subtitles.
**What actually happened?**

When the device opens the Receiver the video is not being loaded

**Comment by joeyparrish** [comment]
The shortest way to reproduce this issue is to run this in the console of the Shaka Pleyr demo:

```js
video.ui.configure({'castReceiverAppId': chrome.cast.media.DEFAULT_MEDIA_RECEIVER_APP_ID})
```

Then load and cast a video.  You will see that the Shaka Player sender API is not compatible with the standard receiver.

However, the Shaka Player sender API was always intended to cast to a custom receiver app using the Shaka Player receiver API.  It has never worked with the default receiver.

The Shaka cast APIs are deprecated and will be removed in favor of direct Cast support in the Shaka Player UI.  This support will be compatible with the default receiver for content that the default receiver can play.  (Currently this excludes DRM content, but I am now responsible for the default receiver, too, so this limitation could be lifted.)

For now, I'm going to call this WAI from Shaka's point of view.  You can use the cast APIs in Shaka v4 on both sides, or you can use the Cast Sender SDK directly and use a non-Shaka receiver.
