### ISSUE TITLE
Adding support for a proprietary transmultiplexer without reassembling the player

### ISSUE THREAD

**Issue by npastuh0v** [shaka-project/shaka-player#6701]
Thank you for not passing by. There is a question about the player. Is it possible to add a transmultiplexer for your player file delivery format?

I'll tell you more about my case.

**Input data:**
There is a server that broadcasts video in fragmented mp4 (aka fmp4) format via Unix sockets. There is also a skill of working with such sockets from the browser side.

**What you want to get at the output:**
An expansion module or a transmultiplexer for shaka-player, which involves processing data received through this socket and playing it through an HTML5 player.

It would also be nice if you could provide an example of a ready-made transmultiplexer or some kind of project that can process data before feeding it to the player.

### I would be very grateful. Shaka Forever!!!

**Comment by joeyparrish** [comment]
It sounds like you're asking about a novel way to request/receive media segments, rather than using HTTP.  Is that right?

**Comment by npastuh0v** [comment]
Yes, that's true. I'm read all examples? located on this repository and i didn't find anything suitable

**Comment by avelad** [comment]
So what you want is to register a custom network scheme, the scheme documentation is at: https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.SchemePlugin

But since it is not very useful I recommend you look at the three schemes that we have in the code and see if it helps you:
https://github.com/shaka-project/shaka-player/blob/main/lib/net/http_xhr_plugin.js
https://github.com/shaka-project/shaka-player/blob/main/lib/net/http_fetch_plugin.js
https://github.com/shaka-project/shaka-player/blob/main/lib/offline/offline_scheme.js

**Comment by npastuh0v** [comment]
Thanks!! It helps me to edit this player for my wishes! Question closed!
