### ISSUE TITLE
Shaka player with Playready DRM report FAILED_TO_GENERATE_LICENSE_REQUEST error.(EDGE Broswer)

### ISSUE THREAD

**Issue by tongwu460** [shaka-project/shaka-player#6763]
I am using attachment(3261225582(9).zip) manifiest play with Playready DRM  in Shaka Demo V4.9.2 & got below error.
Appriciate if anyone can  give some suggestion why this error report & How to fix it?
DRM:Verimatrix.
Video Codecs="hev1.2.4.L153.B0"
Auido codecs="mp4a.40.2"

Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (Failed to execute 'generateRequest' on 'MediaKeySession': Initialization data for CENC is incorrect.,TypeError: Failed to execute 'generateRequest' on 'MediaKeySession': Initialization data for CENC is incorrect.,)

![image](https://github.com/shaka-project/shaka-player/assets/171927526/1e6cb8d4-8c72-4716-9268-36675f0532af)

 
[3261225582 (9).zip](https://github.com/user-attachments/files/15613692/3261225582.9.zip)

**Comment by tongwu460** [comment]
@avelad can you pls give some suggestion?

**Comment by BucherTomas** [comment]
@tongwu460 Your primary issue appears to be the value of `ContentProtection` descriptor within the mpd manifest.

As long as the descriptor consists of just `cenc:pssh` element as in your case, the Base64-encoded value must include the whole ISOBFF PSSH box including the PSSH header and the DRM SystemID followed by PSSH Data (in the case of PlayReady it's just XML PlayReady Header Object and its data size) while your value carries just the PSSH Data. This value must be used only with `mspr:pro` element of ContentProtection descriptor but not with `cenc:pssh`.

In other words, the value for `cenc:pssh` should be
`AAADsnBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAA5KSAwAAAQABAIgDPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBwAEsAMAB2ADUAaQA3AHgAdgB0AHEAQgA1ADMAVwBYAHAANQB3AHIAbQBRAD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AEkAUwBNADcARAArAHQATAB4AGgAcwA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcABzADoALwAvAHAAcgBsAHMALgBvAG8AcgBlAGQAbwBvAC4AdgBjAGEAcwAuAGUAdQAxAC4AdgBlAHIAaQBtAGEAdAByAGkAeAB1AGEAdABjAGwAbwB1AGQALgBuAGUAdAAvAFAAbABhAHkAUgBlAGEAZAB5AC8AcgBpAGcAaAB0AHMAbQBhAG4AYQBnAGUAcgAuAGEAcwBtAHgAPAAvAEwAQQBfAFUAUgBMAD4APABMAFUASQBfAFUAUgBMAD4AaAB0AHQAcABzADoALwAvAHAAcgBsAHMALgBvAG8AcgBlAGQAbwBvAC4AdgBjAGEAcwAuAGUAdQAxAC4AdgBlAHIAaQBtAGEAdAByAGkAeAB1AGEAdABjAGwAbwB1AGQALgBuAGUAdAAvAFAAbABhAHkAUgBlAGEAZAB5AC8AcgBpAGcAaAB0AHMAbQBhAG4AYQBnAGUAcgAuAGEAcwBtAHgAPAAvAEwAVQBJAF8AVQBSAEwAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==`

 instead of the current
`kgMAAAEAAQCIAzwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AcABLADAAdgA1AGkANwB4AHYAdABxAEIANQAzAFcAWABwADUAdwByAG0AUQA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgBJAFMATQA3AEQAKwB0AEwAeABoAHMAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAcwA6AC8ALwBwAHIAbABzAC4AbwBvAHIAZQBkAG8AbwAuAHYAYwBhAHMALgBlAHUAMQAuAHYAZQByAGkAbQBhAHQAcgBpAHgAdQBhAHQAYwBsAG8AdQBkAC4AbgBlAHQALwBQAGwAYQB5AFIAZQBhAGQAeQAvAHIAaQBnAGgAdABzAG0AYQBuAGEAZwBlAHIALgBhAHMAbQB4ADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+AGgAdAB0AHAAcwA6AC8ALwBwAHIAbABzAC4AbwBvAHIAZQBkAG8AbwAuAHYAYwBhAHMALgBlAHUAMQAuAHYAZQByAGkAbQBhAHQAcgBpAHgAdQBhAHQAYwBsAG8AdQBkAC4AbgBlAHQALwBQAGwAYQB5AFIAZQBhAGQAeQAvAHIAaQBnAGgAdABzAG0AYQBuAGEAZwBlAHIALgBhAHMAbQB4ADwALwBMAFUASQBfAFUAUgBMAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=`

Decode the Base64 strings to see the difference. That is why the PlayReady Content Decryption Module considers your shorter value invalid for initialization.

Further reading https://learn.microsoft.com/en-us/playready/specifications/mpeg-dash-playready#212-including-a-playready-object-in-the-mpd and https://www.w3.org/TR/eme-initdata-cenc/#example

**Comment by tongwu460** [comment]
@BucherTomas can i understand if I use winedine and H265 in Shaka player, also need to including the PSSH header in the ISOBFF PSSH box? 

DO you know any other player not require the PSSH header?

because I am facing issue to add the  PSSH header in the  ISOBFF  PSSH box.

**Comment by BucherTomas** [comment]
@tongwu460 Any content decryption module based on CENC standard will require the same structure, so the one for Widevine as well. It is not about a player, per se.

Also worthy mentioning, if you are planning to distribute your stream to browsers, be aware that their desktop versions do not support H.265 streams encrypted with Widevine. You would need to use H.264 or VP9 video codec for those.

**Comment by tongwu460** [comment]
@tongwu460  Thank you, I have notice H265 and Widevine issue, So I plan use EDGE + H265 + Playready.

But now facing this Header not return issue.

By the way, When I using EXO player + Widevine + H265 , I can play the encrypted channel even Header not return.

**Comment by tongwu460** [comment]
@BucherTomas  Do you know if Firefox browser support   H265 + Playready or   H265 + Widevine?

**Comment by BucherTomas** [comment]
@tongwu460

**Short answer:** No or at least not yet.

**Long answer:** Most desktop browsers (except Safari on Mac) do not support H.265 natively due to licensing. They might support it if the underlying GPU supports it and the OS allows the browser to leverage it or in case of Edge, if the user installs appropriate decoder in Windows.
However, once you add DRM into the equation, the support for H.265 on non-Safari desktop browsers is then almost non-existent as browsers then for example do not have access to the secure decoding path with the help of GPU required by hardware decryption.

You can check on Chromium-based browsers if they support encrypted H.265 by opening chrome://media-internals/ address in the browser and checking presence of hevc in the CDM tab.
You can find similar info on FIrefox by opening about:support and looking for Content Decryption Modules Information.

You can also check what DRM systems any browser supports by opening https://nightly-dot-shaka-player-demo.appspot.com/support.html and examining the DRM json object, if the system is not null, it is most likely supported.

This is the current state of things. In the meantime, Widevine browsers (Chrome) are now attempting to implement hardware decryption on Windows that borrows from PlayReady implementation (Netflix is already using it) or from what I saw they are attempting to add PlayReady (Firefox) as an alternative directly because only PlayReady is so integrated with the Windows system that it allows the secure video path to GPU. All things considered, in my opinion, this is the only option that might even open the possibility to support H265 + DRM in the future. But I assume that AV1 will take over anyway and there will be then no rush to add H.265 retroactively anymore.

And this whole explanation does not even go into details of differences and obstacles among various OSes. What is being worked on for Windows will not be applicable for Linux, etc.

**Comment by tongwu460** [comment]
@BucherTomas  HI, after I enable the header, some laptop EDGE browser is working can play  Encrypted channels, but some laptop still report below error:

Can you pls give more suggestion

[Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (Failed to execute 'generateRequest' on 'MediaKeySession': Failed to create MF PR CdmSession (3221226536),NotSupportedError: Failed to execute 'generateRequest' on 'MediaKeySession': Failed to create MF PR CdmSession (3221226536),)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6006)

[3261225582 (1).zip](https://github.com/user-attachments/files/16800165/3261225582.1.zip)

![1111](https://github.com/user-attachments/assets/5b7e7e9f-26de-487b-9585-f8fadd234b31)

**Comment by BucherTomas** [comment]
@tongwu460 Have you tried on those failing systems opening chrome://media-internals/ in Edge as I suggested? Do they even list "hevc" as supported for PlayReady capabilities in the CDMs tab?

You can also try opening https://devs.origin.cdn.cra.cz/play/prcdmhevc.html there, it should return simply "Created cdm.", if the combination of PlayReady + HEVC / AAC from your mpd manifest is supported on those given failing systems.

I would be repeating myself stating that making HEVC video codec work with DRM on desktop browsers can be an uphill battle.

**Comment by tongwu460** [comment]
@BucherTomas yes , i check , it show supported but still report above error.
![20240830-090624(WeLinkPC)](https://github.com/user-attachments/assets/8cf555e3-b323-4586-afc9-feb3137fac83)

![20240830-090634(WeLinkPC)](https://github.com/user-attachments/assets/c1dadbf5-ebc3-4334-8157-a1c7582fe7f9)

**Comment by BucherTomas** [comment]
@tongwu460 Ok, at least this confirms the actual error message FAILED_TO_GENERATE_LICENSE_REQUEST meaning that the error is occuring further down the DRM chain and the HEVC codec appears to be accepted.

Not sure what should be the best course of action here. This looks like a lot of trial and error might be needed to progress.

Do both the working and failing systems have the same hardware such as GPU and chipset and their drivers? Same OS build and Edge version? Do they have the official MS HEVC decoder installed?

Once the playback fails, open edge://media-internals/ in another tab and look at the last playback session at the bottom, copy the log here together with log from the system where it plays for comparison.

It seems strange that some systems would play and some not, since the actual error code is 3221226536 (0xc0000428) which Google suggests could be somehow associated with digital signatures in Windows but there is no hint as to what it might mean with regards to PlayReady CDM, maybe check that your GPU drivers are WHQL signed by running dxdiag. I am purely speculating as there is no official documentation to a lot of Windows error codes, so I have no more ideas.

Have you tried producing:

- a test H.264-encoded and PlayReady-encrypted stream

- a test HEVC-encoded but clear stream without PlayReady

instead to see if that particular stream version starts working everywhere?

**Comment by tongwu460** [comment]
@BucherTomas
In the No working laptop:
a test H.264-encoded and PlayReady-encrypted stream  -- also no working,same error.
a test HEVC-encoded but clear stream without PlayReady -- this is working 

[DxDiag-working laptop.txt](https://github.com/user-attachments/files/16828087/DxDiag-working.laptop.txt)
[DxDiag-no working laptop.txt](https://github.com/user-attachments/files/16828088/DxDiag-no.working.laptop.txt)

**Comment by tongwu460** [comment]
@BucherTomas 
Both Laptop I have install below two 
![截图1](https://github.com/user-attachments/assets/27548b50-2c72-4d5e-84f1-b7a39207a9b0)
![截图](https://github.com/user-attachments/assets/ad8dadf2-c5fe-4dae-96ef-10e50bf124bd)

**Comment by tongwu460** [comment]
@BucherTomas

Once the playback fails, open edge://media-internals/ in another tab and look at the last playback session at the bottom, copy the log here together with log from the system where it plays for comparison.

Can you pls support check the attachment? I am not clear about how to read the logs.
I am using the same playready channel, same version shaka-demo, same latest EDGE Browser, both install above HEVC Extensions, only Windows devices is different, different device Dxdiag have shared in above.

[No-working-log.txt](https://github.com/user-attachments/files/16828173/No-working-log.txt)
[Working-log.txt](https://github.com/user-attachments/files/16828174/Working-log.txt)
