### ISSUE TITLE
Non-application security issue

### ISSUE THREAD

**Issue by RedYetiDev** [shaka-project/shaka-player#6786]
Hello,

I’m a security researcher and may have identified a potential vulnerability in this project. Could you please provide me with a security contact to report this issue?

Please note that **no active testing** was conducted, and the vulnerability was discovered not through targeted analysis of this repository.

**Comment by avelad** [comment]
@joeyparrish ?

**Comment by joeyparrish** [comment]
> Please note that **no active testing** was conducted, and the vulnerability was discovered not through targeted analysis of this repository.

Please let us know how this project and repository were involved in your discovery.  One could interpret your statement above to mean that you didn't analyze our source code at all.  Whatever non-sensitive detail you can share on your process, please include it here for the benefit of everyone in the community.

You may send sensitive or private details to our maintainers group, shaka-player-maintainers@googlegroups.com.

To the community: after we receive the details from @RedYetiDev, we will assess the situation and disclose as much information as possible as soon as possible without compromising your applications and users.  I'll post details on this very issue.

**Comment by RedYetiDev** [comment]
Thanks! I'll send important information shortly.

As for my 'no active testing', while I did look at the repository, and how code within it executes, none of my testing was performed in a way that would impact others users (except myself). Additionally, I was not specifically targeting Shaka-Player, but several components of several different places.

**Comment by joeyparrish** [comment]
@RedYetiDev, thank you for the information.

To the community:

After reviewing the disclosure, there is no threat to your applications or users.  We will post more details after the issue has been resolved.

**Comment by joeyparrish** [comment]
We believe we have resolved the threat in full, so here is the full disclosure:

-----

The vulnerability was in our workflows, primarily our Selenium Lab workflow, but also possibly the Update Screenshots workflow which can call into it.

Our Selenium Lab workflow can only be triggered on a PR by a maintainer, but it also ran a custom action from the repo (set-commit-status).  Although the workflow itself is always run from `main` and not from the PR author's fork, the custom action was checked out by the workflow from the PR's head using `refs/pull/${{ inputs.pr }}/head`.  Since this symbolic reference could change meaning over time, this gave a PR author an opportunity to modify that custom action before it was checked out and executed.  For example:

1. Attacker sends a benign PR
2. Attacker asks for a test run in the lab
3. While the pre-build player job is running (a several-minute window), the attacker pushes a modified set-commit-status to the PR branch
4. When the test job begins, a new checkout occurs on the PR head with the modified set-commit-status
5. That modified action would then run in context of our lab with the ephemeral default GITHUB_TOKEN in the environment, where it might have been abused in some way

This has been resolved by:

  1. moving set-commit-status out of the shaka-player repo so a PR author cannot modify it ([shaka-project/shaka-github-tools#35](https://github.com/shaka-project/shaka-github-tools/pull/35), [shaka-project/shaka-github-tools#36](https://github.com/shaka-project/shaka-github-tools/pull/36), [shaka-project/shaka-player#6808](https://github.com/shaka-project/shaka-player/pull/6808))
  2. consolidating logic to compute git references in our workflows into a single, external action to resolve symbolic refs only one time, in only one way, even in context of nested workflows ([shaka-project/shaka-github-tools#37](https://github.com/shaka-project/shaka-github-tools/pull/37), [shaka-project/shaka-player#6811](https://github.com/shaka-project/shaka-player/pull/6811))

Only ephemeral tokens were used in the affected workflows, so there is no risk of any long-lived tokens having been leaked.  We did not investigate the ephemeral token's permissions, so they might not have been able to write to the repo in the first place.  But out of an abundance of caution, I have checked the commit history to confirm that nothing was added recently that shouldn't have been.

-----

**2,147,483,647 thank yous** to @RedYetiDev for the detailed report and collaboration on the solution!
