### ISSUE TITLE
Issue: Streaming High-Resolution Long Videos Results in Buffering

### ISSUE THREAD

**Issue by rk9155** [shaka-project/shaka-player#7162]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?** 4.10.9

**What browser and OS are you using?** Chrome/Edge - Window/Mac

**Please ask your question**

We are experiencing issues when streaming longer videos (approximately 40-60 minutes or more) using Shaka Player with MPEG-DASH, where higher resolution streams (720p and 1080p) fail to play properly. The video keeps buffering indefinitely and does not begin playback. In contrast, shorter videos (up to 30 minutes) stream without any issues across all resolutions.

**Context:**
We generate MPEG-DASH (MPD) files using ffmpeg, leveraging byte-range segments for chunked streaming. The streams are generated in three resolutions: 720p and 1080p. The behavior differs depending on the length of the video:

When Streaming Works: For shorter videos or lower resolutions (e.g., 480p), each chunk requested in the range header corresponds correctly to the downloaded byte size.

When Streaming Fails: For longer videos, especially in higher resolutions (1080p and sometimes 720p), the size of the downloaded chunks is significantly larger than the size specified in the range header. This results in the video continuously buffering without starting playback. Notably, no errors are reported in the console.

**FFmpeg Command:**
Below is the FFmpeg command used to generate the MPD and corresponding stream files:

            f'ffmpeg -y -i "{path}" -c:v libx264 -x264opts '
            f'"keyint=24:min-keyint=24:no-scenecut" -r 24 '
            f'-c:a aac -b:a 128k -bf 1 -b_strategy 0 -sc_threshold 0 -pix_fmt yuv420p '
            f'-map 0:v:0 -map 0:a:0? -map 0:v:0 -map 0:a:0? '
            # f'-map 0:v:0 -map 0:a:0? '
            # f'-b:v:0 250k -filter:v:0 "scale=-2:240" -profile:v:0 baseline '
            # f'-b:v:0 750k -filter:v:0 "scale=-2:480" -profile:v:0 baseline '
            f'-b:v:0 4000k -filter:v:0 "scale=-2:720" -profile:v:0 baseline '
            f'-b:v:1 6000k -filter:v:1 "scale=-2:1080" -profile:v:1 main '
            f'-single_file 1 -f dash "{self.file_path.rsplit(".", 1)[0]}.mpd"'
        

**Observations:** 

- Successful Stream:
Chunks are downloaded in small, correctly sized segments.
<img width="1436" alt="Screenshot 2024-08-16 at 9 04 28 PM" src="https://github.com/user-attachments/assets/381d685e-bdcd-4b8c-85ff-e7c56b97a9ce">

- Failed Stream:
The entire MP4 file is downloaded before playback begins, resulting in prolonged buffering.
It continue downloading the complete mp4 file before playing
<img width="1436" alt="Screenshot 2024-08-16 at 9 03 54 PM" src="https://github.com/user-attachments/assets/394356d0-1f9b-40dc-9fde-1698235fa89f">

**Sample MPD File:**
For reference, a sample MPD file from the failed stream can be found here
[sample_mpd.txt](https://github.com/user-attachments/files/16638802/sample_mpd.txt)

**Comment by avelad** [comment]
@joeyparrish can you review it? Thanks!

**Comment by joeyparrish** [comment]
> For longer videos, especially in higher resolutions (1080p and sometimes 720p), the size of the downloaded chunks is significantly larger than the size specified in the range header.

Here are some things to check:
 - What is the correct range?
 - Is this the range in the manifest?
   - If not, FFmpeg is to blame
 - Is this the range in the request headers?
   - If not, Shaka Player is to blame
 - Is this the range in the response headers?
   - If not, the web server or CORS is to blame

In your screenshots, I see an HTTP response code of "200".  A range request should generally have a response code of "206".

There are a few ways this can happen:

 - Shaka doesn't send a range request header (if the manifest is correct, this would be a Shaka Player bug)
 - The web server ignores the range request header (a real web server should support it, but for example, [python's built-in doesn't](https://bugs.python.org/issue42643))
 - A CORS issue prevents the range request header from being sent (shouldn't happen with Shaka Player because we don't use 'no-cors' mode)
 - The web server responds to the initial request with a redirect (302, etc), which causes range request headers to be lost (this is in the HTTP spec, not a bug, not in the player's control)

Does this help?
