### ISSUE TITLE
Is there any Reason to add the framerate Along with the resolution? Like 1080p60

### ISSUE THREAD

**Issue by Ravi-79** [shaka-project/shaka-player#7187]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
No, I couldn't find any

**If the question is related to FairPlay, have you read the tutorial?**

It's not related to fairplay

**What version of Shaka Player are you using?**
Latest - v4.10.10

**What browser and OS are you using?**
Windows 11 , Edge

**Please ask your question**

Is there any Reason to add the framerate Along with the resolution? Like 1080p60
![image](https://github.com/user-attachments/assets/3e67100a-b044-4063-8a4f-9fed5b34a51f)
![image](https://github.com/user-attachments/assets/96e040ae-7f89-4f5c-b8fc-dff11ed05d2e)

**Comment by absidue** [comment]
I requested that in https://github.com/shaka-project/shaka-player/issues/5749 although I did say at the time that if other people didn't want it, maybe it should be hidden behind a config option.

**Comment by absidue** [comment]
@roberto-sartori-gl I think the shaka-player developers are trying to avoid adding even more configurable options, as that means even more stuff to test and that could break. Unfortunately for you that means if you want non-standard functionality like always showing the bitrate, you are going to have to build your own quality selector and use that instead of the built-in one.
