### ISSUE TITLE
Some laptop can working in H265+Playready+EDGE, some laptop no working

### ISSUE THREAD

**Issue by tongwu460** [shaka-project/shaka-player#7244]
https://github.com/shaka-project/shaka-player/issues/6763

@BucherTomas Can you pls check above link last 3 line? if you have any idea about some laptop working in H265+Playready+EDGE, some laptop no working?

**Comment by BucherTomas** [comment]
Your issues have nothing to do with Shaka Player, so do not be surprised if the maintainers close the ticket.

As proven by your findings (for instance H.264 stream not working with PlayReady either on those affected systems and provided logs), your inability to decrypt the content is directly caused by the system.

In the meantime:

- media-internals playback log confirmed that MediaFoundation renderer for encrypted content is being used on both, that is good.

- it is the dxdiag log that might hint at your issues - Virtual Display Device adapter. If all the affected systems have this "GPU" as well, try to uninstall it. And update the regular Intel Xe drivers.

Any display virtualizing tech might trigger problems where production-level DRM is concerned. For that very same reason it might be safer to get rid of also your another virtual graphic adapter called "EShare Virtual Monitor Assistant V4" that can be seen in the dxdiag log. It is present also on the system where it works, but there might be later other DRM scenario which might conflict that do not manifest now.

You are using Verimatrix DRM services. If the Verimatrix PlayReady license server allows setting license rules directly in the license acqusition url or elsewhere, to verify that it is truly the virtual adapter causing the issue before uninstalling, you might attempt to set it according their documentation to the equivalent of `playenablers:(786627D8-C2A6-44BE-8F88-08AE255B01A7)` and `sl:150` as per reference specification of test PlayReady server https://testweb.playready.microsoft.com/Server/ServiceQueryStringSyntax . The value of GUID means that also virtual adapters would be allowed by the provided license and value of 150 for service level disables production-level PlayReady and allows non-certified hardware without extra protection to process the content as well. But this is just for your test, never use this in production.

No other abnormalities are sticking out in your logs, so this likely the last meaningful help I can provide.

**Comment by tongwu460** [comment]
@BucherTomas  Thank you for your support^_^
