### ISSUE TITLE
Release notes diff from last minor version

### ISSUE THREAD

**Issue by JJSarrasin** [shaka-project/shaka-player#7254]
Hello,

I just read your last release note for 4.11.0. I was wondering why do you list the full changelog since 4.10.0 (I guess) and not from 4.10.14. 

You probably do this because there wil be more 4.10.x minor versions.

Could you highlight the changes from the last minor version at this date ? It's easier to follow ;-)

**Comment by avelad** [comment]
@joeyparrish can you review it? Please!

**Comment by joeyparrish** [comment]
> I just read your last release note for 4.11.0. I was wondering why do you list the full changelog since 4.10.0 (I guess) and not from 4.10.14.

It is because the changelog is entirely automated, and based on the branch history.  `.0` releases are all released from `main`, and therefore the release tooling sees all the changes between `4.11.0` and `4.10.0` as being "in" this release.

> Could you highlight the changes from the last minor version at this date ? It's easier to follow ;-)

We used to maintain the changelog by hand, and when we did it that way, we would only include changes unique to that feature release.  However, it was just too much work, and we frequently made mistakes.  We omitted things that mattered, we added things accidentally that were reverted, etc.

For us to show only non-cherry-picked changes in the feature release, we would need that functionality in the release tools, which are here:

 - https://github.com/shaka-project/shaka-player/blob/6716ff00c411df5b284d0b705c0d7cd6ef2ec76e/.github/workflows/release-please.yaml#L18-L27
 - https://github.com/google-github-actions/release-please-action
 - https://github.com/googleapis/release-please

I've contributed changes to these tools before, so I know they are maintained and that the maintainers are reasonable.  This sounds like it could be a large change, though, so it might be necessary to form a rough plan and get the agreement of the maintainers before spending too much effort on a PR.

If you would like to lead that process, please link to a `release-please` discussion here so that others can pitch in and follow along.

Does this answer your question?

**Comment by JJSarrasin** [comment]
Thanks for the detailed answer !
It's not something critical, it's more like a comfort thing. I didn't knew it was automated.

I was taking Google's Media3 repository as an example, but they fill it manually, you can see for each version release the previous version it references: https://github.com/androidx/media/blob/release/RELEASENOTES.md
1.4.1 -> 1.4.0
1.4.0 -> 1.3.1 (last 1.3.x version known to this release date)
(potential 1.3.2 could logically reference 1.3.1)
