### ISSUE TITLE
Google Widevine DRM and Apple fairplay DRM protection against piracy

### ISSUE THREAD

**Issue by jasonkaplan79** [shaka-project/shaka-player#7356]
Problem:
I'm using a player like https://jplayer.org/ or https://github.com/vidstack/player/
But my videos can be pirated easily (even if you host videos using .m3u8 files), using chrome extensions.

I believe Shaka Player implements Google Widevine DRM and Apple fairplay DRM, to protect against video piracy. This would prevent videos from being downloaded by inspecting source, or using a chrome extension. Also, recording the screen while the video is playing would turn off the visuals, so that only the sound is audible. See the demo video on the homepage here (try and download the video using a chrome extension, try recording the screen while the video is playing, etc - you will not be able to download or record / capture the video): https://www.vdocipher.com/

How can I implement this exact behavior in my own player, like jPlayer or Vidstack? I am here because Shaka player advertises that it can do those things...however, when I tried the [demos here](https://index-dot-shaka-player-demo.appspot.com/) they did not work.

**Comment by joeyparrish** [comment]
@jasonkaplan79, for DRM, encryption must be applied to the videos, and a license server must be used to provide licenses with keys to authorized users.  It's not just a matter of a video player.  You also have to prepare the content and either host license infrastructure or use third-party license servers (paid or otherwise).

Does this help?

**Comment by jasonkaplan79** [comment]
@avelad 
I'm not sure how to implement Widevine and Fairplay, which is why I am here. 

For Shaka player, the README says:

- Encrypted content with PlayReady and Widevine
- Encrypted content with FairPlay (Safari on macOS and iOS 9+ only)
- DRM support matrix - Widevine and FairPlay supported

So then what do these mean?

**Comment by jasonkaplan79** [comment]
@joeyparrish Thank you, that definitely helps a bit. 
For my backend, I am using a Laravel web framework for creating my website. I would like to do implement Widevine and Fairplay to secure videos for DRM, and do exactly what is being done in the sample video on https://www.vdocipher.com

I want to do the above (which would imply both your points below) without any third party services or license servers
- apply encryption  to the videos
- use a license server to provide licenses with keys to authorized users (in the very simple case I would simply provide a license to my own website where my web application is hosted)

Is this possible? A tutorial or codebase on this would be SO helpful. 🙌

**Comment by joeyparrish** [comment]
> apply encryption to the videos

The actual encryption part is an open standard (ISO Common Encryption), so there are many tools to encrypt your content.  For example, [Shaka Packager](https://github.com/shaka-project/shaka-packager), [GPAC](https://github.com/gpac/gpac), etc.

> without any third party services or license servers

You simply can't do that.  Widevine, FairPlay, and PlayReady don't have open-source license servers AFAIK, and the actual licensing schemes and protocols are not open and can't be trivially implemented by you.  So you have to talk to Google, Apple, and/or Microsoft, or one of their resellers, in order to run a license server for their DRM systems.

If your users are in Chrome or Firefox, only Widevine DRM is available.  If your users are in Edge, only PlayReady DRM (and maybe Widevine?) is available.  If your users are on Safari or iOS, only FairPlay DRM is available.  So as much as we would love to live in a completely open ecosystem, DRM is fundamentally not entirely open.  Many people who are new to DRM might want to think of it like public key infrastructure, which although non-trivial, is at least open.  DRM just isn't.

One more option if you want to pursue it: Google runs Widevine license servers that third-parties can use with credentials as a license backend.  You can establish a relationship with Widevine, get training, get credentials, then use Widevine license servers.  You then run a "license proxy" service that decides which clients have authorization for a license, then signs the request with your private key, and forwards the request to Widevine's backend.  Widevine provides a sample proxy to partners.

I'm betting that doesn't sound appealing to you if you want to be 100% independent, but I wanted to make sure you knew that this is how Widevine does it.  I don't know what the equivalent might look like for PlayReady or FairPlay.  (But I worked at Widevine for about 8 years, and still work in the same building as them.)

I hope that helps clarify!

**Comment by jasonkaplan79** [comment]
@joeyparrish thank you for the detailed explanation! You are very knowledgeable on this topic and I appreciate your expertise.

You guessed right, the latter part (re: Widevine and the license servers) definitely sounds discouraging, because I do want to be 100% independent.
Just curious, what can I get with the "encryption part" (which, as you said, is an open standard with ISO Common Encryption) vs with Widevine, Fairplay (a license server)? Can I use one or the other, piecemeal, with specific benefits?

Would the former (ie the "encryption part") prevent users from downloading videos using Chrome extensions like:
* FetchV
* Video Downloader / Video Downloader professional / Video Downloader Plus
* Stream Recorder, etc
vs Preventing a screen recording from happening while the video is playing?

If I can prevent users from downloading videos, any pointers on how to proceed? That would be helpful. For context, I am using the Vidstack player, which has a nice front-end: https://github.com/vidstack/player

**Comment by joeyparrish** [comment]
You can't prevent users from downloading videos AFAICT.  Even with DRM.  To play the video and to download the video are fundamentally the same thing over the network.

The trick to DRM is that the video is encrypted, but you control the key and how it's used.  You don't want the user to have the key (where they could trivially decrypt a copy they downloaded), but you want the user's *device* to have the key for playback.  They key goes into a closed source component called a CDM (Content Decryption Module) inside the browser, where it can be used in the way you (the content owner) specify in the license (playback this much, these terms, etc).  In DRM, the key should never be accessible outside the CDM.

So encryption on its own just makes the video into unreadable garbage.  If you want them to play it, they need a way to decrypt it.  DRM gives the content owner control over how/when decryption can occur.

If your threat model is that your actual users, who you want to serve content to, could try to keep a copy of that content, DRM (and all of its unfortunate baggage) is the way this problem generally gets solved today.

If your threat model is non-users getting unauthorized access to your files, rather than malicious users, you can keep the content URLs behind an API that requires login.  Or you could authenticate each access to the content instead of using static content storage like a cloud service or CDN offers.  (This could get expensive, though.)

**Comment by jasonkaplan79** [comment]
> You can't prevent users from downloading videos AFAICT. Even with DRM. To play the video and to download the video are fundamentally the same thing over the network.

Thanks @joeyparrish, to be honest that's what I thought until I saw vdocipher. Playing the video and downloading the video over the network are no longer the same thing. At least, VdoCipher makes it MUCH harder, and I haven't figured out a way to download the videos. In fact, I challenge you to download the video on the homepage https://www.vdocipher.com

Thanks for explaining how CDM works...that makes a lot of sense. I want to implement this though, as an end-to-end solution, and that's where I'm struggling.

> If your threat model is that your actual users, who you want to serve content to, could try to keep a copy of that content, DRM (and all of its unfortunate baggage) is the way this problem generally gets solved today.
Yes, this is exactly the threat model I am trying to target / circumvent....authorized users that have access to viewing the content download it and pirate it to others. I want to make this extremely difficult with DRM encryption, if not impossible.

**Comment by jasonkaplan79** [comment]
Also see [this article from Mux](https://www.mux.com/blog/if-someone-can-watch-it-they-can-steal-it-securing-video-content-on-the-internet) and [this article from Bunny](https://docs.bunny.net/docs/widevine-integration).
I guess there is no free and open-source option :(

**Comment by joeyparrish** [comment]
https://d3dac6kw5cbsk4.cloudfront.net/media/PvBalNEso7eOS/846b1c5f/video_1080_yvgfn_3872.mp4 is the video from Vdocipher's home page.  It's encrypted with Common Encryption and played with DRM.

**Comment by joeyparrish** [comment]
> At least, VdoCipher makes it MUCH harder, and I haven't figured out a way to download the videos. In fact, I challenge you to download (or even record in high quality) the video on the homepage https://www.vdocipher.com/ The only way is to point another device like a phone camera to the video and record it with that separate device while the video is playing.

I just opened the debugger in Chrome and grabbed the URL from the network panel.  You can download it trivially.  You just can't play it without a license.

I determined that it's DRM content in two ways:

1. By going through the DOM in the debugger to find the video element, right-clicking, selecting "store as global variable", which creates "temp1", then evaluating "temp1.mediaKeys".  This is non-null, so the video element is playing with DRM through the MediaKeys API.
2. Because Vdocipher's home page says "DRM" right there.

**Comment by joeyparrish** [comment]
> Also see [this article from Mux](https://www.mux.com/blog/if-someone-can-watch-it-they-can-steal-it-securing-video-content-on-the-internet) and [this article from Bunny](https://docs.bunny.net/docs/widevine-integration).
I guess there is no free and open-source option :(

That Mux article is excellent.  And yes, sadly, there is no free and open-source DRM.  If there were, some would argue that it would be trivial to break, because the user is the threat.  Open source puts the user in control of the source code.

DRM is a pain and an expense for all involved, so it would be nice to have an alternative.  But for this particular threat model, I don't know what else you would do.

**Comment by joeyparrish** [comment]
> MediaKeys is empty, so I must not be inspecting the correct element.

It's not empty.  It is an instance of MediaKeys.  You can click the little arrow on the left to expand its properties.

The important details is "MediaKeys {}" is an instance of MediaKeys, so it's playing encrypted content.  If it's "null", it's clear content.

**Comment by jasonkaplan79** [comment]
@joeyparrish I see, thank you...

**Comment by joeyparrish** [comment]
Glad to help.  I know this is a very weird space if you are new to it.

**Comment by jasonkaplan79** [comment]
It is, and thank you. I will keep you posted as I make progress or have a question.
