### ISSUE TITLE
Audio not coming through

### ISSUE THREAD

**Issue by abelalvarez89** [shaka-project/shaka-player#7388]
Shaka Player Version: v4.11.4
Browser/OS: Chrome Version 129.0.6668.60, running in a ReactJS application

Issue:

I recently switched from HLS.js to Shaka Player, and I’m encountering an issue where the audio isn’t playing when using an .m3u8 source. The video plays fine, but there’s no sound, and the volume icon in the UI is disabled.

With HLS.js, both audio and video worked correctly from the same manifest. I’ve already tried the following:

Checked that the player is loading the manifest correctly
Ensured the volume is not muted
Looked at the browser’s autoplay policies
Is there something I’m missing regarding how Shaka Player handles audio tracks from HLS? Any insights or suggestions would be appreciated.

**Comment by tykus160** [comment]
@abelalvarez89 are you able to share a manifest with us, either here or to shaka-player-maintainers@googlegroups.com?

**Comment by joeyparrish** [comment]
We can't play your content with a copy of the playlist text.  Can you make the actual content accessible to us as a URL or zip file?  If something is wrong at decode time, we will never be able to reproduce it without access to your actual segments.

**Comment by jtdavis32608** [comment]
@joeyparrish I work with @abelalvarez89.  Attached is a .Zip containing a short playlist of a live event we captured.  DBIA.m3u8 will play with Edge, but not Chrome.  Chrome console shows the following error:

"PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding: {timestamp=7950666 duration=21333 size=11 is_key

I wonder if Edge is using a different demultiplexer than Chrome?

[Sample-HLS-TS.zip](https://github.com/user-attachments/files/17282611/Sample-HLS-TS.zip)

**Comment by joeyparrish** [comment]
I am also not able to play a zip file full of segments.  Sorry!  Maybe we can help you figure out the issue anyway.

I am not sure how Edge's architecture differs from Chrome, but it seems like a decoder error, not a demuxer error.  Edge on Windows might have access to different codecs at the OS level.

What codec is this?

**Comment by joeyparrish** [comment]
Oh, actually, I see this in the playlist text above:

`CODECS="mp4a.40.2,avc1.64001e"`

So it's just plain old AAC, then?

**Comment by joeyparrish** [comment]
You might need to file a Chrome bug, since it works differently in Edge and Chrome, even though they are built from the same basic source code.

I can promise that, like us, the Chrome team will be better able to help you with an accessible demo and/or content URL.  So I advise you to work on that access.

**Comment by jtdavis32608** [comment]
The .zip file contains segments and playlist.  Are you not able to host it and play them?  You are correct, the audio is AAC.
As a test, we tried changing the audio to MPEG-1 layer 2, but Shaka did not like that at all.

**Comment by jtdavis32608** [comment]
Can you try this link to see if you can access the stream?

http://216.155.126.146:7778/Channel1/DBIA.m3u8

**Comment by joeyparrish** [comment]
The playlist is there, but the segments all return 404

**Comment by jtdavis32608** [comment]
Interesting... they're loading for me.  Can you try this link?  This has a sample page loading the player and content

http://216.155.126.146:7778/JTTEST.html

**Comment by joeyparrish** [comment]
That plays for me.  I do get audio, briefly, on ChromeOS, before I get an audio decoder error.

Below is the full log from chrome:media-internals, formatted in Markdown.  The same in JSON dump from the browser is attached here: 
[shaka-issue-7388-media-internals-log.json](https://github.com/user-attachments/files/17284964/shaka-issue-7388-media-internals-log.json)

The key errors AFAICT are
`Failed to send audio packet for decoding: {timestamp=4814666 duration=21333 size=13 is_key_frame=1 encrypted=0}` and `{"code":1,...,"stack":[{"file":"media/filters/ffmpeg_audio_decoder.cc","line":170}]}`

This is the point where I would move to crbug.com.  If they can explain what the decoder error actually is, it may help explain what we're doing wrong.  Since hls.js works, it seems fair to assume we're doing _something_ wrong.  My best guess is that we have a bug in transmuxing, when we extract and separate audio and video from these segments.  @avelad might know something more about that, but he's off right now.

-----

|Timestamp|Property|Value|
|---|---|---|
|00:00:00.000|created|"2024-10-07 21:57:45.960311 UTC"|
|00:00:00.000|origin_url|"http://216.155.126.146:7778/"|
|00:00:00.000|kFrameUrl|"http://216.155.126.146:7778/JTTEST.html"|
|00:00:00.000|kFrameTitle|"Basic Shaka Player Example"|
|00:00:00.000|url|"blob:http://216.155.126.146:7778/a193a2ab-5208-4357-9801-1a5393ba9780"|
|00:00:00.000|info|"ChunkDemuxer"|
|00:00:00.000|kRendererName|"RendererImpl"|
|00:00:00.000|pipeline_state|"kStarting"|
|00:00:00.326|kAudioTracks|[{"bytes per channel":2,"bytes per frame":4,"channel layout":"STEREO","channels":2,"codec":"aac","codec delay":0,"discard decoder delay":false,"encryption scheme":"Unencrypted","has extra data":false,"profile":"unknown","sample format":"Signed 16-bit","samples per second":48000,"seek preroll":"0us"}]|
|00:00:00.328|kVideoTracks|[{"alpha mode":"is_opaque","codec":"h264","coded size":"320x180","color space":{"matrix":"BT709","primaries":"BT709","range":"LIMITED","transfer":"BT709"},"encryption scheme":"Unencrypted","has extra data":false,"hdr metadata":"unset","natural size":"320x180","orientation":"0°","profile":"h264 high","visible rect":"0,0 320x180"}]|
|00:00:00.331|seek_target|4.024999|
|00:00:00.333|kIsAudioDecryptingDemuxerStream|false|
|00:00:00.333|kAudioDecoderName|"FFmpegAudioDecoder"|
|00:00:00.333|kIsPlatformAudioDecoder|false|
|00:00:00.333|info|"Selected FFmpegAudioDecoder for audio decoding, config: codec: aac, profile: unknown, bytes_per_channel: 2, channel_layout: STEREO, channels: 2, samples_per_second: 48000, sample_format: Signed 16-bit, bytes_per_frame: 4, seek_preroll: 0us, codec_delay: 0, has extra data: false, encryption scheme: Unencrypted, discard decoder delay: false, target_output_channel_layout: STEREO, target_output_sample_format: Unknown sample format, has aac extra data: true"|
|00:00:00.333|info|"Cannot select DecryptingVideoDecoder for video decoding"|
|00:00:00.359|info|"VideoDecoderPipeline |decoder_| Initialize() successful"|
|00:00:00.359|kIsVideoDecryptingDemuxerStream|false|
|00:00:00.359|kVideoDecoderName|"OOPVideoDecoder"|
|00:00:00.359|kIsPlatformVideoDecoder|true|
|00:00:00.359|info|"Selected OOPVideoDecoder for video decoding, config: codec: h264, profile: h264 high, level: not available, alpha_mode: is_opaque, coded size: [320,180], visible rect: [0,0,320,180], natural size: [320,180], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"|
|00:00:00.359|pipeline_state|"kPlaying"|
|00:00:00.359|pipeline_state|"kSeeking"|
|00:00:00.360|pipeline_state|"kPlaying"|
|00:00:00.377|dimensions|"320x180"|
|00:00:00.377|kResolution|"320x180"|
|00:00:00.219|duration|4294967296|
|00:00:00.379|pipeline_buffering_state|{"for_suspended_start":false,"state":"BUFFERING_HAVE_ENOUGH"}|
|00:00:02.105|info|"Effective playback rate changed from 0 to 1"|
|00:00:02.105|event|"kPlay"|
|00:00:02.641|error|"Failed to send audio packet for decoding: {timestamp=4814666 duration=21333 size=13 is_key_frame=1 encrypted=0}"|
|00:00:02.641|error|{"code":1,"data":{},"group":"DecoderStatus","message":"","stack":[{"file":"media/filters/ffmpeg_audio_decoder.cc","line":170}]}|
|00:00:02.641|error|"audio decode error!"|
|00:00:02.641|error|"audio error during playing, status: PIPELINE_ERROR_DECODE"|
|00:00:02.641|error|{"code":3,"data":{},"group":"PipelineStatus","message":"","stack":[{"file":"media/renderers/audio_renderer_impl.cc","line":904}]}|
|00:00:02.642|pipeline_state|"kStopping"|
|00:00:02.642|event|"kPause"|
|00:00:02.642|pipeline_state|"kStopped"|
|00:00:16.787|info|"Selected video track: []"|

**Comment by jtdavis32608** [comment]
@joeyparrish we have reported the issue to crbug.com
Here is a link to the issue on crbug if you want to follow or add information:

https://issues.chromium.org/issues/372523841
