### ISSUE TITLE
[re-open] AV sync regression for HLS live for 2 seconds AV separated content #5528

### ISSUE THREAD

**Issue by shashikant-xgit** [shaka-project/shaka-player#7398]
I am not able to reopen [#5528 ](https://github.com/shaka-project/shaka-player/issues/5528) the issue, hence opening this issue. The two-second issue is what you fixed in [here](https://github.com/shaka-project/shaka-player/pull/6987) is not working with manifest.hls.sequenceMode=false. Once again, it will appear once we do sequenceMode=true.

Some background on sequenceMode flag enablements. We had another desync issue where we saw sync between audio and video in multiple of segment's duration. Let's say a segment is of 6 seconds duration, then we saw sync issues with 6, 12, 18 ... seconds. This issue got fixed once we disabled the segmentMode. But with this, the two-second sync issue appeared again.

Can you please look into the issue?

The details are present in the previous tagged bug.
We can close the bug once we reopen the above.

**Comment by avelad** [comment]
As mentioned in the original issue, the problem is a content issue that is incorrectly flagged in the playlist (timing), so we have applied a workaround that works with the default values, but we are not going to do a workaround for every possible configuration, sorry. Please fix the content at source.
