### ISSUE TITLE
[q] Enable screen capture protection on Clear Key

### ISSUE THREAD

**Issue by Chokoabigail** [shaka-project/shaka-player#7778]
Can EME screen capture protection be used in an HLS clear-key video stream? if so, which configuration should I add for this?

*best-effort  screen capture prevention, not looking for absolute protection without a proper DRM

**Comment by MarianoFacundoArch** [comment]
This is not up to the player. It's up to the DRM system itself you are using :).

**Comment by joeyparrish** [comment]
There is no API or configuration from the player to EME for this.  It is a feature of the underlying DRM, and it is either on or off according to the whims of the vendor.  For example, Widevine implements screen protections, but only on certain OSes.  If you're on a different OS, you can't get it.  If you're on an OS that supports it, you can't turn it off.  There is just no config for this.

If you want to raise an issue on https://github.com/w3c/encrypted-media, especially with an API proposal, we can discuss it in the web standards space.  I think it might be parallel to fields like `persistentState` in the EME config.  I would be in favor of something for this, because you aren't the first one to be confused by it.

I'm currently the co-editor of the EME spec.  The current charter of the Media Working Group doesn't include new features like this, but there is a process for "incubation" of new features outside of the charter, where they can get experimental implementations in browsers ahead of the official spec.  So it's not hopeless.

But for now, there's nothing the player can do until there's an API for it.
